//-------------------------------------------------------------------
//
//  This code is copyright 2007 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//
//-------------------------------------------------------------------
// #########################################################################################
//                                       HE bullet in Water detonation
// #########################################################################################
// =======================================================================================

class CHE_MediumWaterHitEffect
 // extends CWaterExplosionSprayEffect , CBaseEffect CTerrainExplosionDustEffect CWaterHE7576_85_88BulletHitDustEffect
{
  CHE_MediumWaterHitEffect()
  {
   // CreateEffect("LightExplosionSplash",         0.0);
   // CreateEffect("HEWaterSplashRefuseEffect",   0.0);    // //fire partical
    CreateEffect("HEWaterhvyHitDustEffect",     0.0);
    CreateEffect("HEWaterDustRefuseEffect",     0.1);   //    
    CreateEffect("HEWaterDustSinkRefuseEffect", 0.1);      //
    CreateEffect("WaterExplosionRingEffect",    0.0);
    CreateEffect("HEWaterSprayRefuseEffect",    0.3); //
    //CreateAndForgetEffect("HE7576_85_88WaterSignEffect", 0.0);
  }
}
// ==================================================== Splash  ==========================

class CHEWaterSplashRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ...............................................................................
   float EjectionPeriodMS   = 0.01;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.0;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.05;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 1.0;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 1.0;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 0.7;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = -1.0;   	//рандомизация смещени

   int ThetaMin             = 0;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 30;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_fx_fire2.tex";	//имя файла текстуры   Eff_fire1.tex

   boolean UseInvAlpha      = false;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 128;    	//размер текстуры в пикселах
   int     TexFrameX        = 128;     	//размер кадра по ширине
   int     TexFrameY        = 128;     	//размер кадра по высоте

   String ParticlesClass    = "CHEWaterSplashRefuseParticle";    //имя описателя частиц

// Data block ...............................................................................
CHEWaterSplashRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEWaterSplashRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 0.04;  		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 0.05;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = 0.5;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 1.0;		//коэффициент наследования начальной
									//  скорости эмитеера
   float ConstantAcceleration       = -1.0;		//собственное усокрение

   float SpinRandomMin              = -3.0;		//мин поворот частицы вокруг
									//  своей нормали(-3.14 до 3.14)
   float SpinRandomMax              =  3.0;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.1;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.0, 0.4, 1.0];				//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
                    new Color(0.95, 0.95, 0.98, 0.6),
                    new Color(0.95, 0.95, 0.99, 0.8),
                    new Color(0.95, 0.95, 0.99, 0.0)
                  ];

   Array sizes  = [0.2, 1.5, 0.3];				//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
					[0],
					[0]
                  ];
// Data block ..............................................................................
}
// ===================================================  Dust   ==========================

class CHEWaterhvyHitDustEffect
  extends CAnimatedParticleGenerator
{
  boolean m_LightingParticle    = true;
  float   m_LightingInterpolate = 0.4;

  CHEWaterhvyHitDustEffect()
  {
    SetAnimationTime(20.0);
    SetEffectTime(20.0);
    SetStartAndFinalFade(0.3, 0.4, 0.8);
    SetSizeParams(8.0, 0.8);
    SetBaseColor(new Color(0.99, 0.99, 0.99, 0.7));
  //  SetGravity(new Vector(0.0, 0.0, -1.5));   

    for (int I = 0; I < 8; I++)
    {
      SetAnimLength(16);
      SetFixedMaterial(new String(I));

      float Size = 4.0 - float(I) / 4;
      float Deviation = 3.0 + float(I) / 7;
      float Size1 = 2.0 - float(I) / 10;
      float Deviation1 = float(I) / 6;

//      logWarning("[TRACE] I is a "+new String(float(I)));
      GenerateAnimatedParticle(
          CEffectsArray::SmokeCloudLiteEffectSkin, I+3, float(I)*float(I)/2,
          new Vector(0.0, 2.0 - Deviation, float(I)/3), new Vector(0.0, 2.0 - Deviation, float(I)/3),
          new Vector(0.5, 0.5, 0.5), new Vector(Size, Size, Size)
        );
      GenerateAnimatedParticle(
          CEffectsArray::SmokeCloudLiteEffectSkin, I+3, float(I)*float(I)/4,
          new Vector(Deviation1, Deviation1, float(I)/4), new Vector(2.0 - Deviation1, 2.0 - Deviation1, float(I)/4),
          new Vector(0.5, 0.5, 0.5), new Vector(Size-0.1, Size-0.1, Size)
        );
      GenerateAnimatedParticle(
          CEffectsArray::SmokeCloudLiteEffectSkin, I+3, float(I)*float(I)/4,
          new Vector(0.0, 0.0, float(I)/3), new Vector(0.0, 0.0, float(I)/3),
          new Vector(0.5, 0.5, 0.5), new Vector(Size-0.1, Size-0.1, Size)
        );
    }
  }

}

class CHEWaterDustRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ...............................................................................
   float EjectionPeriodMS   = 0.001;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.001;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.071;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 8.5;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 2.0;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 1.0;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = 0.0;   	//рандомизация смещени

   int ThetaMin             = 0;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 60;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_test4.tex";	//имя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 128;    	//размер текстуры в пикселах
   int     TexFrameX        = 128;     	//размер кадра по ширине
   int     TexFrameY        = 128;     	//размер кадра по высоте

   String ParticlesClass    = "CHEWaterDustRefuseParticle";    //имя описателя частиц

// Data block ...............................................................................
CHEWaterDustRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ --------------------------------------------------------------------------
class CHEWaterDustRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ..............................................................................
   float ParticleLifetimeMS         = 2.5;  		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 0.6;		//вариация времени жизни(сек)
   float DragCoefficient            = 0.4;		//not in use
   float GravityCoefficient         = 0.60;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 1.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = -0.15;		//собственное усокрение

   float SpinRandomMin              = -3.1;		//мин поворот частицы вокруг
									// своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  3.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.001;		//скорость вращени
//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.1, 1.1, 2.7, 3.0];			//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
                    new Color(0.9, 0.9, 0.9, 0.3),
                    new Color(0.9, 0.9, 0.9, 0.4),
                    new Color(0.9, 0.9, 0.9, 0.4),
                    new Color(0.9, 0.9, 0.9, 0.4)
                  ];

   Array sizes  = [1.3, 1.8, 2.5, 3.0];			//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
					[0],
					[0],
					[0]
                  ];
// Data block ..............................................................................
}
// ================================================ Dust Sink ==============================
class CHEWaterDustSinkRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ...............................................................................
   float EjectionPeriodMS   = 0.001;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.00;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.2;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 6.0;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 0.0;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 0.0;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = 0.3;   	//рандомизация смещени

   int ThetaMin             = 90;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 92;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_water3.tex";	//имя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 256;     	//размер кадра по ширине
   int     TexFrameY        = 256;     	//размер кадра по высоте
   String ParticlesClass    = "CHEWaterDustSinkRefuseParticle";    //имя описателя частиц

// Data block .............................................................................
CHEWaterDustSinkRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEWaterDustSinkRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 1.0; 		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 4.0;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = 0.12;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 0.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = 0.01;		//собственное усокрение

   float SpinRandomMin              = -3.1;		//мин поворот частицы вокруг
									//  своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  3.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.1;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [10.0, 5.05, 0.08, 0.12, 0.5, 1.7, 2.0];	//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
 			new Color(0.99, 0.99, 0.99, 0.1),
 			new Color(0.89, 0.89, 0.89, 0.1),
			new Color(0.79, 0.79, 0.79, 0.1),
                    	new Color(0.69, 0.69, 0.69, 0.1),
                    	new Color(0.69, 0.69, 0.69, 0.1),
			new Color(0.69, 0.69, 0.69, 0.1),
                  	new Color(0.39, 0.39, 0.39, 0.0)
                  ];

   Array sizes  = [0.1, 1.0, 2.8, 3.4, 4.5, 6.8, 8.0];		//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
					[0],
					[0],
					[0],
					[0],
					[0],
					[0]
                  ];
// Data block ..............................................................................
}
// ================================================ Smoke ==================================
class CHEWaterSmokeRefuseEffect
  extends CBaseRefuseEffect
{
// Data block .............................................................................
   float EjectionPeriodMS   = 0.004;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.01;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.13;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 5.76;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 0.90;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 3.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 0.5;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = 0.0;   	//рандомизация смещени

   int ThetaMin             = 10;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 80;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = true; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_water3.tex";	 //Effect_7.tex Exp_Dust1.texимя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 256;     	//размер кадра по ширине
   int     TexFrameY        = 256;     	//размер кадра по высоте

   String ParticlesClass    = "CHEWaterSmokeRefuseParticle";    //имя описателя частиц

// Data block .............................................................................
CHEWaterSmokeRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEWaterSmokeRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 18.0; 		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 4.0;		//вариация времени жизни(сек)
   float DragCoefficient            = 0.45;		//not in use
   float GravityCoefficient         = 0.08;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 0.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = 0.02;		//собственное усокрение

   float SpinRandomMin              = -0.1;		//мин поворот частицы вокруг
									//  своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  0.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.04;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [6.0, 8.01, 9.42, 10.25, 6.0];		//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
 		    new Color(0.39, 0.39, 0.39, 0.8),
                    new Color(0.39, 0.39, 0.39, 0.8),
                    new Color(0.39, 0.39, 0.39, 0.8),
                    new Color(0.39, 0.39, 0.39, 0.8),
                    new Color(0.0, 0.0, 0.0, 0.0)
                  ];

   Array sizes  = [1.0, 4.0, 6.5, 8.0, 12.0];		//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
			  [0],
			  [0],
			  [0],
			  [0]
                  ];
// Data block ..............................................................................
}
// ================================================ Spray ==================================
class CHEWaterSprayRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ..............................................................................
   float EjectionPeriodMS   = 0.005;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.000;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.1;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 1.0;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 3.5;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 8.0;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = 0.0;   	//рандомизация смещени

   int ThetaMin             = 30;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 70;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.0;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_water3.tex";	//имя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 256;     	//размер кадра по ширине
   int     TexFrameY        = 256;     	//размер кадра по высоте

   String ParticlesClass    = "CHEWaterSprayRefuseParticle";    //имя описателя частиц

// Data block .............................................................................
CHEWaterSprayRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEWaterSprayRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 5.5; 		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 0.2;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = 0.2;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 1.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = -0.01;		//собственное усокрение

   float SpinRandomMin              = -3.1;		//мин поворот частицы вокруг
									//  своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  3.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.005;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.0, 0.3, 0.6, 1.0];			//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
                    new Color(0.95, 0.95, 0.99, 0.8),
                    new Color(0.95, 0.95, 0.99, 0.6),
                    new Color(0.95, 0.95, 0.99, 0.4),
                    new Color(0.95, 0.95, 0.99, 0.0)
                  ];

   Array sizes  = [9.0, 12.0, 19.0, 24.0];			//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
                    	  [0],
			  [0],
			  [0]
                  ];
// Data block ..............................................................................
}

class CWaterRingEffect
  extends CAnimatedParticleGenerator
{
  CWaterRingEffect(
      float _Time,
      float _Size
    )
  {
    SetAnimationTime(_Time);
    SetEffectTime(_Time);
    SetRenderLayer(PRIMLAYER_WATER_EFFECTS);
    SetCoordSystemType(CRDSYS_Origin);

    SetSizeParams(1.0, 0.5);
    SetPrimitiveType(EPPID_STATIC_PLANE_XY);
    SetStartAndFinalFade(0.0, 0.5);

    GenerateAnimatedParticle(
        CEffectsArray::WaterSprayEffectSkin, 3, 5.0,
        new Vector(0.0, 0.0, 0.0), new Vector(0.0, 0.0, 0.0),
        new Vector(1.0, 1.0, 1.0), new Vector(_Size, _Size, 1.0)
      );
  }
}

class CWaterExplosionRingEffect
  extends CWaterRingEffect
{
  CWaterExplosionRingEffect()
  {
    CWaterRingEffect(7.0, 60.0);
  }
}