//-------------------------------------------------------------------
/*
  Array  Animation = [
      ["L_Wheel01_lift", ["joint_WheelLeftMain1_UP", 0, 2]],
      ["L_Wheel02_lift", ["joint_WheelLeftMain2_UP", 0, 2]],
      ["L_Wheel03_lift", ["joint_WheelLeftMain3_UP", 0, 2]],
      ["L_Wheel04_lift", ["joint_WheelLeftMain4_UP", 0, 2]],
      ["L_Wheel05_lift", ["joint_WheelLeftMain5_UP", 0, 2]],
      ["R_Wheel01_lift", ["joint_WheelRightMain1_UP", 0, 2]],
      ["R_Wheel02_lift", ["joint_WheelRightMain2_UP", 0, 2]],
      ["R_Wheel03_lift", ["joint_WheelRightMain3_UP", 0, 2]],
      ["R_Wheel04_lift", ["joint_WheelRightMain4_UP", 0, 2]],
      ["R_Wheel05_lift", ["joint_WheelRightMain5_UP", 0, 2]],
      ["body_recoil_bf", ["Body", 0, 10]],
      ["body_recoil_fb", ["Body", 10, 20]],
      ["body_recoil_lr", ["Body", 20, 30]],
      ["body_recoil_rl", ["Body", 30, 40]],
      ["gun_a", ["Weapons_Base", 0, 1]],
      ["gun_a_recoil", ["Weapon_A", 0, 30]],
      ["luk_commander", ["Commander", 0, 60]],
      ["luk_BC_open", ["Luk_B", 0, 3], ["Luk_C", 0, 3]],
      ["luk_DG_open", ["Luk_D", 0, 3], ["Luk_G", 0, 3]],
    //  ["luk_body_driver", ["driver_l_Arm_Left", 0, 20], ["driver_l_Arm_Right", 0, 20], ["driver_l_Elbow_Left", 0, 20], ["driver_l_Elbow_Right", 0, 20], ["driver_l_Hand_Left", 0, 20], ["driver_l_Hand_Right", 0, 20], ["driver_l_Head", 0, 20], ["driver_l_Head2", 0, 20], ["driver_l_Hips", 0, 20], ["driver_l_Shoulder_Left", 0, 20], ["driver_l_Shoulder_Right", 0, 20], ["driver_l_Spine", 0, 20], ["driver_l_Spine1", 0, 20], ["driver_l_Weapon", 0, 20]],
    //  ["luk_body_open", ["Luk_A", 0, 1]],
      ["turret_a", ["Turret_A", 0, 1]],
      ["wheels_left", ["WheelLeftFront", 0, 60], ["WheelLeftMain1", 0, 60], ["WheelLeftMain2", 0, 60], ["WheelLeftMain3", 0, 60], ["WheelLeftMain4", 0, 60], ["WheelLeftMain5", 0, 60], ["WheelLeftRear", 0, 60]],
      ["wheels_right", ["WheelRightFront", 0, 60], ["WheelRightMain1", 0, 60], ["WheelRightMain2", 0, 60], ["WheelRightMain3", 0, 60], ["WheelRightMain4", 0, 60], ["WheelRightMain5", 0, 60], ["WheelRightRear", 0, 60]]
    ];

  Map    ConfigSets = new Map([
                               [ "Body_CrashedSet", [ "Commander_crashed", "Driver_crashed"] ],
                               [ "Body_NormalSet", [ "Commander", "Driver" ] ]
                               ]);

    */
//-------------------------------------------------------------------

// Unit Explosion
class CSU122_SPExplosion
  extends CHeavyTankExplosion
{
  float  Damage   = 5.0;
  float  Radius   = 1.0;
}

// Main cannon section
// Main cannon animator
class CSU122_SPGunTargetingAnimatorA
  extends CTargetingAnimator
{
  String HorAnimName    = "turret_a";
  String VerAnimName    = "gun_a";

  float  LeftEndAngle   =  9.0;
  float  RightEndAngle  = -9.0;
  float  TopEndAngle    =  -5.0;
  float  BottomEndAngle =  20.0;
}
// Main cannon bullet explosion
class CSU122_SPGunCalibreBulletExplosion
  extends CTankT34_85_44GunCalibreBulletExplosion
{
  float  Damage   = CPiercing::GunSU122_SPCalibreDamage;
  float  FireDamage   = CPiercing::GunSU122_SPCalibreFireDamage;
  float     Radius     = CPiercing::GunSU122_SPCalibreRadius;
 // Component Debris     = new CSU122_SPGunCalibreBulletDebrisCloud();  
}

class CSU122_SPGunCalibreBulletDebrisCloud
{
  int    DebrisQuantity  = CPiercing::GunSU122_SPCalibreDebrisQuantity;
  String DebrisPatternID = "SU122_SPGunCalibreBulletDebris";
  float  DebrisSpeed     = 300.0;
  float  DebrisSpeedDev  = 50.0;
  Vector DebrisDir       = new Vector(0.0, 0.0, 1.0);
  float  DebrisMinAngle  = 0.0;
  float  DebrisMaxAngle  = 90.0;
}

class CSU122_SPGunCalibreBulletDebrisControl
{
  Array     Classificator = [];
  boolean   IsMotionBlur  = true;
  float     MaxDistance   = CPiercing::GunSU122_SPCalibreDebrisMaxDistance;
  String    ExplosionId   = "SU122_SPGunCalibreBulletDebrisExplosion";
  float     Mass          = 0.02;
}

class CSU122_SPGunCalibreBulletDebrisExplosion
  extends CBaseExplosion
{
  String EffectId = "";
  String SoundId  = "";
  float  Damage   = CPiercing::GunSU122_SPCalibreDebrisDamage;
}

class CSU122_SPGunHEBulletExplosion
  extends CHEGun88BulletExplosion
{
  float  Damage   = CPiercing::GunSU122_SPHEDamage;
  float  FireDamage   = CPiercing::GunSU122_SPHEFireDamage;
  float     Radius = CPiercing::GunSU122_SPHERadius;
//  Component Debris = new CSU122_SPGunHEBulletDebrisCloud();
}

class CSU122_SPGunHEBulletDebrisCloud
{
  int    DebrisQuantity  = CPiercing::GunSU122_SPHEDebrisQuantity;
  String DebrisPatternID = "SU122_SPGunHEBulletDebris";
  float  DebrisSpeed     = 300.0;
  float  DebrisSpeedDev  = 50.0;
  Vector DebrisDir       = new Vector(0.0, 0.0, 1.0);
  float  DebrisMinAngle  = 0.0;
  float  DebrisMaxAngle  = 90.0;
}
class CSU122_SPGunHEBulletDebrisControl
{
  Array     Classificator = [];
  boolean   IsMotionBlur  = true;
  float     MaxDistance   = CPiercing::GunSU122_SPHEDebrisMaxDistance;
  String    ExplosionId   = "SU122_SPGunHEBulletDebrisExplosion";
  float     Mass          = 0.02;
}

class CSU122_SPGunHEBulletDebrisExplosion
  extends CBaseExplosion
{
  String EffectId = "";
  String SoundId  = "";
  float  Damage   = CPiercing::GunSU122_SPHEDebrisDamage;
}
class CSU122_SPGunCalibreBulletControl
  extends CCalibreBulletControl
{
  String    ExplosionId  = "SU122_SPGunCalibreBulletExplosion";
  float     BulletSpeed  = CPiercing::GunSU122_SPCalibreBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::GunSU122_SPCalibreMaxDistance;
  float     PenetrationPower      = CPiercing::GunSU122_SPCalibrePenetrationPower;
  Array     PenetrationByDistance = CPiercing::GunSU122_SPCalibrePenetrationByDistance;
  float     PenetrationModifierMin   = CPiercing::GunSU122_SPCalibrePenetrationModifier[0];
  float     PenetrationModifierMax   = CPiercing::GunSU122_SPCalibrePenetrationModifier[1];
}

class CSU122_SPGunHEBulletControl
  extends CHEBulletControl
{
  String    ExplosionId  = "SU122_SPGunHEBulletExplosion";
  float     BulletSpeed  = CPiercing::GunSU122_SPHEBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::GunSU122_SPHEMaxDistance;
  float     PenetrationPower      = CPiercing::GunSU122_SPHEPenetrationPower;
  Array     PenetrationByDistance = CPiercing::GunSU122_SPHEPenetrationByDistance;
}
class CSU122_SPHEAmmo
{
  final static String BulletPatternId = "SU122_SPGunHEBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],[]];
  final static float  LoadingTime     = 0.0f;
}
class CSU122_SPCalibreAmmo
{
  final static String BulletPatternId = "SU122_SPGunCalibreBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],["HUMAN", "VEHICLE"]];
  final static float  LoadingTime     = 0.0f;
}

// Main cannon properties
class CSU122_SPGun
    extends CHeavyGun, CWeaponFireRecoil
{
//  String CloudEffectId   = "HeavyGunFireMuzzleEffect";
  float  InitBulletSpeed = 0.0f;
  float  FireDeviation   = 1.2;
  float  MinFireDeviation   = 0.25;
  Vector GravityVector   = CPiercing::ShellGravityVector;
  final static boolean HighTrajectory  = false;

  final static String BulletPatternId = "";
  final static String FireSoundId     = "FeldHowitzer";
  final static String FireEffectId    = "HeavyGunFireMuzzleEffect";
  


  final static Array Ammo = [
                              new CSU122_SPCalibreAmmo(),
                              new CSU122_SPHEAmmo()
                            ];

  //$TMP TEST DATA
  final static Array AmmoTargetUse    = [
                                          //HEAVYTANK
                                          [0, [["HEAVYTANK"],[]], [[500.0, 25.0, 2000.0, 100.0], [[1000.0, 40.0], [1500.0, 80.0]]]],
                                          [1, [["HEAVYTANK"],[]], [[500.0, 75.0, 2000.0, 0.0  ], [[1000.0, 60.0], [1500.0, 20.0]]]],
                                          //TANK
                                          [0, [["TANK"],     []], [[500.0, 35.0, 2000.0, 100.0], [[1000.0, 45.0], [1500.0, 90.0]]]],
                                          [1, [["TANK"],     []], [[500.0, 65.0, 2000.0, 0.0  ], [[1000.0, 55.0], [1500.0, 10.0]]]],
                                          //VEHICLE
                                          [1, [["VEHICLE"],  []], [[500.0, 50.0, 2000.0, 100.0], [[1000.0, 90.0], [1500.0, 100.0]]]],
                                          //HUMAN
                                          [1, [["HUMAN"],    []], [[500.0, 1.0, 1500.0, 0.0],   [[1000.0, 0.0]]]],
                                          //BLD_WAR
                                          [0, [["BLD_WAR"],  []], [[500.0, 90.0, 1000.0, 100.0], []]],
                                          [1, [["BLD_WAR"],  []], [[500.0, 10.0, 1000.0, 0.0  ], []]],
                                          //BLD_CIV
                                          [1, [["BLD_CIV"],  []], [[500.0, 80.0, 1000.0, 100.0], []]]
                                        ];

  final static boolean CanFireInMove  = true;
  
  final static float  LockAngleHMin    = -9.0;
  final static float  LockAngleHMax    =  9.0;
  final static float  LockAngleVMin    = -5.0;
  final static float  LockAngleVMax    =  20.0;
  final static float  BlockedLockAngle =  4.0;

  final static float DirectionSpeedH  = 1.5; // deg / sec  • horizontal
  final static float DirectionSpeedV  = 1.0; // deg / sec  • vertical

  Component DirectionSoundH  = new #Emitter<CTankMediumTurretDirectionSoundV>();
  Component DirectionSoundV  = new #Emitter<CTankMediumTurretDirectionSoundV>();

  final static int     Ammunition     = 2000;        // wrong value

  //final static float MinDistance      = 1;
  //final static float MaxDistance      = 400;

  // *** Gun parameters for behavior
  final static int  FirePeriod        = 9000; // ms
  final static int  FirePeriodRandAdd = 2500; // ms

  final static boolean BurstFire      = false;
  final static int  BurstTime         = 0; // ms
  final static int  BurstTimeRandAdd  = 0; // ms

  final static int  BurstDelay        = 0; // ms
  final static int  BurstDelayRandAdd = 0; // ms

  // gun specific fire mask with priorities
  final static Array GunSpecificFireMask = [
                                [["GROUND"],[]],    // high priority mask: RestrictTo, Exclude
                                [[],[]], // low priority target with a pulley in the middle
                                [[],[]]             //
                              ];
  Component FireAnimator = new #LineAnimator<CSU122_SPFireAnimation>();
}

class CSU122_SPBaseTrack
{
  String  JointName           = "";
  String  TrackTexName        = "Textures/u_veh_t34_track550.tex";
  String  WheelAnimName       = "";

  Array   TrackTexScrollScale = [0.0, -0.4];
  float   WheelRotateScale    = 0.04;
  float   RealTrackPathScale  = 2.0f;
  boolean IsLeftTrack;

  float   WheelRadius         = 0.417 + 0.0574; // whell radius + track radius
  float   WhellLiftDown       = 0.158;         // max down wheel offset
  float   WhellLiftUp         = 0.085;         // max up wheel offset

  // Collision mask [restrict], [exclude]
  Array   CollisionMask = [[CLASSIFICATOR_WALK_SURFACE], []];
}

class CSU122_SPLeftTrack
  extends CSU122_SPBaseTrack
{
  String  JointName     = "TrackLeft";
  String  WheelAnimName = "wheels_left";
  boolean IsLeftTrack = true;

  Array   WhellsAnimation =
  [
    // joint name,            animation name,            down    up
    //
    ["WheelLeftMain1", "L_Wheel01_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain2", "L_Wheel02_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain3", "L_Wheel03_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain4", "L_Wheel04_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain5", "L_Wheel05_lift", WhellLiftDown, WhellLiftUp, WheelRadius]
  ];
}

class CSU122_SPRightTrack
  extends CSU122_SPBaseTrack
{
  String  JointName     = "TrackRight";
  String  WheelAnimName = "wheels_right";
  boolean IsLeftTrack   = false;

  Array   WhellsAnimation =
  [
    // joint name,            animation name,            down    up
    //
    ["WheelRightMain1", "R_Wheel01_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain2", "R_Wheel02_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain3", "R_Wheel03_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain4", "R_Wheel04_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain5", "R_Wheel05_lift", WhellLiftDown, WhellLiftUp, WheelRadius]
  ];
}

// Fire Animator
class CSU122_SPFireAnimation
{
  final static String  AnimationName     = "gun_a_recoil";
  final static float   AnimationTime     = 1.0;
}

// Behavior
class CSU122_SPBehaviorParams extends CBaseBehaviorParams
{
  float   MaxAttackSpeed    = 4.0;
}

class CSU122_SPBehavior extends CBaseSAUBehavior
{
  final static Component SpecParams = new CSU122_SPBehaviorParams();

 int      AttackStyle        = AttackStyle_SAU;             //       /*     AttackStyle_LightTank;     */
  boolean  CanMove            = true;
  boolean  HasRouter          = true;
  boolean  HasRadar           = true;
  boolean  ForceFrontInAttack = true;
  float    NonRotatableAngle = 9.0;   


  float   CollisionRadius = 8.5;        //
  float   AttackDistanceMin =  50.0;
  float   AttackDistanceMax = 12400.0;

  // *** radar parameters

  float MaxRadarDistance = 12400.0; // m
  float MinRadarDistance = 50.0;    // m
  float MaxRadarAngle    = 180.0;

  int    UpdateRadarPeriod        = 4000; // ms
  int    UpdateRadarPeriodRandAdd = 1000; // ms

  // radar visibility
  float  StaySpeed            = 0.5f;
  String MovingClassificator  = "MOVING_UNIT";
  String FireingClassificator = "TARGETING_UNIT";

  boolean SpecVisibilityCheck = true;

  Array ViewProbabilityByDistance = [[MinRadarDistance, 2.0f, MaxRadarDistance, 0.5],
                                            [
                                            ]
                                           ];

  final static Array ViewProbabilityByAngle = [[- Math_PI, 0.3f, Math_PI, 0.3],
                                         [
                                          [1.0f, 1.0f]
                                         ]
                                        ];

  final static Array ViewProbabilityByState = [
                                          [1, 2.5f] // UST_ATTACK
                                        ];

  final static Array ViewProbabilityByMask =  [
                                          [["MOVING_UNIT"],[], 2.0f],
                                          [["TARGETING_UNIT"],[], 2.0f],
                                          [["OPENLANDSCAPE_UNIT"],[], 2.0f],
                                          [["BUSHLANDSCAPE_UNIT"],[], 1.9f],
                                          [["FORESTLANDSCAPE_UNIT"],[], 1.0f],
                                          [["CLOSELANDSCAPE_UNIT"],[], 1.0f]
                                        ];

  float ViewProbabilityByPreviousStep = 2.0f;


  // *** movement physical parameters

  // physical limitations
  float   MaxRotateSpeed                = 2.0f;
  Vector  MaxSpeed                      = new Vector( 6.5, 0, 0);   // m/s
  Vector  MaxNegativeSpeed              = new Vector( 6.4, 0, 0);   // m/s
  Vector  MaxAccelleration              = new Vector( 0.8, 0, 0);    // m/(s*s)
  Vector  MaxNegativeAccelleration      = new Vector( 1.5, 0, 0);  // m/(s*s)
  Vector  MaxBrakingAccelleration       = new Vector( 2.5, 0, 0);   // m/(s*s)
  Vector  MaxAngleSpeed                 = new Vector(   0, 0, 3.0);    // [rad/s]
  Vector  MaxAngleAccelleration         = new Vector(   0, 0, 1.5);  // [rad/(s*s)]
  Vector  MaxAngleBrakingAccelleration  = new Vector(   0, 0, 2.0); //1);  // [rad/(s*s)]

  // Router parameters

}

// ================================================
// Device classes
// ================================================

class CSU122_SPHullDriverDevice
  extends CHullDriverDevice
{
  String m_NormalSetId  = "Body_NormalSet";
  String m_CrashedSetId = "Body_CrashedSet";

  void HullDriverDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 90);
    }
  }

  void HullDriverDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 0);
    }
  }
}

class CSU122_SPHullGunlayerDevice
  extends CHullGunlayerDevice
{
  String m_NormalSetId  = "Body_NormalSet";
  String m_CrashedSetId = "Body_CrashedSet";

  void HullGunlayerDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 30);
      Behavior.SetFireAbility(false, 30);
    }
  }

  void HullGunlayerDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false,100);
      Behavior.SetFireAbility(false, 0);
    }
    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      if (1 == randnum(2))
        StateControl.SetDelayItemHP(_HostObject.GetItem("TrackLeft").Index, 0.0, 0);

      if (1 == randnum(2))
        StateControl.SetDelayItemHP(_HostObject.GetItem("TrackRight").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("HullDriver").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("HullEngine").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("Turret_A").Index, 0.0, 0);

      StateControl.SetHitPoints(0.0);
    }
   }
}

class CSU122_SPHullEngineDevice
  extends CHullEngineDevice
{
 // String m_NormalSetId  = "";//"Body_NormalSet";
 // String m_CrashedSetId = "";//"Body_CrashedSet";

  void HullEngineDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Vector  MaxSpeed  = new Vector( 1.5, 0, 0);   // m/s
      Behavior.SetFireAbility(false, 20);
    }
  }

  void HullEngineDeviceDestroyed(Component _HostObject)
  {

    Component IdleSound = _HostObject.GetObject("IdleSound");
    if (IdleSound != null)
    {
      IdleSound.StopSoundPlaying(true);
    }

    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      // Change Item hit points after delay in N seconds. SetDelayItemHP(ItemIndex, HitPoints, Time)
      StateControl.SetDelayItemHP(_HostObject.GetItem("HullGunlayer").Index, 0.0, 20+randnum(15));
      StateControl.SetHitPoints(0.0);
    }
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
      Behavior.SetMoveAbility(false, 0);
      

  }
}

class CSU122_SPTrackLeftDevice
  extends CTrackLeftDevice
{
 // String m_NormalSetId  = "TrackLeft_NormalSet";
  // String m_CrashedSetId = "TrackLeft_CrashedSet";

  void TrackLeftDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(0.5f);
      Behavior.SetMoveAbility(false, 60);
    }
  }

  void TrackLeftDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(1.5f);
      Behavior.SetMoveAbility(false, 0);
//    Behavior.ActivateMovement(false);
    }
  }
}

class CSU122_SPTrackRightDevice
  extends CTrackRightDevice
{
 // String m_NormalSetId  = "TrackRight_NormalSet";
 // String m_CrashedSetId = "TrackRight_CrashedSet";

  void TrackRightDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(-0.5f);
      Behavior.SetMoveAbility(false, 60);
    }
  }

  void TrackRightDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(-1.5f);
      Behavior.SetMoveAbility(false, 0);
//      Behavior.ActivateMovement(false);
    }
  }
}

class CSU122_SPTurretDevice
  extends CTurretDevice
{
  String m_NormalSetId  = "Body_NormalSet";
  String m_CrashedSetId = "Body_CrashedSet";

  void TurretDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      //Behavior.SetMoveAbility(false, 10);
      Behavior.SetAimAbility(false, 20);
    }
  }

  void TurretDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetFireAbility(false, 0);
      Behavior.SetAimAbility(false, 0);
      Behavior.SetMoveAbility(false, 0);// 

    }
      Component IdleSound = _HostObject.GetObject("IdleSound");   //
    if (IdleSound != null)
    {
      IdleSound.StopSoundPlaying(true);
    }   

    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      StateControl.SetHitPoints(0.0);
    }
  }
}

class CSU122_SPRecoilController
{
  String FToBAnim   = "body_recoil_fb";
  String BToFAnim   = "body_recoil_bf";
  String RToLAnim   = "body_recoil_rl";
  String LToRAnim   = "body_recoil_lr";
  float  RecoilTime = 0.5;
};

class CSU122_SPSubstance
  extends CMetalSubstance
{
  Vector MainFrictionAxis = new Vector(1.0, 0.0, 0.0);
  float  Friction         = 1.2;
  float  Friction1        = 0.5;
  float  Elasticity       = 0.0;
}

class CSU122_SPManualControl
  extends CConstraintProperties
{
  // =========================================
  // Tank properties
  // =========================================

  float  Mass                 = 38000.0;
  Vector IT                   = new Vector(0.874482, 3.152529, 3.804275);
  float  Elasticity           = 0.0;  // Must be zero else tank will bouncing like ball
  float  Friction             = 0.1;

  float  SuspensionHeight = 0.4;    // cm
  float  SuspensionPower  = 30000;  // kg
  Vector GravityAccelerate    = CWorldPhysics::GravityVector;

    // angular damping coefficients by axises X, Y and Z
  Vector AngularDampingCoeff  = new Vector(0.5, 0.5, 1.0);
  // linear damping coefficients by axises X, Y and Z
  Vector LinearDampingCoeff   = new Vector(2.5, 4.7, 7.6);  /* */

}

// ================================================
// Unit class
// ================================================

class CSU122_SPUnit
    extends CTankUnit, CWeaponConfig, CPushVehicleObject
{
  final static float  DefaultHitPoints = CHitPoints::SAUSU_85UnitHitPoints;
  
  static category UnitType = CLASSIFICATOR_T34_HEAVY_TANK;

  static Array PostExplosionID = [
                                    ["", "SAUSU85Explosion"]
                                 ];

  static Array Hatches = [
                            [ "Luk_Driver",   "luk_DG_open",   1.0 ],      //    "luk_body_open"
                            [ "Luk_ComHatch", "luk_BC_open",   1.0 ], //
                            [ "Commander",    "luk_commander", 1.0 ]        //
                         ];

  static Array HatchesStates = [
                                  [ "Normal", [[ "Luk_ComHatch", 1.0 ], [ "Commander", 1.0 ], [ "Luk_Driver", 1.0 ] ] ],         // [ "Commander", 1.0 ],  , [ "Driver", 1.0 ]
                                  [ "Attack", [[ "Luk_ComHatch", 0.0 ], [ "Commander", 0.0 ], [ "Luk_Driver", 0.0 ]  ] ]       // , [ "Driver", 0.0 ]   , [ "Commander", 0.0 ]
                               ];

  final static String BodyJoint   = "Body";

  final static String DefaultHealthParameter = "HP_HEALTHY";  // fragile constitution
  final static int    UnitMenacePower        = MENACE_NORMAL;  // light weapon
  final static Array  AutomaticClassificators  = ["GROUND", "HEAVYTANK", "SAU", "RU"];
  static Array        LandingJoints            = ["Corner_FL", "Corner_RL", "Corner_RR", "Corner_FR"];

  static Array  SubstanceArmourWidth = [
                                         [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::SAUSU85UnitArmourTurretFWD  ],
                                         [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::SAUSU85UnitArmourTurretREAR ],
                                         [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::SAUSU85UnitArmourTurretTOP  ],
                                         [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::SAUSU85UnitArmourTurretLEFT ],
                                         [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::SAUSU85UnitArmourTurretRIGHT],
                                         [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::SAUSU85UnitArmourHullFWD    ],
                                         [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::SAUSU85UnitArmourHullREAR   ],
                                         [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::SAUSU85UnitArmourHullTOP    ],
                                         [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::SAUSU85UnitArmourHullBOTTOM ],
                                         [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::SAUSU85UnitArmourHullRIGHT  ],
                                         [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::SAUSU85UnitArmourHullLEFT   ]
                                      ];

   Array m_DamageTransfer = [ // From Item , To Item, Item HitPoints Percent
                             ["HullDriver", "HullEngine", 0.8f],
                             ["HullDriver", "HullGunlayer", 1.8f]
                             ];


  boolean m_AITankCollisionShape = true;


  void CSU122_SPUnit()
  {
    SetupMesh(new #AnimatedObject<Cu_veh_SU122_42Model>(), [0]);     //[400, 270, 50, 5]

    // Setup trucks
    SetupTracks(
        new #TrackAnimator<CSU122_SPLeftTrack>(),
        new #TrackAnimator<CSU122_SPRightTrack>()
      );

    // Setup Weapon
    SetupWeapon("Weapon_A", new #Weapon<CSU122_SPGun>(),
      ["Fire_A1"], new #TargetingAnimator<CSU122_SPGunTargetingAnimatorA>());


    // Creates and register unit state component
    // MoveSound, TraceEffectId
    SetMovementEffects(
        new #Emitter<CT34MovementSound>(),
        [
          ["Vapor_L", "GroundUnitTraceEffect"],
          ["Vapor_R", "GroundUnitTraceEffect"],
          ["Smoke_R", "DiselSmokeEffect"],
          ["Smoke_L", "DiselSmokeEffect"]
        ]
      );

    SetIdleEffects(
        new #Emitter<CT34IdleSound>()
      );

    SetAccelEffects(
        new #Emitter<CT34AccelSound>(),
        [
          ["Smoke_R", "DiselAccelSmokeEffect", new Vector (0.0, 0.0, 0.0)],
          ["Smoke_L", "DiselAccelSmokeEffect", new Vector (0.0, 0.0, 0.0)]
        ]
      );

    SetupBehavior( new #VehicleBehavior<CSU122_SPBehavior>());

    Component hatches = new #HatchesStateController();
    hatches.AddHatches( Hatches );
    hatches.AddStates( HatchesStates );
    SetupHatches( hatches );
    hatches.SetHatchesState( "Normal" );
  }

  void Construct(
      Component _Mission,
      Component _PropMap
    )
  {

    CUnit::Construct(_Mission, _PropMap);

    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET762792, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET127, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET85,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET88,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_HEBULLET85,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_HEBULLET88,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BUILDING, 0.0);

    // create effects for tracks: [ HostId, Effectid, ZoneId ]
    SetTrackEffects(
        _Mission,
        [
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest02 , "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest02 , "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest03   , "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest03   , "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Right" ],
          ["Vapor_L", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Vapor_R", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Vapor_L", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Vapor_R", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Vapor_L", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Vapor_R", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ]
        ]
      );



    CreateUnitItem(
        "HullDriver",
        CJointPoints::TankPzIVAusfGUnitHULL_DRIVERPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "HullDriver"
      );
    CreateUnitItem(
        "HullGunlayer",
        CJointPoints::TankPzIVAusfGUnitHULL_GUNLAYERPoints,
        ["GenericDamageItemEffect", "HullGunLayerExplosionEffect"],
        "HullGunlayer"
      );
    CreateUnitItem(
        "HullEngine",
        CJointPoints::TankPzIVAusfGUnitHULL_ENGINEPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "HullEngine"
      );
    CreateUnitItem(
        "TrackLeft",
        CJointPoints::TankPzIVAusfGUnitTRACK_LEFTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackLeft"
      );
    CreateUnitItem(
        "TrackRight",
        CJointPoints::TankPzIVAusfGUnitTRACK_RIGHTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackRight"
      );
    CreateUnitItem(
        "Turret_A",
        CJointPoints::TankPzIVAusfGUnitTURRETPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "Turret_A"
      );
/*    CreateUnitItem(
        "Turret_A_crashed",
        0,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "Turret_A_crashed"
      );*/

    logWarning( "Weapon fire deviation for " + getIdentificator( this ) + "=" + new String( GetObject( "Weapon_A" ).FireDeviation ) );

    LinkDeviceToUnitItem("HullDriver",   new CSU122_SPHullDriverDevice());
    LinkDeviceToUnitItem("HullGunlayer", new CSU122_SPHullGunlayerDevice());
    LinkDeviceToUnitItem("HullEngine",   new CSU122_SPHullEngineDevice());
    LinkDeviceToUnitItem("TrackLeft",    new CSU122_SPTrackLeftDevice());
    LinkDeviceToUnitItem("TrackRight",   new CSU122_SPTrackRightDevice());
    LinkDeviceToUnitItem("Turret_A",     new CSU122_SPTurretDevice());

    AttachEffect2("Vapor_L", "T34TrackEffect", new Vector(0.6, 0.0, 0.0));
    AttachEffect2("Vapor_R", "T34TrackEffect", new Vector(0.6, 0.0, 0.0));
    AttachEffect2("Vapor_L", "T34TrackEffect", new Vector(-0.6, 0.0, 0.0));
    AttachEffect2("Vapor_R", "T34TrackEffect", new Vector(-0.6, 0.0, 0.0));

    SetupRecoilController(new #RecoilController<CSU122_SPRecoilController>());

    Component VehicleController = new #AITankVehicle<CSU122_SPManualControl>();
    if (null == VehicleController)
      logError("Cant setup type of vehicle control for " + getIdentificator(this));

    RegisterObject("AIVehicleController", VehicleController);
    VehicleController.SetEventHandler(this);

    Component Mesh = GetMeshComponent();
    Array BaseShapes = Mesh.GetCollisionShapes(Mesh.GetRootJoint(), false);
    Component Body = VehicleController.CreateObject(Mesh, BaseShapes);

    SetupPhysicaleObject("CSU122_SPSubstance", 60000.0, 0.0);
//    Component VehicleController = GetPhysicsController();


      EnableSurfaceControl(true);
      GetLeftTrack().EnableAutoCalcPath(true);
      GetRightTrack().EnableAutoCalcPath(true);
  }

  // ======================================
  // Armour descriptor
  // ======================================
  Array GetArmourDescriptor()
  {
    return new Array ([
                        [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::SAUSU85UnitArmourTurretFWD  ],
                        [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::SAUSU85UnitArmourTurretREAR ],
                        [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::SAUSU85UnitArmourTurretTOP  ],
                        [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::SAUSU85UnitArmourTurretLEFT ],
                        [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::SAUSU85UnitArmourTurretRIGHT],
                        [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::SAUSU85UnitArmourHullFWD    ],
                        [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::SAUSU85UnitArmourHullREAR   ],
                        [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::SAUSU85UnitArmourHullTOP    ],
                        [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::SAUSU85UnitArmourHullBOTTOM ],
                        [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::SAUSU85UnitArmourHullRIGHT  ],
                        [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::SAUSU85UnitArmourHullLEFT   ]
                      ]);
  }

  event void SetModelViewState(
      boolean _State    
    )
  {
    // TMP
  }

  // ======================================
  // Point collision detector
  // ======================================

  // Call when tank deep in the water (Вызывается, когда танк глубоко заехал в воду)
  event void OnPointCollisionDetect(String _ObjectID)
  {
    // Destroy HullEngine may be changed (убиваем движок, можно заменить на что-то другое)
    SetUnitItemHPPercent("HullEngine", 0.0);
    
    GetObject("PointDetector").EnableDetector(false);
  }
  
  // ======================================
  // Destroy object
  // ======================================

  event void KillUnit()
  {
    Component Behavior = GetObject("Behavior");
    if (Behavior != null)
    {
      //Behavior.ActivateMovement(false);
      //Behavior.ActivateFire(false);
      Behavior.SetAimAbility(false,0);
      Behavior.SetMoveAbility(false,0);
      Behavior.SetFireAbility(false,0);
    }
    Component StateControl = GetObject("StateControl");
    if (StateControl != null)
    {
      StateControl.SetDelayItemHP(GetItem("TrackLeft").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("TrackRight").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullDriver").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullEngine").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullGunlayer").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("Turret_A").Index, 0.0, 0);
      
       //StateControl.SetHitPoints(0.0);
    }
    Component Mission = new #GameController().GetObject(SOID_MissionController);
    if (Mission != null)
    {
       Component Object = Mission.GetObject(getIdentificator(this));
       if(Object != null)
       {
         Object.OnLifeStateChanged(false);
       }
    }
  }
}

// ================================================
// WINTER_Unit class
// ================================================

class CSU122_SP_WUnit
    extends CTankUnit, CWeaponConfig, CPushVehicleObject
{
  final static float  DefaultHitPoints = CHitPoints::SAUSU_85UnitHitPoints;
  
  static category UnitType = CLASSIFICATOR_T34_HEAVY_TANK;

  static Array PostExplosionID = [
                                    ["", "SAUSU85Explosion"]
                                 ];

  static Array Hatches = [
                            [ "Luk_Driver",   "luk_DG_open",   1.0 ],      //    "luk_body_open"
                            [ "Luk_ComHatch", "luk_BC_open",   1.0 ], //
                            [ "Commander",    "luk_commander", 1.0 ]        //
                         ];

  static Array HatchesStates = [
                                  [ "Normal", [[ "Luk_ComHatch", 1.0 ], [ "Commander", 1.0 ], [ "Luk_Driver", 1.0 ] ] ],         // [ "Commander", 1.0 ],  , [ "Driver", 1.0 ]
                                  [ "Attack", [[ "Luk_ComHatch", 0.0 ], [ "Commander", 0.0 ], [ "Luk_Driver", 0.0 ]  ] ]       // , [ "Driver", 0.0 ]   , [ "Commander", 0.0 ]
                               ];

  final static String BodyJoint   = "Body";

  final static String DefaultHealthParameter = "HP_HEALTHY";  // fragile constitution
  final static int    UnitMenacePower        = MENACE_NORMAL;  // light weapon
  final static Array  AutomaticClassificators  = ["GROUND", "HEAVYTANK", "SAU", "RU"];
  static Array        LandingJoints            = ["Corner_FL", "Corner_RL", "Corner_RR", "Corner_FR"];

  static Array  SubstanceArmourWidth = [
                                         [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::SAUSU85UnitArmourTurretFWD  ],
                                         [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::SAUSU85UnitArmourTurretREAR ],
                                         [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::SAUSU85UnitArmourTurretTOP  ],
                                         [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::SAUSU85UnitArmourTurretLEFT ],
                                         [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::SAUSU85UnitArmourTurretRIGHT],
                                         [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::SAUSU85UnitArmourHullFWD    ],
                                         [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::SAUSU85UnitArmourHullREAR   ],
                                         [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::SAUSU85UnitArmourHullTOP    ],
                                         [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::SAUSU85UnitArmourHullBOTTOM ],
                                         [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::SAUSU85UnitArmourHullRIGHT  ],
                                         [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::SAUSU85UnitArmourHullLEFT   ]
                                      ];

   Array m_DamageTransfer = [ // From Item , To Item, Item HitPoints Percent
                             ["HullDriver", "HullEngine", 0.8f],
                             ["HullDriver", "HullGunlayer", 1.8f]
                             ];


  boolean m_AITankCollisionShape = true;


  void CSU122_SP_WUnit()
  {
    SetupMesh(new #AnimatedObject<Cu_veh_SU122_42_WModel>(), [0]);     //[400, 270, 50, 5]

    // Setup trucks
    SetupTracks(
        new #TrackAnimator<CSU122_SPLeftTrack>(),
        new #TrackAnimator<CSU122_SPRightTrack>()
      );

    // Setup Weapon
    SetupWeapon("Weapon_A", new #Weapon<CSU122_SPGun>(),
      ["Fire_A1"], new #TargetingAnimator<CSU122_SPGunTargetingAnimatorA>());


    // Creates and register unit state component
    // MoveSound, TraceEffectId
    SetMovementEffects(
        new #Emitter<CT34MovementSound>(),
        [
          ["Vapor_L", "GroundUnitTraceEffect"],
          ["Vapor_R", "GroundUnitTraceEffect"],
          ["Smoke_R", "DiselSmokeEffect"],
          ["Smoke_L", "DiselSmokeEffect"]
        ]
      );

    SetIdleEffects(
        new #Emitter<CT34IdleSound>()
      );

    SetAccelEffects(
        new #Emitter<CT34AccelSound>(),
        [
          ["Smoke_R", "DiselAccelSmokeEffect", new Vector (0.0, 0.0, 0.0)],
          ["Smoke_L", "DiselAccelSmokeEffect", new Vector (0.0, 0.0, 0.0)]
        ]
      );

    SetupBehavior( new #VehicleBehavior<CSU122_SPBehavior>());

    Component hatches = new #HatchesStateController();
    hatches.AddHatches( Hatches );
    hatches.AddStates( HatchesStates );
    SetupHatches( hatches );
    hatches.SetHatchesState( "Normal" );
  }

  void Construct(
      Component _Mission,
      Component _PropMap
    )
  {

    CUnit::Construct(_Mission, _PropMap);

    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET762792, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET127, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET85,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET88,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_HEBULLET85,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_HEBULLET88,    2.0);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BUILDING, 0.0);

    // create effects for tracks: [ HostId, Effectid, ZoneId ]
    SetTrackEffects(
        _Mission,
        [
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest02 , "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest02 , "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest03   , "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest03   , "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Right" ],
          ["Vapor_L", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Left" ],
          ["Vapor_R", "ForestUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Right" ],
          ["Vapor_L", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Vapor_R", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Vapor_L", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Vapor_R", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Vapor_L", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Vapor_R", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ]
        ]
      );



    CreateUnitItem(
        "HullDriver",
        CJointPoints::TankPzIVAusfGUnitHULL_DRIVERPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "HullDriver"
      );
    CreateUnitItem(
        "HullGunlayer",
        CJointPoints::TankPzIVAusfGUnitHULL_GUNLAYERPoints,
        ["GenericDamageItemEffect", "HullGunLayerExplosionEffect"],
        "HullGunlayer"
      );
    CreateUnitItem(
        "HullEngine",
        CJointPoints::TankPzIVAusfGUnitHULL_ENGINEPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "HullEngine"
      );
    CreateUnitItem(
        "TrackLeft",
        CJointPoints::TankPzIVAusfGUnitTRACK_LEFTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackLeft"
      );
    CreateUnitItem(
        "TrackRight",
        CJointPoints::TankPzIVAusfGUnitTRACK_RIGHTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackRight"
      );
    CreateUnitItem(
        "Turret_A",
        CJointPoints::TankPzIVAusfGUnitTURRETPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "Turret_A"
      );
/*    CreateUnitItem(
        "Turret_A_crashed",
        0,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "Turret_A_crashed"
      );*/

    logWarning( "Weapon fire deviation for " + getIdentificator( this ) + "=" + new String( GetObject( "Weapon_A" ).FireDeviation ) );

    LinkDeviceToUnitItem("HullDriver",   new CSU122_SPHullDriverDevice());
    LinkDeviceToUnitItem("HullGunlayer", new CSU122_SPHullGunlayerDevice());
    LinkDeviceToUnitItem("HullEngine",   new CSU122_SPHullEngineDevice());
    LinkDeviceToUnitItem("TrackLeft",    new CSU122_SPTrackLeftDevice());
    LinkDeviceToUnitItem("TrackRight",   new CSU122_SPTrackRightDevice());
    LinkDeviceToUnitItem("Turret_A",     new CSU122_SPTurretDevice());

    AttachEffect2("Vapor_L", "T34TrackEffect", new Vector(0.6, 0.0, 0.0));
    AttachEffect2("Vapor_R", "T34TrackEffect", new Vector(0.6, 0.0, 0.0));
    AttachEffect2("Vapor_L", "T34TrackEffect", new Vector(-0.6, 0.0, 0.0));
    AttachEffect2("Vapor_R", "T34TrackEffect", new Vector(-0.6, 0.0, 0.0));

    SetupRecoilController(new #RecoilController<CSU122_SPRecoilController>());

    Component VehicleController = new #AITankVehicle<CSU122_SPManualControl>();
    if (null == VehicleController)
      logError("Cant setup type of vehicle control for " + getIdentificator(this));

    RegisterObject("AIVehicleController", VehicleController);
    VehicleController.SetEventHandler(this);

    Component Mesh = GetMeshComponent();
    Array BaseShapes = Mesh.GetCollisionShapes(Mesh.GetRootJoint(), false);
    Component Body = VehicleController.CreateObject(Mesh, BaseShapes);

    SetupPhysicaleObject("CSU122_SPSubstance", 60000.0, 0.0);
//    Component VehicleController = GetPhysicsController();


      EnableSurfaceControl(true);
      GetLeftTrack().EnableAutoCalcPath(true);
      GetRightTrack().EnableAutoCalcPath(true);
  }

  // ======================================
  // Armour descriptor
  // ======================================
  Array GetArmourDescriptor()
  {
    return new Array ([
                        [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::SAUSU85UnitArmourTurretFWD  ],
                        [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::SAUSU85UnitArmourTurretREAR ],
                        [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::SAUSU85UnitArmourTurretTOP  ],
                        [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::SAUSU85UnitArmourTurretLEFT ],
                        [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::SAUSU85UnitArmourTurretRIGHT],
                        [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::SAUSU85UnitArmourHullFWD    ],
                        [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::SAUSU85UnitArmourHullREAR   ],
                        [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::SAUSU85UnitArmourHullTOP    ],
                        [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::SAUSU85UnitArmourHullBOTTOM ],
                        [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::SAUSU85UnitArmourHullRIGHT  ],
                        [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::SAUSU85UnitArmourHullLEFT   ]
                      ]);
  }

  event void SetModelViewState(
      boolean _State    
    )
  {
    // TMP
  }

  // ======================================
  // Point collision detector
  // ======================================

  // Call when tank deep in the water (Вызывается, когда танк глубоко заехал в воду)
  event void OnPointCollisionDetect(String _ObjectID)
  {
    // Destroy HullEngine may be changed (убиваем движок, можно заменить на что-то другое)
    SetUnitItemHPPercent("HullEngine", 0.0);
    
    GetObject("PointDetector").EnableDetector(false);
  }
  
  // ======================================
  // Destroy object
  // ======================================

  event void KillUnit()
  {
    Component Behavior = GetObject("Behavior");
    if (Behavior != null)
    {
      //Behavior.ActivateMovement(false);
      //Behavior.ActivateFire(false);
      Behavior.SetAimAbility(false,0);
      Behavior.SetMoveAbility(false,0);
      Behavior.SetFireAbility(false,0);
    }
    Component StateControl = GetObject("StateControl");
    if (StateControl != null)
    {
      StateControl.SetDelayItemHP(GetItem("TrackLeft").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("TrackRight").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullDriver").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullEngine").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullGunlayer").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("Turret_A").Index, 0.0, 0);
      
       //StateControl.SetHitPoints(0.0);
    }
    Component Mission = new #GameController().GetObject(SOID_MissionController);
    if (Mission != null)
    {
       Component Object = Mission.GetObject(getIdentificator(this));
       if(Object != null)
       {
         Object.OnLifeStateChanged(false);
       }
    }
  }
}



