//-------------------------------------------------------------------//
//  This code is copyright 2001 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//
//-------------------------------------------------------------------

// Unit Explosion
class CTankPzVI_AI_Explosion
  extends CHeavyTankExplosion
{
  float  Damage   = 5.0;
  float  Radius   = 1.0;
}

// Machine gun
class CTankPzVI_AI_MachineGunBulletExplosion
  extends CMachineGun762792BulletExplosion
{
  float  Damage   = CPiercing::TankPzVI_AI_MachineGunDamage;
}

class CTankPzVI_AI_MachineGunBulletControl
  extends CMachineGunBulletControl
{
  String ExplosionId  = "TankPzVI_AI_MachineGunBulletExplosion";
  Vector GravityAccel = CPiercing::BulletGravityVector;
}

class CTankPzVI_AI_CoaxialMachineGun
    extends CMachineGun, CPlayerWeapon
{
  final static int CoAxialMaster = 0;    //

  final static float MinDistance      = 1;
  final static float MaxDistance      = 400;

  final static String BulletPatternId = "TankPzVI_AI_MachineGunBullet";
  final static float  FireDeviation   = 0.15;

  final static Vector  GravityVector   = CPiercing::BulletGravityVector;
  final static boolean HighTrajectory = false;

  final static float DirectionSpeedH  = 14.0; // deg / sec horizontal
  final static float DirectionSpeedV  = 5.0; // deg / sec vertical

  Component BurstFireSound  = new #Emitter<CMG34MachineGunFireSound>();

  final static float  LockAngleHMin     = -5.0;
  final static float  LockAngleHMax     =  5.0;
  final static float  LockAngleVMin     = -5.0;
  final static float  LockAngleVMax     =  5.0;
  final static float  BlockedLockAngle  =  1.0;

  // *** Gun parameters for behavior
  final static int  FirePeriod        = 100; // ms
  final static int  FirePeriodRandAdd = 0; // ms
  
    final static int Slot = 1;

  final static boolean BurstFire      = true;
  final static int  BurstTime         = 2800; // ms
  final static int  BurstTimeRandAdd  = 1000; // ms

  final static int  BurstDelay        = 0; // ms
  final static int  BurstDelayRandAdd = 0; // ms
  // gun specific fire mask with priorities
  final static Array GunSpecificFireMask = [
                                [["GROUND"],[]], // low priority mask: RestrictTo, Exclude
                                [[],[]], //
                                [[],[]]   //
                              ];
}

class CTankPzVI_AI_MachineGun
    extends CMachineGun
{
  final static String BulletPatternId = "TankPzVI_AI_MachineGunBullet";
  final static float MinDistance      = 1;
  final static float MaxDistance      = 400;
  final static Vector  GravityVector   = CPiercing::BulletGravityVector;
  final static boolean HighTrajectory  = false;

  final static float    LockAngleHMin     = -20.0;
  final static float    LockAngleHMax     =  20.0;
  final static float    LockAngleVMin     = -10.0;
  final static float    LockAngleVMax     =  15.0;
  final static float    BlockedLockAngle  =  1.0;

  Component BurstFireSound  = new #Emitter<CMG34MachineGunFireSound>();

  // *** Gun parameters for behavior

  final static int  FirePeriod        = 100; // ms
  final static int  FirePeriodRandAdd = 0; // ms

  final static int Slot = 2;

  final static boolean BurstFire      = true;
  final static int  BurstTime         = 2800; // ms
  final static int  BurstTimeRandAdd  = 1000; // ms

  final static int  BurstDelay        = 0; // ms
  final static int  BurstDelayRandAdd = 0; // ms

  // gun specific fire mask with priorities
  final static Array GunSpecificFireMask = [
                                [["GROUND"],[]], // low priority mask: RestrictTo, Exclude
                                [[],[]], //
                                [[],[]]   //
                              ];
}

// Main cannon section
// Main cannon animator
class CTankPzVI_AI_GunTargetingAnimatorA
  extends CTargetingAnimator
{
  String HorAnimName    = "turret_a";
  String VerAnimName    = "gun_a";

  float  LeftEndAngle   =  180.0;
  float  RightEndAngle  = -180.0;
  float  TopEndAngle    =  -6.5;
  float  BottomEndAngle =  17.0;
}
// Main cannon bullet explosion
class CTankPzVI_AI_GunCalibreBulletExplosion
  extends CCalibreGun88BulletExplosion
{
  float  Damage   = CPiercing::TankPzVI_AI_CalibreDamage;
  float  FireDamage   = CPiercing::TankPzVI_AI_CalibreFireDamage;
  float     Radius     = CPiercing::TankPzVI_AI_CalibreRadius;
  //Component Debris     = new CTankPzVI_AI_GunCalibreBulletDebrisCloud();
}

class CTankPzVI_AI_GunCalibreBulletDebrisCloud
{
  int    DebrisQuantity  = CPiercing::TankPzVI_AI_CalibreDebrisQuantity;
  String DebrisPatternID = "TankPzVI_AI_GunCalibreBulletDebris";
  float  DebrisSpeed     = 300.0;
  float  DebrisSpeedDev  = 50.0;
  Vector DebrisDir       = new Vector(0.0, 0.0, 1.0);
  float  DebrisMinAngle  = 0.0;
  float  DebrisMaxAngle  = 90.0;
}

class CTankPzVI_AI_GunCalibreBulletDebrisControl
{
  Array     Classificator = [];
  boolean   IsMotionBlur  = true;
  float     MaxDistance   = CPiercing::TankPzVI_AI_CalibreDebrisMaxDistance;
  String    ExplosionId   = "TankPzVI_AI_GunCalibreBulletDebrisExplosion";
  float     Mass          = 0.02;
}

class CTankPzVI_AI_GunCalibreBulletDebrisExplosion
  extends CDebrisExplosion
{
  String EffectId = "";
  String SoundId  = "";
  float  Damage   = CPiercing::TankPzVI_AI_CalibreDebrisDamage;
}

class CTankPzVI_AI_GunSubcalibreBulletExplosion
  extends CSubcalibreGun88BulletExplosion
{
  float  Damage   = CPiercing::TankPzVI_AI_SubcalibreDamage;
  float  FireDamage   = CPiercing::TankPzVI_AI_SubcalibreFireDamage;
}

class CTankPzVI_AI_GunHEBulletExplosion
  extends CHEGun88BulletExplosion
{
  float  Damage   = CPiercing::TankPzVI_AI_HEDamage;
  float  FireDamage   = CPiercing::TankPzVI_AI_HEFireDamage;
  float     Radius = CPiercing::TankPzVI_AI_HERadius;
  //Component Debris = new CTankPzVI_AI_GunHEBulletDebrisCloud();
}

class CTankPzVI_AI_GunHEBulletDebrisCloud
{
  int    DebrisQuantity  = CPiercing::TankPzVI_AI_HEDebrisQuantity;
  String DebrisPatternID = "TankPzVI_AI_GunHEBulletDebris";
  float  DebrisSpeed     = 300.0;
  float  DebrisSpeedDev  = 50.0;
  Vector DebrisDir       = new Vector(0.0, 0.0, 1.0);
  float  DebrisMinAngle  = 0.0;
  float  DebrisMaxAngle  = 90.0;
}
class CTankPzVI_AI_GunHEBulletDebrisControl
{
  Array     Classificator = [];
  boolean   IsMotionBlur  = true;
  float     MaxDistance   = CPiercing::TankPzVI_AI_HEDebrisMaxDistance;
  String    ExplosionId   = "TankPzVI_AI_GunHEBulletDebrisExplosion";
  float     Mass          = 0.02;
}

class CTankPzVI_AI_GunHEBulletDebrisExplosion
  extends CDebrisExplosion
{
  String EffectId = "";
  String SoundId  = "";
  float  Damage   = CPiercing::TankPzVI_AI_HEDebrisDamage;
}
class CTankPzVI_AI_GunCalibreBulletControl
  extends CCalibreBulletControl
{
  String    ExplosionId  = "TankPzVI_AI_GunCalibreBulletExplosion";
  float     BulletSpeed  = CPiercing::TankPzVI_AI_CalibreBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::TankPzVI_AI_CalibreMaxDistance;
  float     PenetrationPower      = CPiercing::TankPzVI_AI_CalibrePenetrationPower;
  Array     PenetrationByDistance = CPiercing::TankPzVI_AI_CalibrePenetrationByDistance;
  float     PenetrationModifierMin   = CPiercing::TankPzVI_AI_CalibrePenetrationModifier[0];
  float     PenetrationModifierMax   = CPiercing::TankPzVI_AI_CalibrePenetrationModifier[1];
/*  float     DamageModifierMin        = CPiercing::TankPzVI_AI_CalibreDamageModifier[0];
  float     DamageModifierMax        = CPiercing::TankPzVI_AI_CalibreDamageModifier[1];  */
}

class CTankPzVI_AI_GunSubCalibreBulletControl
  extends CSubcalibreBulletControl
{
  String    ExplosionId  = "TankPzVI_AI_GunSubcalibreBulletExplosion";
  float     BulletSpeed  = CPiercing::TankPzVI_AI_SubcalibreBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::TankPzVI_AI_SubcalibreMaxDistance;
  float     PenetrationPower      = CPiercing::TankPzVI_AI_SubcalibrePenetrationPower;
  Array     PenetrationByDistance = CPiercing::TankPzVI_AI_SubcalibrePenetrationByDistance;
 float     PenetrationModifierMin   = CPiercing::TankPzVI_AI_SubcalibrePenetrationModifier[0];
  float     PenetrationModifierMax   = CPiercing::TankPzVI_AI_SubcalibrePenetrationModifier[1];
/*   float     DamageModifierMin        = CPiercing::TankPzVI_AI_SubcalibreDamageModifier[0];
  float     DamageModifierMax        = CPiercing::TankPzVI_AI_SubcalibreDamageModifier[1];     */
}

class CTankPzVI_AI_GunHEBulletControl
  extends CHEBulletControl
{
  String    ExplosionId  = "TankPzVI_AI_GunHEBulletExplosion";
  float     BulletSpeed  = CPiercing::TankPzVI_AI_HEBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::TankPzVI_AI_HEMaxDistance;
  float     PenetrationPower      = CPiercing::TankPzVI_AI_HEPenetrationPower;
  Array     PenetrationByDistance = CPiercing::TankPzVI_AI_HEPenetrationByDistance;
}

class CTankPzVI_AI_CalibreAmmo
{
  final static String BulletPatternId = "TankPzVI_AI_GunCalibreBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],["HUMAN", "AIR"]];
  final static float  LoadingTime     = 0.0f;

}

class CTankPzVI_AI_SubCalibreAmmo
{
  final static String BulletPatternId = "TankPzVI_AI_GunSubCalibreBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],["HUMAN", "VEHICLE", "BLD_WAR", "BLD_CIV", "AIR"]];
  final static float  LoadingTime     = 0.0f;
}

class CTankPzVI_AI_HEAmmo
{
  final static String BulletPatternId = "TankPzVI_AI_GunHEBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],["HEAVYTANK", "TANK", "AIR"]];
  final static float  LoadingTime     = 0.0f;

}

class CTankPzVI_AI_MachineGunAmmo
{
  final static String BulletPatternId = "TankPzVI_AI_MachineGunBullet";
  final static int    Ammunition      = 1900;
  final static Array  TargetMask      = [[],["AIR"]];
  final static float  LoadingTime     = 0.0f;
}
class CTankPzVI_AI_AmmoContainer
{
  final static String Name = CWeaponNames::str_PzVIAusfEAmmoContainerName;
  final static Array  Ammo = [
                               [0, new CTankPzVI_AI_MachineGunAmmo()]
                             ];

}

// Main cannon properties
class CTankPzVI_AI_Gun
    extends CHeavyGun, CWeaponFireRecoil
{
  float InitBulletSpeed = 0.0f;
  final static float   FireDeviation   = 0.1;
  final static Vector  GravityVector   = CPiercing::ShellGravityVector;
  final static boolean HighTrajectory  = false;

  final static String BulletPatternId = "";
  final static String FireSoundId     = "Pz6MainGunFireSound";
  final static String FireEffectId    = "HeavyGunFireMuzzleEffect";
  final static String AmmoLoadSoundId = "TankPzVIAusfE_GunLoadSound";
//  final static String AmmoLoadVoiceId = "";
//  final static String AmmoLoadedVoiceId = "";

  event void OnWeaponFire()
  {
    Component Object = (new #GameController()).GetMission().GetObject(getIdentificator(this));
    if (null != Object)
      (new #EffectsArray()).CreateEffect("HeavyGunNoMuzzleGroundEffect", getPosition(Object), null);

    CWeaponFireRecoil::OnWeaponFire();
  }

  final static Array Ammo = [
                              new CTankPzVI_AI_CalibreAmmo(),
                              new CTankPzVI_AI_SubCalibreAmmo(),
                              new CTankPzVI_AI_HEAmmo()
                            ];
  //$TMP TEST DATA
  final static Array AmmoTargetUse    = [
                                          [0, [["HEAVYTANK"],[]], [[500.0, 25.0, 2000.0, 100.0], [[1000.0, 40.0], [1500.0, 80.0]]]],
                                          [1, [["HEAVYTANK"],[]], [[500.0, 75.0, 2000.0, 0.0  ], [[1000.0, 60.0], [1500.0, 20.0]]]],
                                          //TANK
                                          [0, [["TANK"],     []], [[500.0, 35.0, 2000.0, 100.0], [[1000.0, 45.0], [1500.0, 90.0]]]],
                                          [1, [["TANK"],     []], [[500.0, 65.0, 2000.0, 0.0  ], [[1000.0, 55.0], [1500.0, 10.0]]]],
                                          //VEHICLE
                                          [2, [["VEHICLE"],  []], [[500.0, 50.0, 2000.0, 100.0], [[1000.0, 90.0], [1500.0, 100.0]]]],
                                          //HUMAN
                                          [2, [["HUMAN"],    []], [[500.0, 15.0, 1000.0, 0.0],   [[]]]],  //
                                          //BLD_WAR
                                          [1, [["BLD_WAR"],  []], [[500.0, 90.0, 1000.0, 100.0], []]],
                                          [2, [["BLD_WAR"],  []], [[500.0, 10.0, 1000.0, 0.0  ], []]],
                                          //BLD_CIV
                                          [2, [["BLD_CIV"],  []], [[500.0, 80.0, 1000.0, 100.0], []]]
                                        ];

  final static boolean CanFireInMove  = true;
  final static float  LockAngleHMin   = -180.0;
  final static float  LockAngleHMax   =  180.0;
  final static float  LockAngleVMin   = -6.5;
  final static float  LockAngleVMax   =   17.0;//33.0; Temp
  final static float  BlockedLockAngle  =  4.0;

  final static float DirectionSpeedH  = 6.5; // deg / sec  Х horizontal
  final static float DirectionSpeedV  = 2.5; // deg / sec  Х vertical

  Component DirectionSoundH  = new #Emitter<CTankHeavyTurretDirectionSoundH>();
  Component DirectionSoundV  = new #Emitter<CTankHeavyTurretDirectionSoundV>();

  final static int     Ammunition     = 2000;        // wrong value

  // *** Gun parameters for behavior
  final static boolean ManualLoad     = true;
  final static boolean UseManualFirePeriod    = false;
  final static int     FirePeriod        = 6000; // ms
  final static int     FirePeriodRandAdd = 2000; // ms

  final static boolean BurstFire      = false;
  final static int  BurstTime         = 2000; // ms
  final static int  BurstTimeRandAdd  = 0; // ms

  final static int  BurstDelay        = 3000; // ms
  final static int  BurstDelayRandAdd = 2000; // ms

  final static int     Slot             = 0;
  final static boolean Primary          = true; // GUN should be marked as Primary

  // gun specific fire mask with priorities
  final static Array GunSpecificFireMask = [
                                [["HEAVYTANK"],[]],    // high priority mask: RestrictTo, Exclude
                                [["GROUND"],[]]             //
                              ];
  Component FireAnimator = new #LineAnimator<CTankPzVI_AI_FireAnimation>();    //
}
// Machinegun section
// Machinegun animator
class CTankPzVI_AI_TargetingAnimatorB
  extends CTargetingAnimator
{
  String LeftUpAnimName    = "gun_c_leftup";
  String LeftDownAnimName  = "gun_c_leftdn";
  String RightUpAnimName   = "gun_c_rightup";
  String RightDownAnimName = "gun_c_rightdn";

  float  LeftEndAngle   = -15.0;
  float  RightEndAngle  =  15.0;
  float  TopEndAngle    =  -7.0;
  float  BottomEndAngle =  7.0;
}
// Engine system

class CTankPzVI_AI_EngineSystem
{

  float MaxPower      = 1600.0;  // maximum horse power
  float MinSpeed      = 600.0;   // minimum RPM
  float MaxSpeed      = 2000.0;  // maximum RPM

  Array Gears         = [
                          -0.10,
                           0.00,
                           0.10,
                           0.20,
                           0.30,
                           0.45,
                           0.60
                        ];


  float LoForce       = 800.0;   // force of engine if brake is disable
  float HiForce       = 16000.0;  // force of engine if brake is enable



}
class CTankPzVI_AI_BaseTrack
{
  String  JointName           = "";
  String  TrackTexName        = "Textures/u_veh_PzVI_AI_track.tex";
  String  WheelAnimName       = "";

  Array   TrackTexScrollScale = [0.0, -0.30];//[0.0, -0.4];
  float   WheelRotateScale    = 0.03;
  float   RealTrackPathScale  = 2.0f;
  boolean IsLeftTrack;

  float   WheelRadius         = 0.396 + 0.045; // whell radius + track radius
  float   WhellLiftDown       = 0.115;         // max down wheel offset
  float   WhellLiftUp         = 0.140;         // max up wheel offset

 // float   TrackSoft           = 0.5;    

  // Collision mask [restrict], [exclude]
  Array   CollisionMask = [[CLASSIFICATOR_WALK_SURFACE ],[CLASSIFICATOR_COLLISION_SHAPES]];
}

class CTankPzVI_AI_LeftTrack
  extends CTankPzVI_AI_BaseTrack
{
  String  JointName     = "TrackLeft";
  String  WheelAnimName = "wheels_left";
  boolean IsLeftTrack = true;

  Array   WhellsAnimation =
  [
    // joint name,            animation name,            down    up
    //
    ["WheelLeftMain1", "L_Wheel01_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain2", "L_Wheel02_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain3", "L_Wheel03_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain4", "L_Wheel04_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain5", "L_Wheel05_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain6", "L_Wheel06_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain7", "L_Wheel07_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain8", "L_Wheel08_lift", WhellLiftDown, WhellLiftUp, WheelRadius]
  ];
}

class CTankPzVI_AI_RightTrack
  extends CTankPzVI_AI_BaseTrack
{
  String  JointName     = "TrackRight";
  String  WheelAnimName = "wheels_right";
  boolean IsLeftTrack   = false;

  Array   WhellsAnimation =
  [
    // joint name,            animation name,            down    up
    //
    ["WheelRightMain1", "R_Wheel01_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain2", "R_Wheel02_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain3", "R_Wheel03_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain4", "R_Wheel04_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain5", "R_Wheel05_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain6", "R_Wheel06_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain7", "R_Wheel07_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain8", "R_Wheel08_lift", WhellLiftDown, WhellLiftUp, WheelRadius]
  ];
}

 //Turret out animator
   class CTankPzVI_AI_TurretOutAnimator1
{
  String AnimationName = "turret_out1";
  float  AnimationTime = 0.5;
};

// Fire Animator
class CTankPzVI_AI_FireAnimation
{
  final static String  AnimationName     = "gun_a_recoil";
  final static float   AnimationTime     = 0.8;
}

class CTankPzVI_AI_HatchBodyAnimator
{
  String AnimationName = "luk_body_open";
  float  AnimationTime = 1.1;
}

//luk commander animator
class CTankPzVI_AI_HatchCommanderAnimator
{
  String AnimationName = "luk_main_open";
  float  AnimationTime = 2.0;
}

class CTankPzVI_AI_CommanderOutAnimator
{
  String AnimationName = "luk_main_commander";
  float  AnimationTime = 3.0;
}

class CTankPzVI_AI_AccelerationAnimator
{
  String AnimationName = "acceleration";
  float  AnimationTime = 1.0;
}

// Behavior
class CTankPzVI_AI_BehaviorParams extends CBaseBehaviorParams
{
  float   MaxAttackSpeed    = 4.0;
  float   CollisionAddRadius = 4.0;
}

class CTankPzVI_AI_Behavior extends CBaseTankBehavior
{
  final static Component SpecParams = new CTankPzVI_AI_BehaviorParams();

  Array EnemyRankDangerByDistance =  [
                                       [[ ["HEAVYTANK"],[] ], [ [ 0.0, 200.0, 1500.0, 100.0 ], [ [400.0, 150.0] ] ] ],
                                       [[ ["TANK"],[] ],      [ [ 0.0, 180.0, 1500.0, 100.0 ], [ [400.0, 140.0] ] ] ], // [ Mask, PiercLinFunctionByDist]
                                       [[ ["ANTITANK"],[] ],  [ [ 0.0, 150.0, 1500.0, 95.0 ], [ [400.0, 130.0] ] ] ],  //
                                       [[ ["BTR"],[] ],       [ [ 0.0, 130.0, 1500.0, 30.0 ], [ [400.0, 125.0] ] ] ],
                                       [[ ["BLD_WAR"],[] ],   [ [ 0.0, 100.0, 1500.0, 35.0 ], [ [400.0,  80.0] ] ] ],
                                       [[ ["VEHICLE"],[] ],   [ [ 0.0,  35.0, 1500.0, 5.0 ],  [ [400.0,  10.0] ] ] ],  //
                                       [[ ["HUMAN"],[] ],     [ [ 0.0,  0.0, 1500.0, 2.0 ],  [ [400.0,   1.0] ] ] ]   //
                                     ]; // default Rank = distance if object not fit any mask


  int      AttackStyle        = AttackStyle_SAU;      // AttackStyle_Tank;   AttackStyle_LightTank AttackStyle_LazyTank;
  boolean  CanMove            = true;
  boolean  HasRouter          = true;           // false
  boolean  HasRadar           = true;
  boolean  ForceFrontInAttack = true; //
  float    NonRotatableAngle = 12.0;
//  float SafeFrontConeAngle = 20.0;  
  float  MinRotateRadius = 0; // unit can turn when staying
  float   CollisionRadius = 12.0;
  float   AttackDistanceMin = 10.0;
  float   AttackDistanceMax = 2700.0;

  // *** radar parameters

  float MaxRadarDistance = 3200.0; // m
  float MinRadarDistance = 1.5;    // m
  float MaxRadarAngle    = 180.0;

  int    UpdateRadarPeriod        = 3000; // ms
  int    UpdateRadarPeriodRandAdd = 1000; // ms

  // *** movement physical parameters

  // physical limitations
  float   MaxRotateSpeed                = 1.75f;
  Vector  MaxSpeed                      = new Vector( 6.5, 0, 0);   // m/s
  Vector  MaxNegativeSpeed              = new Vector( 6.0, 0, 0);   // m/s
  Vector  MaxAccelleration              = new Vector( 0.6, 0, 0);    // m/(s*s)
  Vector  MaxNegativeAccelleration      = new Vector( 0.5, 0, 0);  // m/(s*s)
  Vector  MaxBrakingAccelleration       = new Vector( 1.0, 0, 0);   // m/(s*s)
  Vector  MaxAngleSpeed                 = new Vector(   0, 0, 1.0);    // [rad/s]
  Vector  MaxAngleAccelleration         = new Vector(   0, 0, 0.5);  // [rad/(s*s)]
  Vector  MaxAngleBrakingAccelleration  = new Vector(   0, 0, 1.0); //1);  // [rad/(s*s)]

  // Router parameters

}

// ================================================
// Device classes
// ================================================

class CTankPzVI_AI_HullDriverDevice
  extends CHullDriverDevice
{
  String m_NormalSetId  = "";//"Body_NormalSet";
  String m_CrashedSetId = "";//"Body_CrashedSet";

  void HullDriverDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      //Vector  MaxSpeed  = new Vector( 1.5, 0, 0);   // m/s
      Behavior.SetMoveAbility(false, 10);
    }
  }

  void HullDriverDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 0);
    }

  }
}

class CTankPzVI_AI_HullGunlayerDevice
  extends CHullGunlayerDevice
{
  String m_NormalSetId  = "Body_NormalSet";
  String m_CrashedSetId = "Body_CrashedSet";

  Vector TurretOutForceMin  = new Vector(0.0, 0.0, 7.0);
  Vector TurretOutForceMax  = new Vector(0.0, 0.0, 8.0);
  float  TurretOutForceThetaMin  = 20;
  float  TurretOutForceThetaMax  = 35;
  Vector TurretOutRadiusMin = new Vector(0.5, 0.5, 0.5);
  Vector TurretOutRadiusMax = new Vector(1.0, 1.0, 1.0);  /* */

  void HullGunlayerDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 25);
    }
  }

  void HullGunlayerDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 0);
      Behavior.SetFireAbility(false, 0);
      Behavior.SetAimAbility(false, 0);
    }

 //   boolean TurretOut = (rand(0.0f, 1.0f) >= 0.4);

    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      if (1 == randnum(2))
        StateControl.SetDelayItemHP(_HostObject.GetItem("TrackLeft").Index, 0.0, 0);

      if (1 == randnum(2))
        StateControl.SetDelayItemHP(_HostObject.GetItem("TrackRight").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("HullDriver").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("HullEngine").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("Turret_A").Index, 0.0, 0);

//      StateControl.SetHitPoints(0.0);
    }

/*
    if (TurretOut)
    {
      logWarning("[TurretOut] Is there section for Turret OUT animation!");
      //StateControl.SetCustomState(CUnitStateControl::USID_TurretOut, CUnitStateControl::US_TurretOut);
      Component Mesh = _HostObject.GetObject("Mesh");
      Component Game = new #GameController();
      if(Mesh != null && Game.GetGameMode() == "Single")
      {
        logWarning("UnlinkJoint Turret_A_Crashed");
        Component PhysicsController = _HostObject.SetupPhysicaleItem("CTankPzVI_AI_TurretSubstance", 10000.0, "Turret_A_Crashed");
        //PhysicsController.AppendExternalForce(GetForce(), GetRadius());
        PhysicsController.AppendExternalForceTheta(GetForce(), GetThetaForce(), GetRadius());
      }
    } */
  }
}

class CTankPzVI_AI_HullEngineDevice
  extends CHullEngineDevice
{
  String m_NormalSetId  = "";//"Body_NormalSet";
  String m_CrashedSetId = "";//"Body_CrashedSet";

  void HullEngineDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Vector  MaxSpeed  = new Vector( 0.5, 0, 0);   // m/s
    }
  }

  void HullEngineDeviceDestroyed(Component _HostObject)
  {

    clearEventsForObject(getIdentificator(_HostObject));

    Component IdleSound = _HostObject.GetObject("IdleSound");
    if (IdleSound != null)
    {
      IdleSound.StopSoundPlaying(true);
    }

    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      // Change Item hit points after delay in N seconds. SetDelayItemHP(ItemIndex, HitPoints, Time)
      StateControl.SetDelayItemHP(_HostObject.GetItem("HullEngine").Index, 0.0, 35+randnum(15));
      StateControl.SetHitPoints(0.0);

    Component IdleSound = _HostObject.GetObject("IdleSound");
    if (IdleSound != null)
    {
      IdleSound.StopSoundPlaying(true);
    }

    }
   Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)   //  && HitPoints == 0.0
    {

      Behavior.SetMoveAbility(false, 0);
    }

  }
}

class CTankPzVI_AI_TrackLeftDevice
  extends CTrackLeftDevice
{
  String m_NormalSetId  = "TrackLeft_NormalSet";
  String m_CrashedSetId = "TrackLeft_CrashedSet";

  void TrackLeftDeviceDamaged(Component _HostObject)
  {
    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {

      // Change Item hit points after delay in N seconds. SetDelayItemHP(ItemIndex, HitPoints, Time)
      StateControl.SetDelayItemHP(_HostObject.GetItem("TrackLeft").Index, 100.0, 10.0 );
    }
    
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior!= null)
    {
      Behavior.SetBrakeAngle(1.5f);
      Behavior.SetMoveAbility(false, 10);
    }
  }

  void TrackLeftDeviceDestroyed(Component _HostObject)
  {

    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      // Change Item hit points after delay in N seconds. SetDelayItemHP(ItemIndex, HitPoints, Time)
      StateControl.SetDelayItemHP(_HostObject.GetItem("TrackLeft").Index, 0.0, 0.0 );
      StateControl.SetDelayItemHP(_HostObject.GetItem("HullEngine").Index, 0.0, 0.0 );
    }
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior!= null)   // 
    {
      CanMove = false;
    }
  }
}

class CTankPzVI_AI_TrackRightDevice
  extends CTrackRightDevice
{
  String m_NormalSetId  = "TrackRight_NormalSet";
  String m_CrashedSetId = "TrackRight_CrashedSet";

  void TrackRightDeviceDamaged(Component _HostObject)
  {
        Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      // Change Item hit points after delay in N seconds. SetDelayItemHP(ItemIndex, HitPoints, Time)
      StateControl.SetDelayItemHP(_HostObject.GetItem("TrackRight").Index, 100.0, 10.0 );
    }
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(-1.5f);
      Behavior.SetMoveAbility(false, 10);

    }
  }

  void TrackRightDeviceDestroyed(Component _HostObject)
  {
     Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      // Change Item hit points after delay in N seconds. SetDelayItemHP(ItemIndex, HitPoints, Time)
      StateControl.SetDelayItemHP(_HostObject.GetItem("TrackRight").Index, 0.0, 0.0 );
      StateControl.SetDelayItemHP(_HostObject.GetItem("HullEngine").Index, 0.0, 0.0 );
    }
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior!= null)   //
    {
     // Behavior.SetBrakeAngle(-1.5f);
     // Behavior.SetMoveAbility(false, 0);
      CanMove = false;
    }
  }
}

class CTankPzVI_AI_TurretDevice
  extends CTurretDevice
{
  String m_NormalSetId  = "Turret_A_NormalSet";
  String m_CrashedSetId = "Turret_A_CrashedSet";
/*
  Vector TurretOutForceMin  = new Vector(3.0, 0.0, 4.0);
  Vector TurretOutForceMax  = new Vector(-3.0, 2.0, 6.0);
  Vector TurretOutRadiusMin = new Vector(0.5, 0.5, 0.5);
  Vector TurretOutRadiusMax = new Vector(1.0, 2.0, 1.5);    */

  void TurretDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 45);
      Behavior.SetAimAbility(false, 30);
    }
  }

  void TurretDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetFireAbility(false, 0);
      Behavior.SetAimAbility(false, 0);
      Behavior.SetMoveAbility(false, 0);
    }
/*
    Component IdleSound = _HostObject.GetObject("IdleSound");
    if (IdleSound != null)
    {
      IdleSound.StopSoundPlaying(true);
    }
          */
    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      StateControl.SetDelayItemHP(_HostObject.GetItem("Turret_A").Index, 0.0, 0);
    }
  }
}

class CTankPzVI_AI_RecoilController
{
  String FToBAnim   = "body_recoil_fb";
  String BToFAnim   = "body_recoil_bf";
  String RToLAnim   = "body_recoil_rl";
  String LToRAnim   = "body_recoil_lr";
  float  RecoilTime = 0.5;
};

class CTankPzVI_AI_TurretSubstance
  extends CMetalSubstance
{
  Vector MainFrictionAxis = new Vector(0.0, 0.0, 1.0);
  float  Friction         = 3.9;
  float  Friction1        = 6.9;
  float  Elasticity       = 0.0;
}
class CTankPzVI_AI_Substance
  extends CMetalSubstance
{
  Vector MainFrictionAxis = new Vector(0.0, 0.0, 1.0);
  float  Friction         = 0.5;
  float  Friction1        = 1.0;
  float  Elasticity       = 0.0;
}

class CTankPzVI_AI_MainWheel
{
  float  Mass        = 800.0;
  Vector IT          = new Vector(0.109212, 0.109212, 0.107521);
  float  Elasticity  = 0.1;
  float  Friction    = FLT_MAX;
  float  Friction1   = 1.0;
}

class CTankPzVI_AI_ManualControl
  extends  CBaseManualControl   //  CConstraintProperties
{
  // =========================================
  // Tank properties
  // =========================================

  float  Mass                 = 56000.0;
  Vector IT                   = new Vector(0.874482, 3.152529, 3.804275);
  float  Elasticity           = 0.09;
  float  Friction             = 1.0;
  float  SuspensionHeight = 0.30;    // cm
  float  SuspensionPower  = 50000;  // kg

  // =========================================
  // Tank body drop coefficients
  // =========================================

  // angular damping coefficients by axises X, Y and Z
  Vector AngularDampingCoeff  = new Vector(1.0, 1.0, 0.5);
  // linear damping coefficients by axises X, Y and Z
  Vector LinearDampingCoeff   = new Vector(2.5, 2.7, 1.6);

  // =========================================
  // Wheels configuration
  // =========================================    

  Array  Wheels               = [

                                  // Left side

                                  [ "WheelLeftMain1_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelLeftMain2_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelLeftMain3_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelLeftMain4_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelLeftMain5_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelLeftMain6_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelLeftMain7_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelLeftMain8_CS", new CTankPzVI_AI_MainWheel()  ],

                                  // Right side

                                  [ "WheelRightMain1_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelRightMain2_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelRightMain3_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelRightMain4_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelRightMain5_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelRightMain6_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelRightMain7_CS", new CTankPzVI_AI_MainWheel()  ],
                                  [ "WheelRightMain8_CS", new CTankPzVI_AI_MainWheel()  ]

                                ];
                                
  // =========================================
  // Other systems
  // =========================================

  Component EngineSystem      = new CTankPzVITigerE1EngineSystem();   //

  // =========================================
  // Sounds
  // =========================================


  Component LeftTrackSound    = new #Emitter<CTankPzVIAusfE_TrackSound>();
  Component RightTrackSound   = new #Emitter<CTankPzVIAusfE_TrackSound>();

  float  BeginTrackSoundFreq  = 0.25; //
  float  TrackSpeedScaleCoeff = 1.0 / 12000.0; //
}
// ================================================
// Unit class
// ================================================

class CTankPzVI_AI_Unit
    extends CTankUnit, CWeaponConfig, CPushVehicleObject
{

  static category UnitType = CLASSIFICATOR_T34_HEAVY_TANK;

  static Array PostExplosionID = [
                                    ["", "TankPzVIAusfEExplosion"]
                                 ];
  static Array Hatches = [
                            [ "Luk_Driver",    "luk_body_open",      2.0 ],
                            [ "Luk_Commander", "luk_main_open",      1.0 ],
                            [ "Commander",  "luk_main_commander", 1.0 ]
                         ];

  static Array HatchesStates = [
                                  [ "Normal", [  [ "Luk_Commander", 1.0 ], [ "Commander", 1.0 ], [ "Luk_Driver", 0.0 ] ] ],
                                  [ "Attack", [ [ "Luk_Driver", 0.0 ], [ "Luk_Commander", 0.0 ], [ "Commander", 0.0 ] ] ]
                               ];
/*
 Array   TurretOutAnimations = [
                                  [  1.0, new #LineAnimator<CTankPzVIAusfETurretOutAnimator1>() ]
                                ];  */
  final static float DefaultHitPoints = CHitPoints::TankPzVI_AI_UnitHitPoints;
  final static String DefaultHealthParameter = "HP_HEALTHY";  // fragile constitution
  final static int    UnitMenacePower        = MENACE_NORMAL;  // light weapon
  final static Array  AutomaticClassificators  = ["GROUND", "TANK", "GER"];
  final static String DefaultSurfaceControl = "PutonGroundLandingJoints";            //
  static Array        LandingJoints            = ["Corner_FL", "Corner_RL", "Corner_RR", "Corner_FR"];

  static Array  SubstanceArmourWidth = [
                                         [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVI_AI_UnitArmourTurretFWD  ],
                                         [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVI_AI_UnitArmourTurretREAR ],
                                         [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVI_AI_UnitArmourTurretTOP  ],
                                         [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVI_AI_UnitArmourTurretLEFT ],
                                         [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVI_AI_UnitArmourTurretRIGHT],
                                         [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVI_AI_UnitArmourHullFWD    ],
                                         [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVI_AI_UnitArmourHullREAR   ],
                                         [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVI_AI_UnitArmourHullTOP    ],
                                         [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVI_AI_UnitArmourHullBOTTOM ],
                                         [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVI_AI_UnitArmourHullRIGHT  ],
                                         [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVI_AI_UnitArmourHullLEFT   ]
                                      ];

   Array m_DamageTransfer = [ // From Item , To Item, Item HitPoints Percent
                             ["HullDriver", "HullEngine", 0.2f],
                             ["HullDriver", "HullGunlayer", 0.2f]
                             ];

  boolean m_AITankCollisionShape = true;

  // =======================================
  // Contruction and initialization
  // =======================================

  void CTankPzVI_AI_Unit()
  {
    SetupMesh(new #AnimatedObject<Cu_veh_PzVI_AI_Model>(), [300, 170, 50, 5]);

    // Setup trucks 
    SetupTracks(
        new #TrackAnimator<CTankPzVI_AI_LeftTrack>(),
        new #TrackAnimator<CTankPzVI_AI_RightTrack>()
      );

    // Setup Weapon
    SetupWeapon("Weapon_A", new #Weapon<CTankPzVI_AI_Gun>(),
      ["Fire_A1"], new #TargetingAnimator<CTankPzVI_AI_GunTargetingAnimatorA>());

    //SetupWeapon("Weapon_B", new #Weapon<CTankPzVI_AI_CoaxialMachineGun>(), "Fire_A1", ["Fire_B1"], null);

    SetupWeapon("Weapon_C", new #Weapon<CTankPzVI_AI_MachineGun>(),       //
      ["Fire_C1"], new #TargetingAnimator2<CTankPzVI_AI_TargetingAnimatorB>());   


    // Creates and register unit state component
    // MoveSound, TraceEffectId
    SetMovementEffects(
        new #Emitter<CTankPzIVGMovementSound>(),
        [
          ["Vapor_L", "GroundUnitTraceEffect"],
          ["Vapor_R", "GroundUnitTraceEffect"],
          ["Smoke",   "PetrolSmokeEffect"]
        ]
      );

    SetIdleEffects(
        new #Emitter<CTankPzIVGIdleSound>()
      );

    SetAccelEffects(
        new #Emitter<CTankPzIVGAccelSound>(),
        [
          ["Smoke", "PetrolAccelSmokeEffect", new Vector ( 0.0, 0.0, 0.0)]
        ]
      );

      // Setup turret out animator
//     SetTurretOutEffectsArray( TurretOutAnimations );
     SetupBehavior( new #VehicleBehavior<CTankPzVI_AI_Behavior>());
  }


  // =======================================
  // Collision control
  // =======================================

  Component CreateCollisionControl(String _ScriptClassName)
  {
    Component CollisionControl = new #CollisionControl2();
    CollisionControl.SetCollisionMask(
        [CLASSIFICATOR_WALK_SURFACE],
        [ CLASSIFICATOR_DO_NOT_COLLISION_CHECK, CLASSIFICATOR_PHYSICS_CONTROLLABLE ]
       );

    loadFromScript(CollisionControl, _ScriptClassName);
    RegisterObject("CollisionControl", CollisionControl);

    return CollisionControl;
  }

  void Construct(
      Component _Mission,
      Component _PropMap
    )
  {

    CUnit::Construct(_Mission, _PropMap);

    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET762792, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET127, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_SUBCALIBREBULLET7576, 0.4);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET7576, 0.2);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BUILDING, 0.0);

    // create effects for tracks: [ HostId, Effectid, ZoneId ]
    SetTrackEffects(
        _Mission,
        [
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest01, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest01, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest02, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest02, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest03, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest03, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest04, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Forest04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush01, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush01, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush02, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush02, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush03, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush03, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush04, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_Bush04, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Right" ],
          ["Corner_RL", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Left" ],
          ["Corner_RR", "ForestComplexTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ]
        ]
      );

    CreateUnitItem(
        "HullDriver",
        CJointPoints::TankPzVI_AI_UnitHULL_DRIVERPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "HullDriver"
      );
    CreateUnitItem(
        "HullGunlayer",
        CJointPoints::TankPzVI_AI_UnitHULL_GUNLAYERPoints,
        ["GenericDamageItemEffect", "HullGunLayerExplosionEffect"],
        "HullGunlayer"
      );
    CreateUnitItem(
        "HullEngine",
        CJointPoints::TankPzVI_AI_UnitHULL_ENGINEPoints ,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "HullEngine"
      );
    CreateUnitItem(
        "TrackLeft",
        CJointPoints::TankPzVI_AI_UnitTRACK_LEFTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackLeft"
      );
    CreateUnitItem(
        "TrackRight",
        CJointPoints::TankPzVI_AI_UnitTRACK_RIGHTPoints ,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackRight"
      );
    CreateUnitItem(
        "Turret_A",
        CJointPoints::TankPzVI_AI_UnitTURRETPoints,
        ["GenericDamageItemEffect", "GenericLargeFirePostSmokeRefuseEffect"],
        ["Turret_A_Crashed", "Turret_A_Crashed"],
        "Turret_A"
      );

    logWarning("Weapon fire deviation for " + getIdentificator(this) + "=" + new String(GetObject("Weapon_A").FireDeviation));

    LinkDeviceToUnitItem("HullDriver",   new CTankPzVI_AI_HullDriverDevice());
    LinkDeviceToUnitItem("HullGunlayer", new CTankPzVI_AI_HullGunlayerDevice());
    LinkDeviceToUnitItem("HullEngine",   new CTankPzVI_AI_HullEngineDevice());
    LinkDeviceToUnitItem("TrackLeft",    new CTankPzVI_AI_TrackLeftDevice());
    LinkDeviceToUnitItem("TrackRight",   new CTankPzVI_AI_TrackRightDevice());
    LinkDeviceToUnitItem("Turret_A",     new CTankPzVI_AI_TurretDevice());

    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));

    SetupRecoilController(new #RecoilController<CTankPzVI_AI_RecoilController>());
    CreateCollisionControl("CBaseCollisionControl"); //


     if ((new #GameController()).GetGameMode() == "Single")            //!= "Single")
       GetObject("Mesh").SetAnimateAlways(true);

      Component VehicleController = new #AITankVehicle<CTankPzVI_AI_ManualControl>();
 //   Component VehicleController = GetPhysicsController();

    if (null == VehicleController)
    {
      logError("Cant setup type of vehicle control for " + getIdentificator(this));
      return;
    }

    RegisterObject("AIVehicleController", VehicleController);
    VehicleController.SetEventHandler(this);
       // Create mesh
    Component Mesh = GetMeshComponent();
       // Create base object
    Array BaseShapes = Mesh.GetCollisionShapes(Mesh.GetRootJoint(), false);
    Component Body = VehicleController.CreateObject(Mesh, BaseShapes);

    SetupPhysicaleObject("CTankPzVI_AI_Substance", 60000.0, 0.0);    //
   // GetPhysicsController().SetFixedBody("Mesh", true);
    // Setup hatches controls
    Component hatches = new #HatchesStateController();
    hatches.AddHatches( Hatches );
    hatches.AddStates( HatchesStates );
    SetupHatches( hatches );
    hatches.SetHatchesState( "Normal" );
    EnableSurfaceControl(true);
    GetLeftTrack().EnableAutoCalcPath(true);
    GetRightTrack().EnableAutoCalcPath(true);
  }


  // ======================================
  // Armour descriptor
  // ======================================
  Array GetArmourDescriptor()
  {
    return new Array ([
                        [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVI_AI_UnitArmourTurretFWD  ],
                        [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVI_AI_UnitArmourTurretREAR ],
                        [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVI_AI_UnitArmourTurretTOP  ],
                        [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVI_AI_UnitArmourTurretLEFT ],
                        [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVI_AI_UnitArmourTurretRIGHT],
                        [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVI_AI_UnitArmourHullFWD    ],
                        [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVI_AI_UnitArmourHullREAR   ],
                        [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVI_AI_UnitArmourHullTOP    ],
                        [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVI_AI_UnitArmourHullBOTTOM ],
                        [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVI_AI_UnitArmourHullRIGHT  ],
                        [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVI_AI_UnitArmourHullLEFT   ]
                      ]);
  }

  // ======================================
  // Point collision detector
  // ======================================

  // Call when tank deep in the water (¬ызываетс€, когда танк глубоко заехал в воду)
  event void OnPointCollisionDetect(String _ObjectID)
  {
    // Destroy HullEngine may be changed (убиваем движок, можно заменить на что-то другое)
    SetUnitItemHPPercent("HullEngine", 0.0);
    
    GetObject("PointDetector").EnableDetector(false);
  }

   event void SetModelViewState(
       boolean _State
     )
   {
     // TMP
   }

     event void KillUnit()
  {
    Component Behavior = GetObject("Behavior");
    if (Behavior != null)
    {
      //Behavior.ActivateMovement(false);
      //Behavior.ActivateFire(false);
      Behavior.SetAimAbility(false,0);
      Behavior.SetMoveAbility(false,0);
      Behavior.SetFireAbility(false,0);
    }
    Component StateControl = GetObject("StateControl");
    if (StateControl != null)
    {
      StateControl.SetDelayItemHP(GetItem("TrackLeft").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("TrackRight").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullDriver").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullEngine").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("HullGunlayer").Index, 0.0, 0);

      StateControl.SetDelayItemHP(GetItem("Turret_A").Index, 0.0, 0);
    }
    Component Mission = new #GameController().GetObject(SOID_MissionController);
    if (Mission != null)
    {
       Component Object = Mission.GetObject(getIdentificator(this));
       if(Object != null)
       {
         Object.OnLifeStateChanged(false);
       }
    }
  }
}


