//-------------------------------------------------------------------
/*     CockpitNearCameraGunner  CockpitCameraGunner
      Array  Animation = [
      ["L_Wheel01_lift", ["joint_WheelLeftMain1_UP", 0, 20]],
      ["L_Wheel02_lift", ["joint_WheelLeftMain2_UP", 0, 20]],
      ["L_Wheel03_lift", ["joint_WheelLeftMain3_UP", 0, 20]],
      ["L_Wheel04_lift", ["joint_WheelLeftMain4_UP", 0, 20]],
      ["L_Wheel05_lift", ["joint_WheelLeftMain5_UP", 0, 20]],
      ["L_Wheel06_lift", ["joint_WheelLeftMain6_UP", 0, 20]],
      ["L_Wheel07_lift", ["joint_WheelLeftMain7_UP", 0, 20]],
      ["L_Wheel08_lift", ["joint_WheelLeftMain8_UP", 0, 20]],
      ["R_Wheel01_lift", ["joint_WheelRightMain1_UP", 0, 20]],
      ["R_Wheel02_lift", ["joint_WheelRightMain2_UP", 0, 20]],
      ["R_Wheel03_lift", ["joint_WheelRightMain3_UP", 0, 20]],
      ["R_Wheel04_lift", ["joint_WheelRightMain4_UP", 0, 20]],
      ["R_Wheel05_lift", ["joint_WheelRightMain5_UP", 0, 20]],
      ["R_Wheel06_lift", ["joint_WheelRightMain6_UP", 0, 20]],
      ["R_Wheel07_lift", ["joint_WheelRightMain7_UP", 0, 20]],
      ["R_Wheel08_lift", ["joint_WheelRightMain8_UP", 0, 20]],
      ["body_recoil_fb", ["Body", 0, 30]],
      ["body_recoil_bf", ["Body", 30, 60]],
      ["body_recoil_rl", ["Body", 60, 90]],
      ["body_recoil_lr", ["Body", 90, 120]],
      ["gun_a", ["Weapon_B", 0, 1]],
      ["gun_a_recoil", ["Weapon_A1", 0, 30]],
      ["gun_c_leftdn", ["Weapon_C", 6, 7]],
      ["gun_c_leftup", ["Weapon_C", 2, 3]],
      ["gun_c_rightdn", ["Weapon_C", 4, 5]],
      ["gun_c_rightup", ["Weapon_C", 0, 1]],
      ["luk1_open", ["Hat_Load", 0, 2]],
      ["luk4_open", ["LoadHatch", 0, 2]],
      ["block_open", ["DRV_Block", 0, 4]],
      ["luk_body_open", ["HING02", 0, 4], ["HATCH02", 0, 4]],
      ["luk_main_commander", ["Body_commander", 0, 60]],
      ["luk_main_open", ["Cupola_Hatch", 0, 4],["Cupola_Hinge1", 0, 4]],
      ["turret_a", ["Turret_A", 0, 4]],
      ["wheels_left", ["WheelLeftFront", 0, 60], ["WheelLeftMain1", 0, 60], ["WheelLeftMain2", 0, 60], ["WheelLeftMain3", 0, 60], ["WheelLeftMain4", 0, 60], ["WheelLeftMain5", 0, 60], ["WheelLeftMain6", 0, 60], ["WheelLeftMain7", 0, 60], ["WheelLeftMain8", 0, 60], ["WheelLeftRear", 0, 60]],
      ["wheels_right", ["WheelRightFront", 0, 60], ["WheelRightMain1", 0, 60], ["WheelRightMain2", 0, 60], ["WheelRightMain3", 0, 60], ["WheelRightMain4", 0, 60], ["WheelRightMain5", 0, 60], ["WheelRightMain6", 0, 60], ["WheelRightMain7", 0, 60], ["WheelRightMain8", 0, 60], ["WheelRightRear", 0, 60]]
    ];

  Map    ConfigSets = new Map([
      [ "Body_CrashedSet", [ "Body_Crashed" ] ],
      [ "Body_NormalSet", [ "Body", "Body_2", "HullDriver", "HullEngine", "HullGunlayer", "Luk_C", "Luk_D", "Weapon_C" ] ],
      [ "TrackLeft_CrashedSet", [ "TrackLeft_Crashed" ] ],
      [ "TrackLeft_NormalSet", [ "GearLeftMain", "TrackLeft"] ],
      [ "TrackRight_CrashedSet", [ "TrackRight_Crashed" ] ],
      [ "TrackRight_NormalSet", [ "GearRightMain", "TrackRight" ] ],
      [ "Turret_A_CrashedSet", ["Body_commander_crashed" ] ],
      [ "Turret_A_NormalSet", [ "TURRET_A", "Body_commander" ] ]

    ]);

*/
//-------------------------------------------------------------------  course_2

// Unit Explosion
class CTankPzVITigerE1_EarlyExplosion
  extends CHeavyTankExplosion
{
  float  Damage   = 5.0;
  float  Radius   = 1.0;
}

// Machine gun
class CTankPzVITigerE1_EarlyMachineGunBulletExplosion
  extends CMachineGun127BulletExplosion
{
  float  Damage   = CPiercing::TankPzVIAusfEMachineGunDamage;
}

class CTankPzVITigerE1_EarlyMachineGunBulletControl
  extends CFakeMachineGunBulletControl
{
  String ExplosionId  = "TankPzVIAusfEMachineGunBulletExplosion"; //
  Vector GravityAccel = CPiercing::BulletGravityVector;
  float  BulletSpeed  = 750.0;
  float  Mass         = 0.009;
}

class CTankPzVITigerE1_EarlyCoaxialMachineGun
    extends CMachineGun, CPlayerWeapon
{
  final static String BulletPatternId  = "TankPzVIAusfEMachineGunBullet";

  final static float  FireDeviation    = 0.05;

  final static Array Ammo = [0];

  final static Vector  GravityVector   = CPiercing::BulletGravityVector;
  final static boolean HighTrajectory  = false;

  Component BurstFireSound  = new #Emitter<CMG34MachineGunFireSound>();

  final static float    LockAngleHMin     = -7.0;
  final static float    LockAngleHMax     =  7.0;
  final static float    LockAngleVMin     = -7.0;
  final static float    LockAngleVMax     =  7.0;
  final static float    BlockedLockAngle  =  0.0;

  final static int Slot = 1;

  //  Gun parameters for behavior
  final static int  FirePeriod        = 10; // ms
  final static int  FirePeriodRandAdd = 0; // ms

  final static boolean BurstFire      = true;
  final static int  BurstTime         = 2800; // ms
  final static int  BurstTimeRandAdd  = 1000; // ms

  final static int  BurstDelay        = 0; // ms
  final static int  BurstDelayRandAdd = 0; // ms
  // gun specific fire mask with priorities
  final static Array GunSpecificFireMask = [
                                [[],[]], // low priority mask: RestrictTo, Exclude
                                [[],[]]
                              ];        /**/
}
class CTankPzVITigerE1_EarlyPlayerCoaxialMachineGun
    extends CTankPzVITigerE1_EarlyCoaxialMachineGun
{
  final static float     FireDeviation  = 0.05;
 /*
  void OnWeaponFire()
  {
    sendEvent(0.0f, SOID_MissionController, "IncreaseShoots", []); 
  } 
*/
}
class CTankPzVITigerE1_EarlyMachineGun
    extends CMachineGun, CPlayerWeapon //
{
  final static String BulletPatternId = "TankPzVIAusfEMachineGunBullet";
  final static float MinDistance      = 1;
  final static float MaxDistance      = 1600;
  final static float     FireDeviation   = 0.05;

  final static Array Ammo = [0];

  final static Vector  GravityVector   = CPiercing::BulletGravityVector;
  final static boolean HighTrajectory  = false;

  final static float    LockAngleHMin     = -7.0;
  final static float    LockAngleHMax     =  7.0;
  final static float    LockAngleVMin     =  -7.0;
  final static float    LockAngleVMax     =  7.0;
  final static float    BlockedLockAngle  =   0.0;

  Component BurstFireSound  = new #Emitter<CMG34MachineGunFireSound>();

  final static int Slot = 2;

  // Gun parameters for behavior
  final static int  FirePeriod        = 200; // ms // murkz trying 200 instead of 10 , yeah 200 has fixed it!
  final static int  FirePeriodRandAdd = 0; // ms

  final static boolean BurstFire      = true;
  final static int  BurstTime         = 2800; // ms
  final static int  BurstTimeRandAdd  = 1000; // ms

  final static int  BurstDelay        = 0; // ms
  final static int  BurstDelayRandAdd = 0; // ms
  // gun specific fire mask with priorities 
  final static Array GunSpecificFireMask = [
                                [[],[]], // low priority mask: RestrictTo, Exclude
                                [[],[]]
                              ];      /* */
}

class CTankPzVITigerE1_EarlyPlayerMachineGun
    extends CTankPzVITigerE1_EarlyMachineGun
{
  final static float     FireDeviation  = 0.05;

}

// Main cannon section
// Main cannon animator
class CTankPzVITigerE1_EarlyGunTargetingAnimatorA
  extends CTargetingAnimator
{
  String HorAnimName    = "turret_a";
  String VerAnimName    = "gun_a";

  float  LeftEndAngle   =  180.0;
  float  RightEndAngle  = -180.0;
  float  TopEndAngle    =  -7.0;
  float  BottomEndAngle =  20.0;
}
// Main cannon bullet explosion
class CTankPzVITigerE1_EarlyGunCalibreBulletExplosion
  extends CTankPzVIAusfEGunCalibreBulletExplosion
{
}

class CTankPzVITigerE1_EarlyGunCalibreBulletDebrisCloud
  extends CTankPzVIAusfEGunCalibreBulletDebrisCloud
{

}

class CTankPzVITigerE1_EarlyGunCalibreBulletDebrisControl
{
  Array     Classificator = [];
  boolean   IsMotionBlur  = true;
  float     MaxDistance   = CPiercing::TankPzVIAusfECalibreDebrisMaxDistance;
  String    ExplosionId   = "TankPzVIAusfEGunCalibreBulletDebrisExplosion";
  float     Mass          = 0.02;
}

class CTankPzVITigerE1_EarlyGunCalibreBulletDebrisExplosion
  extends CTankPzVIAusfEGunCalibreBulletDebrisExplosion
{
}

class CTankPzVITigerE1_EarlyGunSubcalibreBulletExplosion
  extends CTankPzVIAusfEGunSubcalibreBulletExplosion
{

}

class CTankPzVITigerE1_EarlyGunHEBulletExplosion
  extends CTankPzVIAusfEGunHEBulletExplosion
{

}

class CTankPzVITigerE1_EarlyGunHEBulletDebrisCloud
  extends CTankPzVIAusfEGunHEBulletDebrisCloud
{

}
class CTankPzVITigerE1_EarlyGunHEBulletDebrisControl
  extends CTankPzVIAusfEGunHEBulletDebrisControl
{

}

class CTankPzVITigerE1_EarlyGunHEBulletDebrisExplosion
  extends CTankPzVIAusfEGunHEBulletDebrisExplosion
{

}
class CTankPzVITigerE1_EarlyGunCalibreBulletControl
  extends CTankPzVIAusfEGunCalibreBulletControl
{
  String    ExplosionId  = "TankPzVIAusfEGunCalibreBulletExplosion";
  float     BulletSpeed  = CPiercing::TankPzVIAusfECalibreBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::TankPzVIAusfECalibreMaxDistance;
  float     PenetrationPower      = CPiercing::TankPzVIAusfECalibrePenetrationPower;
  Array     PenetrationByDistance = CPiercing::TankPzVIAusfECalibrePenetrationByDistance;
  float     PenetrationModifierMin   = CPiercing::TankPzVIAusfECalibrePenetrationModifier[0];
  float     PenetrationModifierMax   = CPiercing::TankPzVIAusfECalibrePenetrationModifier[1];
/*  float     DamageModifierMin        = CPiercing::TankPzVIAusfECalibreDamageModifier[0];
  float     DamageModifierMax        = CPiercing::TankPzVIAusfECalibreDamageModifier[1];   */
}

class CTankPzVITigerE1_EarlyGunSubCalibreBulletControl
  extends CTankPzVIAusfEGunSubCalibreBulletControl
{
  String    ExplosionId  = "TankPzVIAusfEGunSubcalibreBulletExplosion";
  float     BulletSpeed  = CPiercing::TankPzVIAusfESubcalibreBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::TankPzVIAusfESubcalibreMaxDistance;
  float     PenetrationPower      = CPiercing::TankPzVIAusfESubcalibrePenetrationPower;
  Array     PenetrationByDistance = CPiercing::TankPzVIAusfESubcalibrePenetrationByDistance;
  float     PenetrationModifierMin   = CPiercing::TankPzVIAusfESubcalibrePenetrationModifier[0];
  float     PenetrationModifierMax   = CPiercing::TankPzVIAusfESubcalibrePenetrationModifier[1];
/*  float     DamageModifierMin        = CPiercing::TankPzVIAusfESubcalibreDamageModifier[0];
  float     DamageModifierMax        = CPiercing::TankPzVIAusfESubcalibreDamageModifier[1]; */
}

class CTankPzVITigerE1_EarlyGunHEBulletControl
  extends CTankPzVIAusfEGunHEBulletControl
{
  String    ExplosionId  = "TankPzVIAusfEGunHEBulletExplosion";
  float     BulletSpeed  = CPiercing::TankPzVIAusfEHEBulletSpeed;
  Vector    GravityAccel = CPiercing::ShellGravityVector;
  float     MaxDistance           = CPiercing::TankPzVIAusfEHEMaxDistance;
  float     PenetrationPower      = CPiercing::TankPzVIAusfEHEPenetrationPower;
  Array     PenetrationByDistance = CPiercing::TankPzVIAusfEHEPenetrationByDistance;
}


class CTankPzVITigerE1_EarlyCalibreAmmo
{
  final static String BulletPatternId = "TankPzVIAusfEGunCalibreBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],["HUMAN", "VEHICLE", "AIR"]];
  final static float  LoadingTime     = 0.0f;
  // Cockpit UI parms
  final static Array   VoiceID        = ["WeaponShellAP1","WeaponShellAP2","WeaponShellAP3","WeaponShellAP4"];
  final static WString AmmoName       = CWeaponNames::str_PzVIAusfECalibreAP_ShortName;
  final static WString UIName         = L""; // CWeaponNames::str_PzVIAusfECalibreAP_ShortName;
  final static String  Material       = "TankShell_Pzgr40";
  final static String  StatusMaterial = "TankShellFill";
}

class CTankPzVITigerE1_EarlyCalibreAmmoPlayer extends CTankPzVITigerE1_EarlyCalibreAmmo
{
  final static int    Ammunition      = 60;
  final static float  LoadingTime     = 7.0f;
}

class CTankPzVITigerE1_EarlySubCalibreAmmo
{
  final static String BulletPatternId = "TankPzVIAusfEGunSubCalibreBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],["HUMAN", "VEHICLE", "BLD_WAR", "BLD_CIV", "AIR"]];
  final static float  LoadingTime     = 0.0f;
  // Cockpit UI parms
  final static Array   VoiceID        = ["WeaponShellSubAP1","WeaponShellSubAP2","WeaponShellSubAP3","WeaponShellSubAP4"];
  final static WString AmmoName       = CWeaponNames::str_PzVIAusfESubCalibreAP_ShortName;
  final static WString UIName         = L"";  // CWeaponNames::str_PzVIAusfESubCalibreAP_ShortName;
  final static String  Material       = "TankShell_PzGr39HL";
  final static String  StatusMaterial = "TankShellFill";
}

class CTankPzVITigerE1_EarlySubCalibreAmmoPlayer extends CTankPzVITigerE1_EarlySubCalibreAmmo
{
  final static int    Ammunition      = 12;
  final static float  LoadingTime     = 7.0f;
}

class CTankPzVITigerE1_EarlyHEAmmo
{
  final static String BulletPatternId = "TankPzVIAusfEGunHEBullet";
  final static int    Ammunition      = 2000;
  final static Array  TargetMask      = [[],["HEAVYTANK", "TANK", "AIR"]];
  final static float  LoadingTime     = 0.0f;
  // Cockpit UI parms
  final static Array   VoiceID        = ["WeaponShellHE1","WeaponShellHE2","WeaponShellHE3","WeaponShellHE4"];
  final static WString AmmoName       = CWeaponNames::str_PzVIAusfECalibreHE_ShortName;
  final static WString UIName         = L""; // CWeaponNames::str_PzVIAusfECalibreHE_ShortName;
  final static String  Material       = "TankShell_SprGr43";
  final static String  StatusMaterial = "TankShellFill";
}

class CTankPzVITigerE1_EarlyHEAmmoPlayer extends CTankPzVITigerE1_EarlyHEAmmo
{
  final static int    Ammunition      = 20;
  final static float  LoadingTime     = 7.0f;
}

class CTankPzVITigerE1_EarlyMachineGunAmmo
{
  final static String BulletPatternId = "TankPzVIAusfEMachineGunBullet";
  final static int    Ammunition      = 1900;
  final static Array  TargetMask      = [[],[]];
  final static float  LoadingTime     = 0.0f;

  // Cockpit UI parms
  final static int RenderMode         = 1;
  final static WString UIName         = L"";//CWeaponNames::str_PzVIAusfEMG_ShortName;
  final static WString UIName2        = L"";//CWeaponNames::str_PzVIAusfEAmmoContainerName;
  final static String  Material       = "German_MG_Frame";
  final static String  StatusMaterial = "MachinGunFill";
}

class CTankPzVITigerE1_EarlyAmmoContainer
{
  final static String Name = CWeaponNames::str_PzVIAusfEAmmoContainerName;
  final static Array  Ammo = [
                               [0, new CTankPzVITigerE1_EarlyMachineGunAmmo()]
                             ];
}

// Main cannon properties
class CTankPzVITigerE1_EarlyGun
    extends CHeavyGun, CPlayerWeapon, CWeaponFireRecoil
{
  float InitBulletSpeed = 0.0f;
  float   FireDeviation   = 0.01;
  float   MinFireDeviation   = 0.005;
  final static Vector  GravityVector   = CPiercing::ShellGravityVector;
  final static boolean HighTrajectory  = false;

  final static String BulletPatternId = "";
  final static String FireSoundId     = "Pz6MainGunFireSound";
  final static String FireEffectId    = "HeavyGunFireNoMuzzleEffect";
  final static String AmmoLoadSoundId = "TankPzVIAusfE_GunLoadSound";
  final static String AmmoLoadVoiceId = "";
  final static String AmmoLoadedVoiceId = "";

  event void OnWeaponFire()
  {
    Component Object = (new #GameController()).GetMission().GetObject(getIdentificator(this));
    if (null != Object)
      (new #EffectsArray()).CreateEffect("HeavyGunNoMuzzleGroundEffect", getPosition(Object), null);

    CWeaponFireRecoil::OnWeaponFire();
  }

  final static Array Ammo = [
                              new CTankPzVITigerE1_EarlyCalibreAmmo(),
                              new CTankPzVITigerE1_EarlySubCalibreAmmo(),
                              new CTankPzVITigerE1_EarlyHEAmmo()
                            ];

  //$TMP TEST DATA
  final static Array AmmoTargetUse    = [
                                          [0, [["HEAVYTANK"],[]], [[50.0, 250.0, 2000.0, 100.0], [[1000.0, 60.0], [1500.0, 20.0]]]],
                                         // [1, [["HEAVYTANK"],[]], [[500.0, 75.0, 2000.0, 80.0  ], [[1000.0, 40.0], [1500.0, 80.0]]]],
                                          //TANK
                                          [0, [["TANK"],     []], [[50.0, 250.0, 2000.0, 100.0], [[1000.0, 60.0], [1500.0, 20.0]]]],
                                         // [1, [["TANK"],     []], [[500.0, 75.0, 2000.0, 80.0  ], [[1000.0, 40.0], [1500.0, 80.0]]]],
                                          //VEHICLE
                                          [2, [["VEHICLE"],  []], [[500.0, 50.0, 2000.0, 100.0], [[1000.0, 90.0], [1500.0, 100.0]]]],
                                          //HUMAN
                                          [2, [["HUMAN"],    []], [[500.0, 15.0, 1000.0, 0.0],   [[]]]],
                                          //BLD_WAR
                                          [1, [["BLD_WAR"],  []], [[500.0, 90.0, 1000.0, 100.0], []]],
                                          [2, [["BLD_WAR"],  []], [[500.0, 10.0, 1000.0, 0.0  ], []]],
                                          //BLD_CIV
                                          [2, [["BLD_CIV"],  []], [[500.0, 80.0, 1000.0, 100.0], []]]
                                        ];

  final static boolean CanFireInMove  = false;

  final static float  LockAngleHMin   = -180.0;
  final static float  LockAngleHMax   =  180.0;
  final static float  LockAngleVMin   = -7.0;
  final static float  LockAngleVMax   = 20.0;//33.0; Temp
  final static float  BlockedLockAngle  =  0.0;

  final static float DirectionSpeedH  = 6.5; // deg / sec  • horizontal
  final static float DirectionSpeedV  = 3.5; // deg / sec  • vertical
  // for damaged state
  final static float DirectionDamagedSpeedH = 3.5;
  final static float DirectionDamagedSpeedV = 3.5;

  final static float DirectionLowSpeedH  = 1.0; // deg / sec   horizontal
  final static float DirectionLowSpeedV  =  1.0; // deg / sec   vertical

  Component DirectionSoundH  = new #Emitter<CTankHeavyTurretDirectionSoundH>();
  Component DirectionSoundV  = new #Emitter<CTankHeavyTurretDirectionSoundV>();

  final static int     Ammunition     = 2000;        // wrong value

  // *** Gun parameters for behavior
  final static boolean ManualLoad     = true;
  final static boolean UseManualFirePeriod    = false;
  final static int     FirePeriod        = 7000; // ms
  final static int     FirePeriodRandAdd = 2000; // ms

  final static boolean BurstFire      = false;
  final static int  BurstTime         = 2000; // ms
  final static int  BurstTimeRandAdd  = 0; // ms

  final static int  BurstDelay        = 3000; // ms
  final static int  BurstDelayRandAdd = 2000; // ms

  final static int     Slot             = 0;
  final static boolean Primary          = true; // GUN should be marked as Primary

  // gun specific fire mask with priorities
  final static Array GunSpecificFireMask = [
                                [["GROUND"],[]], // high priority mask: RestrictTo, Exclude
                                [["NAVAL"],[]],  // low priority mask
                                [["STRUCTURE"],[]]  // very-very low priority target with a pulley in the middle
                              ];

  Component FireAnimator = new #LineAnimator<CTankPzVITigerE1_EarlyFireAnimation>();  //
}

class CTankPzVITigerE1_EarlyPlayerGun
    extends CTankPzVITigerE1_EarlyGun
{
  final static float     FireDeviation   = 0.001;
  final static String FireSoundId     = "PzVI_E_TankGunShootSound";
  final static String AmmoLoadVoiceId = "TankPzVIAusfE_GunLoadVoice";  //
  final static String AmmoLoadedVoiceId = "TankPzVIAusfE_GunLoadedVoice"; //
  final static Array Ammo = [
                              new CTankPzVITigerE1_EarlyCalibreAmmoPlayer(),
                              new CTankPzVITigerE1_EarlySubCalibreAmmoPlayer(),
                              new CTankPzVITigerE1_EarlyHEAmmoPlayer()
                            ];

  final static float DirectionSpeedH  = 6.5; // deg / sec  • horizontal
  final static float DirectionSpeedV  = 2.5; // deg / sec  • vertical
  // for damaged state
  final static float DirectionDamagedSpeedH = 3.5;
  final static float DirectionDamagedSpeedV = 3.5;

  final static float DirectionLowSpeedH  = 1.0; // deg / sec   horizontal
  final static float DirectionLowSpeedV  =  1.0; // deg / sec   vertical

  int m_CurrentAmmoLoaded = 0;

  event void OnWeaponFire()
  {
    CTankPzVITigerE1_EarlyGun::OnWeaponFire();
    sendEvent(0.0f, SOID_MissionController, "IncreaseShoots", []);
   logWarning("CTankPzVITigerE1_EarlyGun::OnWeaponFire()");     //
  }

  void OnAmmoLoad(
      int _AmmoID
    )
  {
//    logWarning("OnAmmoLoad");
    if (m_CurrentAmmoLoaded != _AmmoID)
    {
      m_CurrentAmmoLoaded = _AmmoID;
      Component Mission = new #GameController().GetMission();
      if (null != Mission)
        Mission.GetObject(Mission.GetMainPlayerObjectID()).ReportAmmoLoad(Ammo[_AmmoID]);
    }
  }

  void OnAmmoLoaded(
      int _AmmoID
    )
  {
    logWarning("OnAmmoLoaded");
    Component Mission = new #GameController().GetMission();
    if (null != Mission)
      Mission.GetObject(Mission.GetMainPlayerObjectID()).ReportAmmoLoaded(Ammo[_AmmoID]);
  }

}
// Machinegun section
// Machinegun animator
class CTankPzVITigerE1_EarlyTargetingAnimatorB
  extends CTargetingAnimator
{
  String LeftUpAnimName    = "gun_c_leftup";
  String LeftDownAnimName  = "gun_c_leftdn";
  String RightUpAnimName   = "gun_c_rightup";
  String RightDownAnimName = "gun_c_rightdn";

  float  LeftEndAngle   = -7.0;
  float  RightEndAngle  =  7.0;
  float  TopEndAngle    =  -7.0;
  float  BottomEndAngle =  7.0;
}

class CTankPzVITigerE1_EarlyEngineSystem
{
  float    MaxPower      = 3600.0f; // maximum horse power
  float    MinPower      = 2000.0;
  float    MinSpeed      = 800.0;   // minimum RPM
  float    MaxSpeed      = 2700.0;  // maximum RPM
  float    RunningTime   = 1.0;     // starter working time, sec

  int AutoDriverLowRPMGear  = 1200;
  int AutoDriverHighRPMGear = 2650;
  int AutoDriverGearForRotation = 3;   //   3

  float AutoDriverAngleDelta = 6.00f;   //5.0f
  float AutoDriverSpeedDelta = 3.0f;    //1.5f
  float AutoDriverMaxAngle   = 0.2f;  //0.1f
  float AutoDriverAnglePower = 8.3f;  // 0.3f

                                   /*                   R1    N     I     II    III   IV      V     VI    VII    VIII   IX      X   23.0f, 25.0f,  */
  Array   GearsSwitchMinSpeed = [ -1.0f, 0.0f, 2.5f, 3.5f, 8.0f, 16.0f, 19.0f, 28.0f, 30.0f, 35.0f];

  float    EngineFriction = 1.0;

  static Component EventHandler;


  boolean  TwoTracksRotation = true; // Possibility to turn ????????
  boolean  PlayReverseGearAnimation = false; //To lose for animation of return of the handle of transfers to initial value    CTankPzVITigerE1_Early

  Array    GearNames     = [ L"R1", L"N", L"G1", L"G2", L"G3", L"G4", L"G5", L"G6", L"G7", L"High"];

 //Transmission capacity ч utilization rate  Factor    Factor   capacity   capacity.             sound of the engine                  reverse    animation animation
  //                      before ч sine     *two.    Off*two. Lowerings  повышени
  //                                                              Turns   Turns

  Array    Gears         = [
                            // [  -0.07,     80000.0,  18000.0,      0.1,      0.5,     new #Emitter<CTankPzVIAusfE_Gear04Sound>(), new #LineAnimator<CTankPzVIAusfEGear4Animator>(), true],
                            // [  -0.06,     80000.0,  18000.0,      0.1,      0.5,     new #Emitter<CTankPzVIAusfE_Gear03Sound>(), new #LineAnimator<CTankPzVIAusfEGear3Animator>(), true],
                             //[  -0.05,     80000.0,  18000.0,      0.1,      0.5,     new #Emitter<CTankPzVIAusfE_Gear02Sound>(), new #LineAnimator<CTankPzVIAusfEGear2Animator>(), true],
                             [  -0.06,     80000.0,  18000.0,      0.1,      0.5,     new #Emitter<CTankPzVIAusfE_Gear01Sound>(), 0, true],
                             [   0.00,     1500.0,    1500.0,      0.5,      0.5,     new #Emitter<CTankPzVIAusfE_IdleSound>(), new #LineAnimator<CTankPzVIAusfEGearReverseAnimator>(), true ],
                             [   0.05,     80000.0,  18000.0,      1.6,      0.5,     new #Emitter<CTankPzVIAusfE_Gear01Sound>(), new #LineAnimator<CTankPzVIAusfEGearNormalAnimator>() ],
                             [   0.09,     70000.0,  18000.0,      2.0,      0.5,     new #Emitter<CTankPzVIAusfE_Gear02Sound>(), new #LineAnimator<CTankPzVIAusfEGear2Animator>() ],
                             [   0.12,     60000.0,  18000.0,      3.0,      0.5,     new #Emitter<CTankPzVIAusfE_Gear03Sound>(), new #LineAnimator<CTankPzVIAusfEGear3Animator>() ],
                             [   0.16,     20000.0,  12500.0,      5.0,      0.5,     new #Emitter<CTankPzVIAusfE_Gear04Sound>(), new #LineAnimator<CTankPzVIAusfEGear4Animator>() ],
                             [   0.20,     12500.0,  11500.0,      6.5,      0.5,     new #Emitter<CTankPzVIAusfE_Gear05Sound>(), new #LineAnimator<CTankPzVIAusfEGear5Animator>() ],
                             [   0.30,     11500.0,  10500.0,      7.0,      0.5,     new #Emitter<CTankPzVIAusfE_Gear06Sound>(), new #LineAnimator<CTankPzVIAusfEGear6Animator>() ],
                             [   0.40,     10500.0,   9500.0,      8.0,      0.5,     new #Emitter<CTankPzVIAusfE_Gear07Sound>(), new #LineAnimator<CTankPzVIAusfEGear7Animator>() ],
                             [   0.50,      9500.0,   8000.0,      9.0,      0.5,     new #Emitter<CTankPzVIAusfE_Gear08Sound>(), new #LineAnimator<CTankPzVIAusfEGear7Animator>() ]
                           ];

  // power of engine by speed if brake is enable for single track or both tracks
  //                          Speed  Power
  Array     BrakePower   = [
                             [ 0.0,  48000.0, 10.0, 9500.0 ],
                             [
                               [ 0.5, 19000.0 ],
                               [ 2.0, 14000.0 ],
                               [ 3.0, 9500.0 ],
                               [ 5.0, 9500.0 ],
                               [ 6.0, 9500.0 ]
                             ]
                           ];


  // power for hand brake by speed
  Array     HBrakePower  = [
                             [ 0.0,  17000.0, 7.0, 10000.0 ]
                           ];
 
  Component GearOnSnd    = new #Emitter<CTankPzVIAusfE_GearOnSound>();
  Component StartEng     = new #Emitter<CTankPzVIAusfE_StartEngineSound>();
  Component StopEng      = new #Emitter<CTankPzVIAusfE_StopEngineSound>();
  Component StarterSnd   = new #Emitter<CTankPzVIAusfE_StarterEngineSound>();
  Component DieSnd       = new #Emitter<CTankPzVIAusfE_EngineDieSound>();

  Component AccelerationAnimator = new #LineAnimator<CTankPzVITigerE1_EarlyAccelerationAnimator>();
  Component LeftClutchAnimator   = new #LineAnimator<CTankPzVITigerE1_EarlyLeftClutchAnimator>();
  Component RightClutchAnimator  = new #LineAnimator<CTankPzVITigerE1_EarlyRightClutchAnimator>(); 
  Component BreakAnimator        = new #LineAnimator<CTankPzVITigerE1_EarlyBreakAnimator>(); /**/

  float     BeginEngineSoundFreq   = 0.3;//0.364;
  float     EngineSpeedScaleCoeff  = 1.0 / 2250.0 ; // ;  // 3000.0
  float     VehicleSpeedScaleCoeff = 1.0/ 2250.0 ;    // 3000.0

}

//
// Describe wheel types
//

class CTankPzVITigerE1_EarlyMainWheel
{
  float  Mass        = 800.0;
  Vector IT          = new Vector(0.109212, 0.109212, 0.107521);
  float  Elasticity  = 0.06;
  float  Friction    = FLT_MAX;      //   1.0
  float  Friction1   = 1.0;
}
class CTankPzVITigerE1_EarlyManualControl
  extends CBaseManualControl
{
  // =========================================
  // Tank properties
  // =========================================

  float  Mass                 = 56000.0;
  Vector IT                   = new Vector(0.874482, 3.152529, 3.804275);
  float  Elasticity           = 0.80;
  float  Friction             = 2.5;
  float  SuspensionHeight = 0.200;    // cm
  float  SuspensionPower  = 6000.0;  // kg
  Vector GravityAccelerate    = new Vector(0.0, 0.0, -3.5);

/*    // angular damping coefficients by axises X, Y and Z
  Vector AngularDampingCoeff  = new Vector(0.0, 0.0, 1.0);
  // linear damping coefficients by axises X, Y and Z
  Vector LinearDampingCoeff   = new Vector(2.4, 2.4, 1.6);  */
  Vector AngularDampingCoeff  = new Vector(0.0, 0.0, 0.3);
  // linear damping coefficients by axises X, Y and Z
  Vector LinearDampingCoeff   = new Vector(0.3, 0.3, 0.6);  /**/
  Array  Wheels               = [

                                  // Left side

                                  [ "WheelLeftMain1_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelLeftMain2_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelLeftMain3_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelLeftMain4_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelLeftMain5_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelLeftMain6_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelLeftMain7_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelLeftMain8_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],

                                  // Right side

                                  [ "WheelRightMain1_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelRightMain2_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelRightMain3_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelRightMain4_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelRightMain5_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelRightMain6_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelRightMain7_CS", new CTankPzVITigerE1_EarlyMainWheel()  ],
                                  [ "WheelRightMain8_CS", new CTankPzVITigerE1_EarlyMainWheel()  ]

                                ];
 
  // =========================================
  // Other systems
  // =========================================

  Component EngineSystem      = new CTankPzVITigerE1_EarlyEngineSystem();   //

  // =========================================
  // Sounds
  // =========================================


  Component LeftTrackSound    = new #Emitter<CTankPzVIAusfE_TrackSound>();
  Component RightTrackSound   = new #Emitter<CTankPzVIAusfE_TrackSound>();

  float  BeginTrackSoundFreq  = 0.25; //
  float  TrackSpeedScaleCoeff = 1.0 / 12000.0; //
}

// Track animator
class CTankPzVITigerE1_EarlyBaseTrack
{
  String  JointName           = "";
  String  TrackTexName        = "";
  String  WheelAnimName       = "";

  Array   TrackTexScrollScale = [0.0, -0.20];//[0.0, -0.4];
  float   WheelRotateScale    = 0.03;
  float   RealTrackPathScale  = 2.0f;
  boolean IsLeftTrack;

  float   WheelRadius         = 0.415 + 0.085; //0.413 + 0.072 whell radius + track radius
  float   WhellLiftDown       = 0.150;  //       // max down wheel offset
  float   WhellLiftUp         = 0.150;   //      // max up wheel offset

   float   TrackSoft           = 0.6; //

  // Collision mask [restrict], [exclude]
  Array   CollisionMask = [[ CLASSIFICATOR_WALK_SURFACE], [CLASSIFICATOR_COLLISION_SHAPES]];// здесь exclude используется не как исключающий, а как дополнительный
}

class CTankPzVITigerE1_EarlyLeftTrack
  extends CTankPzVITigerE1_EarlyBaseTrack
{
  String  JointName     = "TrackLeft";
  String  TrackTexName        = "Textures/u_veh_TigerE1_Track_Lft.tex";
  String  WheelAnimName = "wheels_left";

  boolean IsLeftTrack = true;

  Array   WhellsAnimation =
  [
    // joint name,            animation name,            down    up
    //
    ["WheelLeftMain1", "L_Wheel01_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain2", "L_Wheel02_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain3", "L_Wheel03_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain4", "L_Wheel04_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain5", "L_Wheel05_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain6", "L_Wheel06_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain7", "L_Wheel07_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelLeftMain8", "L_Wheel08_lift", WhellLiftDown, WhellLiftUp, WheelRadius]
  ];
}

class CTankPzVITigerE1_EarlyRightTrack
  extends CTankPzVITigerE1_EarlyBaseTrack
{
  String  JointName     = "TrackRight";
  String  TrackTexName        = "Textures/u_veh_TigerE1_Track_RT.tex";
  String  WheelAnimName = "wheels_right";
  boolean IsLeftTrack   = false;

  Array   WhellsAnimation =
  [
    // joint name,            animation name,            down    up
    //
    ["WheelRightMain1", "R_Wheel01_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain2", "R_Wheel02_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain3", "R_Wheel03_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain4", "R_Wheel04_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain5", "R_Wheel05_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain6", "R_Wheel06_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain7", "R_Wheel07_lift", WhellLiftDown, WhellLiftUp, WheelRadius],
    ["WheelRightMain8", "R_Wheel08_lift", WhellLiftDown, WhellLiftUp, WheelRadius]
  ];
}


 //Turret out animator
   class CTankPzVITigerE1_EarlyTurretOutAnimator1
{
  String AnimationName = "turret_out1";
  float  AnimationTime = 0.5;
};


// Fire Animator
class CTankPzVITigerE1_EarlyFireAnimation
{
  final static String  AnimationName     = "gun_a_recoil";
  final static float   AnimationTime     = 1.0;
}

class CTankPzVITigerE1_EarlyHatchBodyAnimator
{
  String AnimationName = "block_open";
  float  AnimationTime = 1.0;
}
class CTankPzVITigerE1_EarlyHatchCommanderAnimator
{
  String AnimationName = "luk_main_open";
  float  AnimationTime = 2.0;
}

//luk commander animator
class CTankPzVITigerE1_EarlyCommanderOutAnimator
{
  String AnimationName = "luk_main_commander";
  float  AnimationTime = 2.0;
}

// Inside animations
class CTankPzVITigerE1_EarlyOilPressAnimator
{
  String AnimationName = "oil_pressure";
  float  AnimationTime = 1.0;
}

/*class CTankT34_85_44OilTempAnimator
{
  String AnimationName = "oil_temperature";
  float  AnimationTime = 1.0;
}
  */
class CTankPzVITigerE1_EarlyWaterTempAnimator
{
  String AnimationName = "water_temperature";
  float  AnimationTime = 1.0;
}

class CTankPzVITigerE1_EarlyAccelerationAnimator
{
  String AnimationName = "acceleration";
  float  AnimationTime = 1.0;
}
class CTankPzVITigerE1_EarlyTachometerAnimator
{
  String AnimationName = "tacho";
  float  AnimationTime = 1.0;
}
class CTankPzVITigerE1_EarlySpeedometerAnimator
{
  String AnimationName = "speed";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyLeftClutchAnimator
{
  String AnimationName = "left_side_clutch";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyRightClutchAnimator
{
  String AnimationName = "right_side_clutch";
  float  AnimationTime = 0.5;
}
//Gears animators 
class CTankPzVITigerE1_EarlyGearNormalAnimator
{
  String AnimationName = "direction_normal";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyGearReverseAnimator
{
  String AnimationName = "direction_reverse";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyGear2Animator
{
  String AnimationName = "gear_2";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyGear3Animator
{
  String AnimationName = "gear_3";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyGear4Animator
{
  String AnimationName = "gear_4";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyGear5Animator
{
  String AnimationName = "gear_5";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyGear6Animator
{
  String AnimationName = "gear_6";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyGear7Animator
{
  String AnimationName = "gear_7";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyBreakAnimator
{
  String AnimationName = "mountain_brake";
  float  AnimationTime = 0.5;
}
class CTankPzVITigerE1_EarlyCourse
{
  String AnimationName = "course_2";
  float  AnimationTime = 1.0;
}
// Behavior
class CTankPzVITigerE1_EarlyBehaviorParams extends CBaseBehaviorParams
{
  float   MaxAttackSpeed     = 3.0;
  float   CollisionAddRadius = 8.0;
}

class CTankPzVITigerE1_EarlyBehavior extends CBaseTankBehavior
{
  final static Component SpecParams = new CTankPzVITigerE1_EarlyBehaviorParams();

  Array EnemyRankDangerByDistance =  [
                                       [[ ["HEAVYTANK"],["AIR"] ], [ [ 0.0, 200.0, 1500.0, 100.0 ], [ [400.0, 150.0] ] ] ],
                                       [[ ["TANK"],["AIR"] ],      [ [ 0.0, 150.0, 1500.0, 100.0 ], [ [400.0, 140.0] ] ] ], // [ Mask, PiercLinFunctionByDist]
                                       [[ ["ANTITANK"],["AIR"] ],  [ [ 0.0, 150.0, 1500.0, 95.0 ], [ [400.0, 130.0] ] ] ],
                                       [[ ["BTR"],["AIR"] ],       [ [ 0.0, 130.0, 1500.0, 30.0 ], [ [400.0, 125.0] ] ] ],
                                       [[ ["BLD_WAR"],["AIR"] ],   [ [ 0.0, 100.0, 1500.0, 35.0 ], [ [400.0,  80.0] ] ] ],
                                       [[ ["VEHICLE"],["AIR"] ],   [ [ 0.0,  10.0, 1500.0, 5.0 ],  [ [400.0,  10.0] ] ] ],
                                       [[ ["HUMAN"],["AIR"] ],     [ [ 0.0,  35.0, 1500.0, 2.0 ],  [ [400.0,   5.0] ] ] ],
                                       [[ ["AIR"],[] ],            [ [ 0.0,   0.0, 1500.0, 0.0 ],  [ [400.0,   0.0] ] ] ]
                                     ]; // default Rank = distance if object not fit any mask

  int      AttackStyle        = AttackStyle_LightTank;  //;AttackStyle_LazyTank  //AttackStyle_Tank;
  boolean  CanMove            = true;
  boolean  HasRouter          = false;
  boolean  HasRadar           = true;

  float   MinRotateRadius = 0; // unit can turn when staying
  float   AttackDistanceMin = 20.0;
  float   AttackDistanceMax = 2600.0;

  // *** radar parameters

  float MaxRadarDistance = 2800.0; // m     // tweaked from 3.5 11-11-08
  float MinRadarDistance = 50.0;    // m
  float MaxRadarAngle    = 180.0;

  int    UpdateRadarPeriod        = 3000; // ms
  int    UpdateRadarPeriodRandAdd = 1000; // ms

  // *** movement physical parameters

  // physical limitations
  float   MaxRotateSpeed                = 0.25f;
  Vector  MaxSpeed                      = new Vector( 6.6, 0, 0);   // m/s
  Vector  MaxNegativeSpeed              = new Vector( 3.5, 0, 0);   // m/s
  Vector  MaxAccelleration              = new Vector( 0.6, 0, 0);    // m/(s*s)
  Vector  MaxNegativeAccelleration      = new Vector( 0.2, 0, 0);  // m/(s*s)
  Vector  MaxBrakingAccelleration       = new Vector( 1.0, 0, 0);   // m/(s*s)
  Vector  MaxAngleSpeed                 = new Vector(   0, 0, 1.0);    // [rad/s]
  Vector  MaxAngleAccelleration         = new Vector(   0, 0, 0.8);  // [rad/(s*s)]
  Vector  MaxAngleBrakingAccelleration  = new Vector(   0, 0, 2.0); //1);  // [rad/(s*s)]

}

// ================================================
// Device classes
// ================================================

class CTankPzVITigerE1_EarlyHullDriverDevice
  extends CHullDriverDevice
{
  String m_NormalSetId  = "";//"Body_NormalSet";
  String m_CrashedSetId = "";//"Body_CrashedSet";

  void HullDriverDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 10);
    }
  }

  void HullDriverDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 0);
    }

  }
}

class CTankPzVITigerE1_EarlyHullGunlayerDevice
  extends CHullGunlayerDevice
{
  String m_NormalSetId  = "Body_NormalSet";
  String m_CrashedSetId = "Body_CrashedSet";

  Vector TurretOutForceMin  = new Vector(0.0, 0.0, 2.0);
  Vector TurretOutForceMax  = new Vector(0.0, 0.0, 5.0);
  float  TurretOutForceThetaMin  = 25;
  float  TurretOutForceThetaMax  = 35;
  Vector TurretOutRadiusMin = new Vector(0.5, 0.5, 1.0);
  Vector TurretOutRadiusMax = new Vector(1.0, 3.0, 8.0);

  void HullGunlayerDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 15);
    }
  }

  void HullGunlayerDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 0);
      Behavior.SetFireAbility(false, 0);
      Behavior.SetAimAbility(false,0);
    }


    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      if ((1 == randnum(2)) || CPiercing::TankPzVIAusfEAlwaysDestroyTrack)
        StateControl.SetDelayItemHP(_HostObject.GetItem("TrackLeft").Index, 0.0, 0);

      if ((1 == randnum(2)) || CPiercing::TankPzVIAusfEAlwaysDestroyTrack)
        StateControl.SetDelayItemHP(_HostObject.GetItem("TrackRight").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("HullDriver").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("HullEngine").Index, 0.0, 0);

      StateControl.SetDelayItemHP(_HostObject.GetItem("Turret_A").Index, 0.0, 0);

//      StateControl.SetHitPoints(0.0);
    }

  }
}

class CTankPzVITigerE1_EarlyHullEngineDevice
  extends CHullEngineDevice  //
{
  String m_NormalSetId  = "";//"Body_NormalSet";
  String m_CrashedSetId = "";//"Body_CrashedSet";

  void HullEngineDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 30);
    }
  }

  void HullEngineDeviceDestroyed(Component _HostObject)
  {
    clearEventsForObject(getIdentificator(_HostObject));

    Component IdleSound = _HostObject.GetObject("IdleSound");
    if (IdleSound != null)
    {
      IdleSound.StopSoundPlaying(true);
    }

    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      // Change Item hit points after delay in N seconds. SetDelayItemHP(ItemIndex, HitPoints, Time)
      StateControl.SetDelayItemHP(_HostObject.GetItem("HullGunlayer").Index, 0.0, 15+randnum(15));
      StateControl.SetHitPoints(0.0);
    }

  }
}

class CTankPzVITigerE1_EarlyTrackLeftDevice
  extends CTrackLeftDevice
{
//  String m_NormalSetId  = "TrackLeft_NormalSet";
//  String m_CrashedSetId = "TrackLeft_CrashedSet";

  void TrackLeftDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(1.5f);
      Behavior.SetMoveAbility(false, 10);
    }
  }

  void TrackLeftDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(1.5f);
      Behavior.SetMoveAbility(false, 0);
      //Behavior.ActivateMovement(false);
    }
  }
}

class CTankPzVITigerE1_EarlyTrackRightDevice
  extends CTrackRightDevice
{
//  String m_NormalSetId  = "TrackRight_NormalSet";
//  String m_CrashedSetId = "TrackRight_CrashedSet";

  void TrackRightDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(-1.5f);
      Behavior.SetMoveAbility(false, 10);
    }
  }

  void TrackRightDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetBrakeAngle(-1.5f);
      Behavior.SetMoveAbility(false, 0);
      //Behavior.ActivateMovement(false);
    }
  }
}

class CTankPzVITigerE1_EarlyTurretDevice
  extends CTurretDevice
{
  String m_NormalSetId  = "Turret_A_NormalSet";//
  String m_CrashedSetId = "Turret_A_CrashedSet"; //

  Vector TurretOutForceMin  = new Vector(3.0, 0.0, 4.0);
  Vector TurretOutForceMax  = new Vector(-3.0, 2.0, 6.0);
  Vector TurretOutRadiusMin = new Vector(0.5, 0.5, 0.5);
  Vector TurretOutRadiusMax = new Vector(1.0, 3.0, 2.5);
/**/  

  void TurretDeviceDamaged(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetMoveAbility(false, 60);
      Behavior.SetAimAbility(false, 30);
    }
  }

  void TurretDeviceDestroyed(Component _HostObject)
  {
    Component Behavior = _HostObject.GetObject("Behavior");
    if (Behavior != null)
    {
      Behavior.SetFireAbility(false, 0);
      Behavior.SetAimAbility(false, 0);
      Behavior.SetMoveAbility(false, 0);
    }

    Component IdleSound = _HostObject.GetObject("IdleSound");
    if (IdleSound != null)
    {
      IdleSound.StopSoundPlaying(true);
    }

    Component StateControl = _HostObject.GetObject("StateControl");
    if (StateControl != null)
    {
      StateControl.SetHitPoints(0.0);
    }

   }
 }

class CTankPzVITigerE1_EarlyRecoilController
{
  String FToBAnim   = "body_recoil_fb";
  String BToFAnim   = "body_recoil_bf";
  String RToLAnim   = "body_recoil_rl";
  String LToRAnim   = "body_recoil_lr";
  float  RecoilTime = 1.0;
};

class CTankPzVITigerE1_EarlyTurretSubstance
  extends CMetalSubstance
{
  Vector MainFrictionAxis = new Vector(0.0, 0.0, 1.0);
  float  Friction         = 0.5;
  float  Friction1        = 0.9;
  float  Elasticity       = 0.2;
}

class CTankPzVITigerE1_EarlySubstance
  extends CMetalSubstance
{
  Vector MainFrictionAxis = new Vector(1.0, 0.0, 0.0);
  float  Friction         = 1.2;
  float  Friction1        = 0.2;
  float  Elasticity       = 0.3;
}

// ================================================
// Unit class 1
// ================================================

class CTankPzVITigerE1_EarlyUnit
    extends CGerTankPlayerUnit,CWeaponConfig, CPushVehicleObject  //
{
  final static String DefaultHealthParameter = "HP_HEALTHY";  // fragile constitution
  // Automatic classificators of this object
  final static Array AutomaticClassificators  = ["GROUND", "HEAVYTANK", "GER"];
  final static float DefaultHitPoints = CHitPoints::TankPzVIAusfEUnitHitPoints;

  boolean m_flag = false;

  final static boolean DefaultSetFlagMode       = false;

  final static boolean DefaultSetWinterMode     = false; //

  static category UnitType = CLASSIFICATOR_T34_HEAVY_TANK;

  static Array PostExplosionID = [
                                    ["", "TankPzVIAusfExplosion"]
                                 ];

  static Array Hatches = [
                            [ "BLC_Driver",    "block_open",         1.0 ],
                            [ "Luk_Driver",    "luk_body_open",      1.0 ], //
                            [ "Luk_Commander", "luk_main_open",      2.0 ],
                            [ "Commander",  "luk_main_commander", 2.0 ]
                         ];

                                                                        

  static Array HatchesStates = [
                                  [ "Normal", [ [ "BLC_Driver", 0.0 ],[ "Luk_Driver", 1.0 ], [ "Luk_Commander", 1.0 ], [ "Commander", 1.0 ] ] ],
                                  [ "Attack", [ [ "BLC_Driver", 1.0 ],[ "Luk_Driver", 0.0 ], [ "Luk_Commander", 0.0 ], [ "Commander", 0.0 ] ] ]
                               ];

  final static String BodyJoint   = "Body";

  final static String DefaultSurfaceControl = "PutonGroundLandingJoints";      // LandingJoints
  final static Array  LandingJoints         = ["Corner_FL", "Corner_RL", "Corner_RR", "Corner_FR"];

  static Array  SubstanceArmourWidth = [
                                         [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                                         [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                                         [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                                         [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                                         [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                                         [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                                         [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                                         [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                                         [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                                         [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                                         [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                                      ];

   Array m_DamageTransfer = [ // From Item , To Item, Item HitPoints Percent
                             ["HullDriver", "HullEngine", 0.2f],
                             ["HullDriver", "HullGunlayer", 0.2f]
                             ];


  // Camera parameters
  float MinHorAngle  = -1.475; //  360' -3.141592 was     -0.43
  float MaxHorAngle  =  1.475; // was 0.43
  float MinVertAngle = -1.30; // was      -0.75
  float MaxVertAngle =  0.43;  // 60' 1.047199
/* */
   // Critical Engine Speed
  float m_CriticalEngineSpeed1 = 2680.0;
  float m_TempIncreaseCoeff1   = 0.01;
  float m_CriticalEngineSpeed2 = 2690.0;
  float m_TempIncreaseCoeff2   = 0.1;
  float m_CriticalEngineSpeed3 = 2700.0;
  float m_TempIncreaseCoeff3   = 0.2;

  float m_CriticalWaterTemp = 115.0f;
  float m_CriticalOilTemp   = 100.0f;

  boolean m_AITankCollisionShape = true;

 int     m_CockpitStyle         = CS_Tiger;     //

  float   m_RepairTime = 20.0f;
  boolean m_ReadyToRepair = true;

  // =======================================
  // Contruction and initialization
  // =======================================

  void CTankPzVITigerE1_EarlyUnit()
  {

    SetupExtendMesh("Cu_veh_TIGER_E1_Early_PlayableModel", "Cu_veh_PzVI_MAIN_InsideModel");
    GetMeshComponent().SetLods([0]); // ,120,80,60,40

    // Setup trucks
    SetupTracks(
      new #TrackAnimator<CTankPzVITigerE1_EarlyLeftTrack>(),
      new #TrackAnimator<CTankPzVITigerE1_EarlyRightTrack>()
    );

    SetGunRecoilEffects(new #LineAnimator<CTankPzVITigerE1_EarlyFireAnimation>());

    SetHatchBodyEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchBodyAnimator>());
    SetHatchCommanderEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchCommanderAnimator>(),
                             new #LineAnimator<CTankPzVITigerE1_EarlyCommanderOutAnimator>());

    SetHideInCockpitJoints(["Body_commander", "HullDriver"]);

    SetCockpitDevice("TachometerAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyTachometerAnimator>(), 3600.0f, 0.0f);
    SetCockpitDevice("SpeedAnimator", new #LineAnimator<CTankPzVITigerE1_EarlySpeedometerAnimator>(), 80.88f, 0.0f);              
    SetCockpitDevice("OilPressureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyOilPressAnimator>(), 18.0f, 0.0f);
    SetCockpitDevice("WaterTemperatureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyWaterTempAnimator>(), 125.0f, 0.0f);

  // Setup turret out animator
   // SetTurretOutEffectsArray( TurretOutAnimations );

  }


  void Construct(
      Component _Mission,
      Component _PropMap
    )
  {


    if (_PropMap.Get("IsManual", false))  //
   {                                    //

      EnableSurfaceControl(false);

      SetEngineComponents(
          [
          [ "Smoke_L", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect",      "Engine"     ],
          [ "Smoke_L", "TigerEngineSmokeEffect",      "Engine"     ]
          ]
        );

      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyPlayerGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null );  // new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      Component Game = new #GameController();
      boolean IsMirror = _PropMap.Get("IsMirror", (Game.GetGameMode() == "Client"));
      if (IsMirror)
        SetIdleEffects(new #Emitter<CTankPzVIAusfEIdleSound>());

        boolean isAutoShooter = true;
        if(isFunctionExist(_Mission, "IsExpertMode", 0))
            isAutoShooter = !_Mission.IsExpertMode();
        if(isAutoShooter && !IsMirror )
        {
          Component AutoShooter = new #AutoShooter<CAutoShooter>();
          setSlaveObject( AutoShooter, this );
          AutoShooter.SetMachineGun( GetObject( "Weapon_B" ) );
          AutoShooter.SetMainGun( GetObject( "Weapon_A" ) );
          AutoShooter.SetEventHandler(this);
          AutoShooter.Enable(true);
          AutoShooter.SetUnitPriority(CUnitType::UnitPriority);
          RegisterObject( "AutoShooter", AutoShooter );
        }
           // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );



      SetAccelEffects(
          new #Emitter<CTankPzIVGAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );
        



    }
    else
    {
      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null ); //  new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      SetupBehavior( new #VehicleBehavior<CTankPzVITigerE1_EarlyBehavior>());


      Component hatches = new #HatchesStateController();
      hatches.AddHatches( Hatches );
      hatches.AddStates( HatchesStates );
      SetupHatches( hatches );
      hatches.SetHatchesState( "Normal" );

    // Creates and register unit state component
    // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      SetIdleEffects(
          new #Emitter<CTankPzVIAusfE_IdleSound>()
        );

      SetAccelEffects(
          new #Emitter<CTankPzVIAusfEAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      GetLeftTrack().EnableAutoCalcPath(true);
      GetRightTrack().EnableAutoCalcPath(true);

    }

    CPlayerUnit::Construct(_Mission, _PropMap);

    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET762792, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET127, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_SUBCALIBREBULLET7576, 0.4);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET7576, 0.2);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BUILDING, 0.0);

    // create effects for tracks: [ HostId, Effectid, ZoneId ]
    SetTrackEffects(
        _Mission,
        [
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ]
        ]
      );

    CreateUnitItem(
        "HullDriver",
        CJointPoints::TankPzVIAusfEUnitHULL_DRIVERPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "HullDriver"
      );
    CreateUnitItem(
        "HullGunlayer",
        CJointPoints::TankPzVIAusfEUnitHULL_GUNLAYERPoints,
        ["GenericDamageItemEffect", "HullGunLayerExplosionEffect"],
        "HullGunlayer"
      );
    CreateUnitItem(
        "HullEngine",
        CJointPoints::TankPzVIAusfEUnitHULL_ENGINEPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "HullEngine"
      );
    CreateUnitItem(
        "TrackLeft",
        CJointPoints::TankPzVIAusfEUnitTRACK_LEFTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackLeft"
      );
    CreateUnitItem(
        "TrackRight",
        CJointPoints::TankPzVIAusfEUnitTRACK_RIGHTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackRight"
      );
    CreateUnitItem(
        "Turret_A",
        CJointPoints::TankPzVIAusfEUnitTURRETPoints,
        ["GenericDamageItemEffect", "GenericLargeFirePostSmokeRefuseEffect"],
      //  ["Turret_A_Crashed", "Turret_A_Crashed"],
        "Turret_A"
      );

    GetObject("Weapon_A").SetFireAnimator(GetObject("GunRecoilAnimator"));
    //logWarning("Weapon fire deviation for " + getIdentificator(this) + "=" + new String(GetObject("Weapon_A").FireDeviation));

    LinkDeviceToUnitItem("HullDriver",   new CTankPzVITigerE1_EarlyHullDriverDevice());
    LinkDeviceToUnitItem("HullGunlayer", new CTankPzVITigerE1_EarlyHullGunlayerDevice());
    LinkDeviceToUnitItem("HullEngine",   new CTankPzVITigerE1_EarlyHullEngineDevice());
    LinkDeviceToUnitItem("TrackLeft",    new CTankPzVITigerE1_EarlyTrackLeftDevice());
    LinkDeviceToUnitItem("TrackRight",   new CTankPzVITigerE1_EarlyTrackRightDevice());
    LinkDeviceToUnitItem("Turret_A",     new CTankPzVITigerE1_EarlyTurretDevice());

    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));

    SetupRecoilController(new #RecoilController<CTankPzVITigerE1_EarlyRecoilController>());

    if ((new #GameController()).GetGameMode() != "Single")            // != "Single")
       GetObject("Mesh").SetAnimateAlways(true);

    if (!_PropMap.Get("IsManual", false))
      SetupPhysicaleObject("CTankPzVITigerE1_EarlySubstance", 60000.0, 0.0);


    if (_PropMap.Get("IsManual", false))
    {
      GetObject("VoiceMessenger").AddSoundTable(CCockpit::TigerVoices);
      SetAngleMessages(CCockpit::GermanAngleMessages);
      m_TargetDirection = [[L"", ""],[L"", ""]];

      Component PointDetector = new #PointCollisionDetector();
      PointDetector.EnableDetector(true);
      PointDetector.SetCollisionMask([CLASSIFICATOR_TERRAIN, CLASSIFICATOR_GROUND, CLASSIFICATOR_TERRAINFOREST],[]);
      PointDetector.SetEventHandler(this);
      setPositionable(PointDetector, GetMeshComponent());
      RegisterObject("PointDetector", PointDetector); /* */
    }

 }
  // =======================================
  // Collision control
  // =======================================

  Component CreateCollisionControl(String _ScriptClassName)
  {
    Component CollisionControl = new #CollisionControl2();
    CollisionControl.SetCollisionMask(
        [ CLASSIFICATOR_WALK_SURFACE ],
        [ CLASSIFICATOR_DO_NOT_COLLISION_CHECK, CLASSIFICATOR_PHYSICS_CONTROLLABLE ]
       );

    loadFromScript(CollisionControl, _ScriptClassName);
    RegisterObject("CollisionControl", CollisionControl);

    return CollisionControl;
  }

  void Initialize(
      Component   _Mission,
      Component   _PropMap
    )
  {
    CPlayerUnit::Initialize(_Mission, _PropMap);
     // Put on ground tank object
    boolean IsManual = _PropMap.Get("IsManual", false);
    if (IsManual)
    {
      LinkModel();
      PutonGround();
      EnableSurfaceControl(false);
      UnlinkModel();

    }

 }

  void SetFlagMode(
      boolean _Enable
    )
  {
    if (_Enable)
    {
     setVisibleState(GetMeshComponent().GetJoint("Flag"), true);
     }
    else
      setVisibleState(GetMeshComponent().GetJoint("Flag"), false);
   }

  // ======================================
  // Vehicle controller
  // ======================================
  Component CreateVehicleController()
  {
   
  CTankPzVITigerE1_EarlyEngineSystem::EventHandler = this;      //
  return (new #TankVehicle<CTankPzVITigerE1_EarlyManualControl>());

  }

  // ======================================
  // AI Vehicle controller
  // ======================================
  Component CreateAIVehicleController()
  {
    return (new #AITankVehicle<CTankPzVITigerE1_EarlyManualControl>());
  }

  // ======================================
  // Manual control
  // ======================================
  Component CreateManualControl()
  {
    return new #ManualTankControl();
  }

  // ======================================
  // Armour descriptor
  // ======================================
  Array GetArmourDescriptor()
  {
    return new Array ([
                        [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                        [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                        [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                        [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                        [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                        [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                        [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                        [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                        [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                        [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                        [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                      ]);
  }

  event void ReadyToRepair()
  {
    m_ReadyToRepair = true;
  }

  event void ReloadAmmo()
  {

    if (!checkMask(this, [], [CLASSIFICATOR_DEAD_OBJECT]) || !m_ReadyToRepair)
      return;

    Component AutoThingsUI = GetObject("AutoThingsUI");
    if ( AutoThingsUI == null )
      return;

    if (AutoThingsUI.IsHandbrakeActive())
    {
      m_ReadyToRepair = false;
      sendEvent(m_RepairTime, getIdentificator(this), "ReadyToRepair", []);

      Component Weapon = GetObject("Weapon_A");
      Weapon.SetAmmoQuantity(0, CTankPzVITigerE1_EarlyCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(1, CTankPzVITigerE1_EarlySubCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(2, CTankPzVITigerE1_EarlyHEAmmoPlayer::Ammunition);

      Component StateControl = GetStateControl();
      for (int i = 0; i < m_UnitItemsList.size(); i++)
      {
        Component Item = m_UnitItemsList[i];
        StateControl.SetUnitItemHP(Item.Index, Item.HitPoints);
        Item.CurrentHitPoints = Item.HitPoints;
      }
    }
  }

  // ======================================
  // Point collision detector
  // ======================================

  // Call when tank deep in the water (Вызывается, когда танк глубоко заехал в воду)
  event void OnPointCollisionDetect(String _ObjectID)
  {
    // Destroy HullEngine may be changed (убиваем движок, можно заменить на что-то другое)
    SetUnitItemHPPercent("HullEngine", 0.0);
    
    GetObject("PointDetector").EnableDetector(false);
  }


  event void SetModelViewState(
      boolean _State
    )
  {
    // TMP
  }

}
// ================================================
// Unit class 2 PanzerGray + Dunkelgleb
// ================================================

class CTankPzVITigerE1_EarlyIIUnit
    extends CGerTankPlayerUnit,CWeaponConfig, CPushVehicleObject  //
{ 
  final static String DefaultHealthParameter = "HP_HEALTHY";  // fragile constitution
    // Automatic classificators of this object
  final static Array AutomaticClassificators  = ["GROUND", "HEAVYTANK", "GER"];
  final static float DefaultHitPoints = CHitPoints::TankPzVIAusfEUnitHitPoints;

  boolean m_flag = false;



  final static boolean DefaultSetFlagMode       = false;

  final static boolean DefaultSetWinterMode     = false; //

  static category UnitType = CLASSIFICATOR_T34_HEAVY_TANK;

  static Array PostExplosionID = [
                                    ["", "TankPzVIAusfExplosion"]
                                 ];

  static Array Hatches = [
                            [ "BLC_Driver",    "block_open",         1.0 ],
                            [ "Luk_Driver",    "luk_body_open",      1.0 ], //
                            [ "Luk_Commander", "luk_main_open",      2.0 ],
                            [ "Commander",  "luk_main_commander", 2.0 ]
                         ];

                                                                        

  static Array HatchesStates = [
                                  [ "Normal", [ [ "BLC_Driver", 0.0 ],[ "Luk_Driver", 1.0 ], [ "Luk_Commander", 1.0 ], [ "Commander", 1.0 ] ] ],
                                  [ "Attack", [ [ "BLC_Driver", 1.0 ],[ "Luk_Driver", 0.0 ], [ "Luk_Commander", 0.0 ], [ "Commander", 0.0 ] ] ]
                               ];

  final static String BodyJoint   = "Body";

  final static String DefaultSurfaceControl = "PutonGroundLandingJoints";      // LandingJoints
  final static Array  LandingJoints         = ["Corner_FL", "Corner_RL", "Corner_RR", "Corner_FR"];

  static Array  SubstanceArmourWidth = [
                                         [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                                         [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                                         [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                                         [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                                         [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                                         [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                                         [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                                         [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                                         [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                                         [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                                         [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                                      ];

   Array m_DamageTransfer = [ // From Item , To Item, Item HitPoints Percent
                             ["HullDriver", "HullEngine", 0.6f],
                             ["HullDriver", "HullGunlayer", 0.1f]
                             ];
 

  // Camera parameters
  float MinHorAngle  = -1.475; //  360' -3.141592 was     -0.43
  float MaxHorAngle  =  1.475; // was 0.43
  float MinVertAngle = -1.30; // was      -0.75
  float MaxVertAngle =  0.43;  // 60' 1.047199
/* */
   // Critical Engine Speed
  float m_CriticalEngineSpeed1 = 2680.0;
  float m_TempIncreaseCoeff1   = 0.01;
  float m_CriticalEngineSpeed2 = 2690.0;
  float m_TempIncreaseCoeff2   = 0.1;
  float m_CriticalEngineSpeed3 = 2700.0;
  float m_TempIncreaseCoeff3   = 0.2;

  float m_CriticalWaterTemp = 115.0f;
  float m_CriticalOilTemp   = 100.0f;

  boolean m_AITankCollisionShape = true;

 int     m_CockpitStyle         = CS_Tiger;     //

  float   m_RepairTime = 20.0f;
  boolean m_ReadyToRepair = true;

  // =======================================
  // Contruction and initialization
  // =======================================

  void CTankPzVITigerE1_EarlyIIUnit()
  {

    SetupExtendMesh("Cu_veh_TIGER_E1_Early_Playable_IIModel", "Cu_veh_PzVI_MAIN_InsideModel");
    GetMeshComponent().SetLods([0]); //,120,80,60,40

    // Setup trucks
    SetupTracks(
      new #TrackAnimator<CTankPzVITigerE1_EarlyLeftTrack>(),
      new #TrackAnimator<CTankPzVITigerE1_EarlyRightTrack>()
    );

    SetGunRecoilEffects(new #LineAnimator<CTankPzVITigerE1_EarlyFireAnimation>());

    SetHatchBodyEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchBodyAnimator>());
    SetHatchCommanderEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchCommanderAnimator>(),
                             new #LineAnimator<CTankPzVITigerE1_EarlyCommanderOutAnimator>());

    SetHideInCockpitJoints(["Body_commander", "HullDriver"]);

    SetCockpitDevice("TachometerAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyTachometerAnimator>(), 3600.0f, 0.0f);
    SetCockpitDevice("SpeedAnimator", new #LineAnimator<CTankPzVITigerE1_EarlySpeedometerAnimator>(), 80.88f, 0.0f);
    SetCockpitDevice("OilPressureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyOilPressAnimator>(), 18.0f, 0.0f);
    SetCockpitDevice("WaterTemperatureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyWaterTempAnimator>(), 125.0f, 0.0f);

  // Setup turret out animator
   // SetTurretOutEffectsArray( TurretOutAnimations );

  }


  void Construct(
      Component _Mission,
      Component _PropMap
    )
  {


    if (_PropMap.Get("IsManual", false))  //
   {                                    //

      EnableSurfaceControl(false);

      SetEngineComponents(
          [
          [ "Smoke_L", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect",      "Engine"     ],
          [ "Smoke_L", "TigerEngineSmokeEffect",      "Engine"     ]
          ]
        );

      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyPlayerGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null );  // new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      Component Game = new #GameController();
      boolean IsMirror = _PropMap.Get("IsMirror", (Game.GetGameMode() == "Client"));
      if (IsMirror)
        SetIdleEffects(new #Emitter<CTankPzVIAusfEIdleSound>());

        boolean isAutoShooter = true;
        if(isFunctionExist(_Mission, "IsExpertMode", 0))
            isAutoShooter = !_Mission.IsExpertMode();
        if(isAutoShooter && !IsMirror )
        {
          Component AutoShooter = new #AutoShooter<CAutoShooter>();
          setSlaveObject( AutoShooter, this );
          AutoShooter.SetMachineGun( GetObject( "Weapon_B" ) );
          AutoShooter.SetMainGun( GetObject( "Weapon_A" ) );
          AutoShooter.SetEventHandler(this);
          AutoShooter.Enable(true);
          AutoShooter.SetUnitPriority(CUnitType::UnitPriority);
          RegisterObject( "AutoShooter", AutoShooter );
        }
           // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );



      SetAccelEffects(
          new #Emitter<CTankPzIVGAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );
        



    }
    else
    {
      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null ); //  new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      SetupBehavior( new #VehicleBehavior<CTankPzVITigerE1_EarlyBehavior>());


      Component hatches = new #HatchesStateController();
      hatches.AddHatches( Hatches );
      hatches.AddStates( HatchesStates );
      SetupHatches( hatches );
      hatches.SetHatchesState( "Normal" );

    // Creates and register unit state component
    // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      SetIdleEffects(
          new #Emitter<CTankPzVIAusfE_IdleSound>()
        );

      SetAccelEffects(
          new #Emitter<CTankPzVIAusfEAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      GetLeftTrack().EnableAutoCalcPath(true);
      GetRightTrack().EnableAutoCalcPath(true);

    }

    CPlayerUnit::Construct(_Mission, _PropMap);

    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET762792, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET127, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_SUBCALIBREBULLET7576, 0.4);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET7576, 0.2);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BUILDING, 0.0);

    // create effects for tracks: [ HostId, Effectid, ZoneId ]
    SetTrackEffects(
        _Mission,
        [
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ]
        ]
      );

    CreateUnitItem(
        "HullDriver",
        CJointPoints::TankPzVIAusfEUnitHULL_DRIVERPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "HullDriver"
      );
    CreateUnitItem(
        "HullGunlayer",
        CJointPoints::TankPzVIAusfEUnitHULL_GUNLAYERPoints,
        ["GenericDamageItemEffect", "HullGunLayerExplosionEffect"],
        "HullGunlayer"
      );
    CreateUnitItem(
        "HullEngine",
        CJointPoints::TankPzVIAusfEUnitHULL_ENGINEPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "HullEngine"
      );
    CreateUnitItem(
        "TrackLeft",
        CJointPoints::TankPzVIAusfEUnitTRACK_LEFTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackLeft"
      );
    CreateUnitItem(
        "TrackRight",
        CJointPoints::TankPzVIAusfEUnitTRACK_RIGHTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackRight"
      );
    CreateUnitItem(
        "Turret_A",
        CJointPoints::TankPzVIAusfEUnitTURRETPoints,
        ["GenericDamageItemEffect", "GenericLargeFirePostSmokeRefuseEffect"],
      //  ["Turret_A_Crashed", "Turret_A_Crashed"],
        "Turret_A"
      );

    GetObject("Weapon_A").SetFireAnimator(GetObject("GunRecoilAnimator"));
    //logWarning("Weapon fire deviation for " + getIdentificator(this) + "=" + new String(GetObject("Weapon_A").FireDeviation));

    LinkDeviceToUnitItem("HullDriver",   new CTankPzVITigerE1_EarlyHullDriverDevice());
    LinkDeviceToUnitItem("HullGunlayer", new CTankPzVITigerE1_EarlyHullGunlayerDevice());
    LinkDeviceToUnitItem("HullEngine",   new CTankPzVITigerE1_EarlyHullEngineDevice());
    LinkDeviceToUnitItem("TrackLeft",    new CTankPzVITigerE1_EarlyTrackLeftDevice());
    LinkDeviceToUnitItem("TrackRight",   new CTankPzVITigerE1_EarlyTrackRightDevice());
    LinkDeviceToUnitItem("Turret_A",     new CTankPzVITigerE1_EarlyTurretDevice());

    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));

    SetupRecoilController(new #RecoilController<CTankPzVITigerE1_EarlyRecoilController>());

    if ((new #GameController()).GetGameMode() != "Single")            // != "Single")
       GetObject("Mesh").SetAnimateAlways(true);

    if (!_PropMap.Get("IsManual", false))
      SetupPhysicaleObject("CTankPzVITigerE1_EarlySubstance", 60000.0, 0.0);


    if (_PropMap.Get("IsManual", false))
    {
      GetObject("VoiceMessenger").AddSoundTable(CCockpit::TigerVoices);
      SetAngleMessages(CCockpit::GermanAngleMessages);
      m_TargetDirection = [[L"", ""],[L"", ""]];

/*        Component PointDetector = new #PointCollisionDetector();
      PointDetector.EnableDetector(true);
      PointDetector.SetCollisionMask([CLASSIFICATOR_TERRAIN, CLASSIFICATOR_GROUND, CLASSIFICATOR_TERRAINFOREST],[]);
      PointDetector.SetEventHandler(this);
      setPositionable(PointDetector, GetMeshComponent());
      RegisterObject("PointDetector", PointDetector);  */
    }

 }
  // =======================================
  // Collision control
  // =======================================

  Component CreateCollisionControl(String _ScriptClassName)
  {
    Component CollisionControl = new #CollisionControl2();
    CollisionControl.SetCollisionMask(
        [CLASSIFICATOR_WALK_SURFACE],
        [ CLASSIFICATOR_DO_NOT_COLLISION_CHECK, CLASSIFICATOR_PHYSICS_CONTROLLABLE ]
       );

    loadFromScript(CollisionControl, _ScriptClassName);
    RegisterObject("CollisionControl", CollisionControl);

    return CollisionControl;
  }

  void Initialize(
      Component   _Mission,
      Component   _PropMap
    )
  {
    CPlayerUnit::Initialize(_Mission, _PropMap);
     // Put on ground tank object
    boolean IsManual = _PropMap.Get("IsManual", false);
    if (IsManual)
    {
      LinkModel();
      PutonGround();
      EnableSurfaceControl(false);
      UnlinkModel();

    }

 }

  void SetFlagMode(
      boolean _Enable
    )
  {
    if (_Enable)
    {
     setVisibleState(GetMeshComponent().GetJoint("Flag"), true);
     }
    else
      setVisibleState(GetMeshComponent().GetJoint("Flag"), false);
   }

  // ======================================
  // Vehicle controller
  // ======================================
  Component CreateVehicleController()
  {
   
  CTankPzVITigerE1_EarlyEngineSystem::EventHandler = this;      //
  return (new #TankVehicle<CTankPzVITigerE1_EarlyManualControl>());

  }

  // ======================================
  // AI Vehicle controller
  // ======================================
  Component CreateAIVehicleController()
  {
    return (new #AITankVehicle<CTankPzVITigerE1_EarlyManualControl>());
  }

  // ======================================
  // Manual control
  // ======================================
  Component CreateManualControl()
  {
    return new #ManualTankControl();
  }

  // ======================================
  // Armour descriptor
  // ======================================
  Array GetArmourDescriptor()
  {
    return new Array ([
                        [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                        [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                        [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                        [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                        [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                        [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                        [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                        [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                        [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                        [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                        [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                      ]);
  }

  event void ReadyToRepair()
  {
    m_ReadyToRepair = true;
  }

  event void ReloadAmmo()
  {

    if (!checkMask(this, [], [CLASSIFICATOR_DEAD_OBJECT]) || !m_ReadyToRepair)
      return;

    Component AutoThingsUI = GetObject("AutoThingsUI");
    if ( AutoThingsUI == null )
      return;

    if (AutoThingsUI.IsHandbrakeActive())
    {
      m_ReadyToRepair = false;
      sendEvent(m_RepairTime, getIdentificator(this), "ReadyToRepair", []);

      Component Weapon = GetObject("Weapon_A");
      Weapon.SetAmmoQuantity(0, CTankPzVITigerE1_EarlyCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(1, CTankPzVITigerE1_EarlySubCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(2, CTankPzVITigerE1_EarlyHEAmmoPlayer::Ammunition);

      Component StateControl = GetStateControl();
      for (int i = 0; i < m_UnitItemsList.size(); i++)
      {
        Component Item = m_UnitItemsList[i];
        StateControl.SetUnitItemHP(Item.Index, Item.HitPoints);
        Item.CurrentHitPoints = Item.HitPoints;
      }
    }
  }

  // ======================================
  // Point collision detector
  // ======================================

  // Call when tank deep in the water (Вызывается, когда танк глубоко заехал в воду)
  event void OnPointCollisionDetect(String _ObjectID)
  {
    // Destroy HullEngine may be changed (убиваем движок, можно заменить на что-то другое)
    SetUnitItemHPPercent("HullEngine", 0.0);
    
    GetObject("PointDetector").EnableDetector(false);
  }


  event void SetModelViewState(
      boolean _State
    )
  {
    // TMP
  }

}

// ================================================
// Unit class 3 Winter
// ================================================

class CTankPzVITigerE1_Early_WUnit
    extends CGerTankPlayerUnit,CWeaponConfig, CPushVehicleObject  //
{
  final static String DefaultHealthParameter = "HP_HEALTHY";  // fragile constitution
  // Automatic classificators of this object
  final static Array AutomaticClassificators  = ["GROUND", "HEAVYTANK", "GER"];
  final static float DefaultHitPoints = CHitPoints::TankPzVIAusfEUnitHitPoints;

  boolean m_flag = false;



  final static boolean DefaultSetFlagMode       = false;

  final static boolean DefaultSetWinterMode     = false; //

  static category UnitType = CLASSIFICATOR_T34_HEAVY_TANK;

  static Array PostExplosionID = [
                                    ["", "TankPzVIAusfExplosion"]
                                 ];

  static Array Hatches = [
                            [ "BLC_Driver",    "block_open",         1.0 ],
                            [ "Luk_Driver",    "luk_body_open",      1.0 ], //
                            [ "Luk_Commander", "luk_main_open",      2.0 ],
                            [ "Commander",  "luk_main_commander", 2.0 ]
                         ];

                                                                        

  static Array HatchesStates = [
                                  [ "Normal", [ [ "BLC_Driver", 0.0 ],[ "Luk_Driver", 1.0 ], [ "Luk_Commander", 1.0 ], [ "Commander", 1.0 ] ] ],
                                  [ "Attack", [ [ "BLC_Driver", 1.0 ],[ "Luk_Driver", 0.0 ], [ "Luk_Commander", 0.0 ], [ "Commander", 0.0 ] ] ]
                               ];

  final static String BodyJoint   = "Body";

  final static String DefaultSurfaceControl = "PutonGroundLandingJoints";      // LandingJoints
  final static Array  LandingJoints         = ["Corner_FL", "Corner_RL", "Corner_RR", "Corner_FR"];

  static Array  SubstanceArmourWidth = [
                                         [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                                         [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                                         [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                                         [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                                         [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                                         [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                                         [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                                         [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                                         [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                                         [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                                         [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                                      ];

   Array m_DamageTransfer = [ // From Item , To Item, Item HitPoints Percent
                             ["HullDriver", "HullEngine", 0.6f],
                             ["HullDriver", "HullGunlayer", 0.6f]
                             ];
 

  // Camera parameters
  float MinHorAngle  = -1.475; //  360' -3.141592 was     -0.43
  float MaxHorAngle  =  1.475; // was 0.43
  float MinVertAngle = -1.30; // was      -0.75
  float MaxVertAngle =  0.43;  // 60' 1.047199
/* */
   // Critical Engine Speed
  float m_CriticalEngineSpeed1 = 2680.0;
  float m_TempIncreaseCoeff1   = 0.01;
  float m_CriticalEngineSpeed2 = 2690.0;
  float m_TempIncreaseCoeff2   = 0.1;
  float m_CriticalEngineSpeed3 = 2700.0;
  float m_TempIncreaseCoeff3   = 0.2;

  float m_CriticalWaterTemp = 115.0f;
  float m_CriticalOilTemp   = 100.0f;

  boolean m_AITankCollisionShape = true;

 int     m_CockpitStyle         = CS_Tiger;     //

  float   m_RepairTime = 20.0f;
  boolean m_ReadyToRepair = true;

  // =======================================
  // Contruction and initialization
  // =======================================

  void CTankPzVITigerE1_Early_WUnit()
  {

    SetupExtendMesh("Cu_veh_TIGER_E1_Early_Playable_WModel", "Cu_veh_PzVI_MAIN_InsideModel");

    GetMeshComponent().SetLods([0]);   //  ,120,80,60,40

    // Setup trucks
    SetupTracks(
      new #TrackAnimator<CTankPzVITigerE1_EarlyLeftTrack>(),
      new #TrackAnimator<CTankPzVITigerE1_EarlyRightTrack>()
    );

    SetGunRecoilEffects(new #LineAnimator<CTankPzVITigerE1_EarlyFireAnimation>());

    SetHatchBodyEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchBodyAnimator>());
    SetHatchCommanderEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchCommanderAnimator>(),
                             new #LineAnimator<CTankPzVITigerE1_EarlyCommanderOutAnimator>());

    SetHideInCockpitJoints(["Body_commander", "HullDriver"]);

    SetCockpitDevice("TachometerAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyTachometerAnimator>(), 3600.0f, 0.0f);
    SetCockpitDevice("SpeedAnimator", new #LineAnimator<CTankPzVITigerE1_EarlySpeedometerAnimator>(), 80.88f, 0.0f);
    SetCockpitDevice("OilPressureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyOilPressAnimator>(), 18.0f, 0.0f);
    SetCockpitDevice("WaterTemperatureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyWaterTempAnimator>(), 125.0f, 0.0f);

  // Setup turret out animator
   // SetTurretOutEffectsArray( TurretOutAnimations );

  }


  void Construct(
      Component _Mission,
      Component _PropMap
    )
  {


    if (_PropMap.Get("IsManual", false))  //
   {                                    //

      EnableSurfaceControl(false);

      SetEngineComponents(
          [
          [ "Smoke_L", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect",      "Engine"     ],
          [ "Smoke_L", "TigerEngineSmokeEffect",      "Engine"     ]
          ]
        );

      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyPlayerGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null );  // new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      Component Game = new #GameController();
      boolean IsMirror = _PropMap.Get("IsMirror", (Game.GetGameMode() == "Client"));
      if (IsMirror)
        SetIdleEffects(new #Emitter<CTankPzVIAusfEIdleSound>());

        boolean isAutoShooter = true;
        if(isFunctionExist(_Mission, "IsExpertMode", 0))
            isAutoShooter = !_Mission.IsExpertMode();
        if(isAutoShooter && !IsMirror )
        {
          Component AutoShooter = new #AutoShooter<CAutoShooter>();
          setSlaveObject( AutoShooter, this );
          AutoShooter.SetMachineGun( GetObject( "Weapon_B" ) );
          AutoShooter.SetMainGun( GetObject( "Weapon_A" ) );
          AutoShooter.SetEventHandler(this);
          AutoShooter.Enable(true);
          AutoShooter.SetUnitPriority(CUnitType::UnitPriority);
          RegisterObject( "AutoShooter", AutoShooter );
        }
           // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );



      SetAccelEffects(
          new #Emitter<CTankPzIVGAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );
        



    }
    else
    {
      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null ); //  new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      SetupBehavior( new #VehicleBehavior<CTankPzVITigerE1_EarlyBehavior>());


      Component hatches = new #HatchesStateController();
      hatches.AddHatches( Hatches );
      hatches.AddStates( HatchesStates );
      SetupHatches( hatches );
      hatches.SetHatchesState( "Normal" );

    // Creates and register unit state component
    // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      SetIdleEffects(
          new #Emitter<CTankPzVIAusfE_IdleSound>()
        );

      SetAccelEffects(
          new #Emitter<CTankPzVIAusfEAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      GetLeftTrack().EnableAutoCalcPath(true);
      GetRightTrack().EnableAutoCalcPath(true);

    }

    CPlayerUnit::Construct(_Mission, _PropMap);

    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET762792, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET127, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_SUBCALIBREBULLET7576, 0.4);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET7576, 0.2);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BUILDING, 0.0);

    // create effects for tracks: [ HostId, Effectid, ZoneId ]
    SetTrackEffects(
        _Mission,
        [
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ]
        ]
      );

    CreateUnitItem(
        "HullDriver",
        CJointPoints::TankPzVIAusfEUnitHULL_DRIVERPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "HullDriver"
      );
    CreateUnitItem(
        "HullGunlayer",
        CJointPoints::TankPzVIAusfEUnitHULL_GUNLAYERPoints,
        ["GenericDamageItemEffect", "HullGunLayerExplosionEffect"],
        "HullGunlayer"
      );
    CreateUnitItem(
        "HullEngine",
        CJointPoints::TankPzVIAusfEUnitHULL_ENGINEPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "HullEngine"
      );
    CreateUnitItem(
        "TrackLeft",
        CJointPoints::TankPzVIAusfEUnitTRACK_LEFTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackLeft"
      );
    CreateUnitItem(
        "TrackRight",
        CJointPoints::TankPzVIAusfEUnitTRACK_RIGHTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackRight"
      );
    CreateUnitItem(
        "Turret_A",
        CJointPoints::TankPzVIAusfEUnitTURRETPoints,
        ["GenericDamageItemEffect", "GenericLargeFirePostSmokeRefuseEffect"],
      //  ["Turret_A_Crashed", "Turret_A_Crashed"],
        "Turret_A"
      );

    GetObject("Weapon_A").SetFireAnimator(GetObject("GunRecoilAnimator"));
    //logWarning("Weapon fire deviation for " + getIdentificator(this) + "=" + new String(GetObject("Weapon_A").FireDeviation));

    LinkDeviceToUnitItem("HullDriver",   new CTankPzVITigerE1_EarlyHullDriverDevice());
    LinkDeviceToUnitItem("HullGunlayer", new CTankPzVITigerE1_EarlyHullGunlayerDevice());
    LinkDeviceToUnitItem("HullEngine",   new CTankPzVITigerE1_EarlyHullEngineDevice());
    LinkDeviceToUnitItem("TrackLeft",    new CTankPzVITigerE1_EarlyTrackLeftDevice());
    LinkDeviceToUnitItem("TrackRight",   new CTankPzVITigerE1_EarlyTrackRightDevice());
    LinkDeviceToUnitItem("Turret_A",     new CTankPzVITigerE1_EarlyTurretDevice());

    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));

    SetupRecoilController(new #RecoilController<CTankPzVITigerE1_EarlyRecoilController>());

    if ((new #GameController()).GetGameMode() != "Single")            // != "Single")
       GetObject("Mesh").SetAnimateAlways(true);

    if (!_PropMap.Get("IsManual", false))
      SetupPhysicaleObject("CTankPzVITigerE1_EarlySubstance", 60000.0, 0.0);


    if (_PropMap.Get("IsManual", false))
    {
      GetObject("VoiceMessenger").AddSoundTable(CCockpit::TigerVoices);
      SetAngleMessages(CCockpit::GermanAngleMessages);
      m_TargetDirection = [[L"", ""],[L"", ""]];

      Component PointDetector = new #PointCollisionDetector();
      PointDetector.EnableDetector(true);
      PointDetector.SetCollisionMask([CLASSIFICATOR_TERRAIN, CLASSIFICATOR_GROUND, CLASSIFICATOR_TERRAINFOREST],[]);
      PointDetector.SetEventHandler(this);
      setPositionable(PointDetector, GetMeshComponent());
      RegisterObject("PointDetector", PointDetector); /*   */
    }

 }
  // =======================================
  // Collision control
  // =======================================

  Component CreateCollisionControl(String _ScriptClassName)
  {
    Component CollisionControl = new #CollisionControl2();
    CollisionControl.SetCollisionMask(
        [CLASSIFICATOR_WALK_SURFACE],
        [ CLASSIFICATOR_DO_NOT_COLLISION_CHECK, CLASSIFICATOR_PHYSICS_CONTROLLABLE ]
       );

    loadFromScript(CollisionControl, _ScriptClassName);
    RegisterObject("CollisionControl", CollisionControl);

    return CollisionControl;
  }

  void Initialize(
      Component   _Mission,
      Component   _PropMap
    )
  {
    CPlayerUnit::Initialize(_Mission, _PropMap);
     // Put on ground tank object
    boolean IsManual = _PropMap.Get("IsManual", false);
    if (IsManual)
    {
      LinkModel();
      PutonGround();
      EnableSurfaceControl(false);
      UnlinkModel();

    }

 }

  void SetFlagMode(
      boolean _Enable
    )
  {
    if (_Enable)
    {
     setVisibleState(GetMeshComponent().GetJoint("Flag"), true);
     }
    else
      setVisibleState(GetMeshComponent().GetJoint("Flag"), false);
   }

  // ======================================
  // Vehicle controller
  // ======================================
  Component CreateVehicleController()
  {
   
  CTankPzVITigerE1_EarlyEngineSystem::EventHandler = this;      //
  return (new #TankVehicle<CTankPzVITigerE1_EarlyManualControl>());

  }

  // ======================================
  // AI Vehicle controller
  // ======================================
  Component CreateAIVehicleController()
  {
    return (new #AITankVehicle<CTankPzVITigerE1_EarlyManualControl>());
  }

  // ======================================
  // Manual control
  // ======================================
  Component CreateManualControl()
  {
    return new #ManualTankControl();
  }

  // ======================================
  // Armour descriptor
  // ======================================
  Array GetArmourDescriptor()
  {
    return new Array ([
                        [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                        [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                        [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                        [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                        [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                        [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                        [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                        [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                        [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                        [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                        [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                      ]);
  }

  event void Winter()
  {
    //Component mission = GetMission();
    return IsWinter = true;

  }/**/

  event void ReadyToRepair()
  {
    m_ReadyToRepair = true;
  }

  event void ReloadAmmo()
  {

    if (!checkMask(this, [], [CLASSIFICATOR_DEAD_OBJECT]) || !m_ReadyToRepair)
      return;

    Component AutoThingsUI = GetObject("AutoThingsUI");
    if ( AutoThingsUI == null )
      return;

    if (AutoThingsUI.IsHandbrakeActive())
    {
      m_ReadyToRepair = false;
      sendEvent(m_RepairTime, getIdentificator(this), "ReadyToRepair", []);

      Component Weapon = GetObject("Weapon_A");
      Weapon.SetAmmoQuantity(0, CTankPzVITigerE1_EarlyCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(1, CTankPzVITigerE1_EarlySubCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(2, CTankPzVITigerE1_EarlyHEAmmoPlayer::Ammunition);

      Component StateControl = GetStateControl();
      for (int i = 0; i < m_UnitItemsList.size(); i++)
      {
        Component Item = m_UnitItemsList[i];
        StateControl.SetUnitItemHP(Item.Index, Item.HitPoints);
        Item.CurrentHitPoints = Item.HitPoints;
      }
    }
  }

  // ======================================
  // Point collision detector
  // ======================================

  // Call when tank deep in the water (Вызывается, когда танк глубоко заехал в воду)
  event void OnPointCollisionDetect(String _ObjectID)
  {
    // Destroy HullEngine may be changed (убиваем движок, можно заменить на что-то другое)
    SetUnitItemHPPercent("HullEngine", 0.0);
    
    GetObject("PointDetector").EnableDetector(false);
  }


  event void SetModelViewState(
      boolean _State
    )
  {
    // TMP
  }

}
// ================================================
// Unit class 4 _PzGry
// ================================================

class CTankPzVITigerE1_Early_PzGryUnit
    extends CGerTankPlayerUnit,CWeaponConfig, CPushVehicleObject  //
{
  final static String DefaultHealthParameter = "HP_HEALTHY";  // fragile constitution
  // Automatic classificators of this object
  final static Array AutomaticClassificators  = ["GROUND", "HEAVYTANK", "GER"];
  final static float DefaultHitPoints = CHitPoints::TankPzVIAusfEUnitHitPoints;

  boolean m_flag = false;

  final static boolean DefaultSetFlagMode       = false;

  final static boolean DefaultSetWinterMode     = false; //

  static category UnitType = CLASSIFICATOR_T34_HEAVY_TANK;

  static Array PostExplosionID = [
                                    ["", "TankPzVIAusfExplosion"]
                                 ];

  static Array Hatches = [
                            [ "BLC_Driver",    "block_open",         1.0 ],
                            [ "Luk_Driver",    "luk_body_open",      1.0 ], //
                            [ "Luk_Commander", "luk_main_open",      2.0 ],
                            [ "Commander",  "luk_main_commander", 2.0 ]
                         ];

                                                                        

  static Array HatchesStates = [
                                  [ "Normal", [ [ "BLC_Driver", 0.0 ],[ "Luk_Driver", 1.0 ], [ "Luk_Commander", 1.0 ], [ "Commander", 1.0 ] ] ],
                                  [ "Attack", [ [ "BLC_Driver", 1.0 ],[ "Luk_Driver", 0.0 ], [ "Luk_Commander", 0.0 ], [ "Commander", 0.0 ] ] ]
                               ];

  final static String BodyJoint   = "Body";

  final static String DefaultSurfaceControl = "PutonGroundLandingJoints";      // LandingJoints
  final static Array  LandingJoints         = ["Corner_FL", "Corner_RL", "Corner_RR", "Corner_FR"];

  static Array  SubstanceArmourWidth = [
                                         [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                                         [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                                         [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                                         [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                                         [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                                         [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                                         [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                                         [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                                         [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                                         [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                                         [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                                      ];

   Array m_DamageTransfer = [ // From Item , To Item, Item HitPoints Percent
                             ["HullDriver", "HullEngine", 0.6f],
                             ["HullDriver", "HullGunlayer", 0.6f]
                             ];
 

  // Camera parameters
  float MinHorAngle  = -1.475; //  360' -3.141592 was     -0.43
  float MaxHorAngle  =  1.475; // was 0.43
  float MinVertAngle = -1.30; // was      -0.75
  float MaxVertAngle =  0.43;  // 60' 1.047199
/* */
   // Critical Engine Speed
  float m_CriticalEngineSpeed1 = 2680.0;
  float m_TempIncreaseCoeff1   = 0.01;
  float m_CriticalEngineSpeed2 = 2690.0;
  float m_TempIncreaseCoeff2   = 0.1;
  float m_CriticalEngineSpeed3 = 2700.0;
  float m_TempIncreaseCoeff3   = 0.2;

  float m_CriticalWaterTemp = 115.0f;
  float m_CriticalOilTemp   = 100.0f;

  boolean m_AITankCollisionShape = true;

 int     m_CockpitStyle         = CS_Tiger;     //

  float   m_RepairTime = 20.0f;
  boolean m_ReadyToRepair = true;

  // =======================================
  // Contruction and initialization
  // =======================================

  void CTankPzVITigerE1_Early_PzGryUnit()
  {

    SetupExtendMesh("Cu_veh_TIGER_E1_Early_Playable_PzGryModel", "Cu_veh_PzVI_MAIN_InsideModel");

    GetMeshComponent().SetLods([0]);   //  ,120,80,60,40

    // Setup trucks
    SetupTracks(
      new #TrackAnimator<CTankPzVITigerE1_EarlyLeftTrack>(),
      new #TrackAnimator<CTankPzVITigerE1_EarlyRightTrack>()
    );

    SetGunRecoilEffects(new #LineAnimator<CTankPzVITigerE1_EarlyFireAnimation>());

    SetHatchBodyEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchBodyAnimator>());
    SetHatchCommanderEffects(new #LineAnimator<CTankPzVITigerE1_EarlyHatchCommanderAnimator>(),
                             new #LineAnimator<CTankPzVITigerE1_EarlyCommanderOutAnimator>());

    SetHideInCockpitJoints(["Body_commander", "HullDriver"]);

    SetCockpitDevice("TachometerAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyTachometerAnimator>(), 3600.0f, 0.0f);
    SetCockpitDevice("SpeedAnimator", new #LineAnimator<CTankPzVITigerE1_EarlySpeedometerAnimator>(), 80.88f, 0.0f);
    SetCockpitDevice("OilPressureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyOilPressAnimator>(), 18.0f, 0.0f);
    SetCockpitDevice("WaterTemperatureAnimator", new #LineAnimator<CTankPzVITigerE1_EarlyWaterTempAnimator>(), 125.0f, 0.0f);

  // Setup turret out animator
   // SetTurretOutEffectsArray( TurretOutAnimations );

  }


  void Construct(
      Component _Mission,
      Component _PropMap
    )
  {


    if (_PropMap.Get("IsManual", false))  //
   {                                    //

      EnableSurfaceControl(false);

      SetEngineComponents(
          [
          [ "Smoke_L", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect", "EngineStart"],
          [ "Smoke_R", "TigerEngineSmokeEffect",      "Engine"     ],
          [ "Smoke_L", "TigerEngineSmokeEffect",      "Engine"     ]
          ]
        );

      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyPlayerMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyPlayerGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null );  // new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      Component Game = new #GameController();
      boolean IsMirror = _PropMap.Get("IsMirror", (Game.GetGameMode() == "Client"));
      if (IsMirror)
        SetIdleEffects(new #Emitter<CTankPzVIAusfEIdleSound>());

        boolean isAutoShooter = true;
        if(isFunctionExist(_Mission, "IsExpertMode", 0))
            isAutoShooter = !_Mission.IsExpertMode();
        if(isAutoShooter && !IsMirror )
        {
          Component AutoShooter = new #AutoShooter<CAutoShooter>();
          setSlaveObject( AutoShooter, this );
          AutoShooter.SetMachineGun( GetObject( "Weapon_B" ) );
          AutoShooter.SetMainGun( GetObject( "Weapon_A" ) );
          AutoShooter.SetEventHandler(this);
          AutoShooter.Enable(true);
          AutoShooter.SetUnitPriority(CUnitType::UnitPriority);
          RegisterObject( "AutoShooter", AutoShooter );
        }
           // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );



      SetAccelEffects(
          new #Emitter<CTankPzIVGAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );
        



    }
    else
    {
      // Setup Weapon
      SetupAmmoContainer(new #AmmoContainer<CTankPzVITigerE1_EarlyAmmoContainer>());
      Component CoaxialMachineGun = new #Weapon2<CTankPzVITigerE1_EarlyCoaxialMachineGun>();
      Component MachineGun = new #Weapon2<CTankPzVITigerE1_EarlyMachineGun>();
      CoaxialMachineGun.SetAmmoContainer(GetObject("AmmoContainer"));
      MachineGun.SetAmmoContainer(GetObject("AmmoContainer"));

      SetupWeapon( "Weapon_A", new #Weapon<CTankPzVITigerE1_EarlyGun>(),
                  ["Fire_A1"], new #TargetingAnimator<CTankPzVITigerE1_EarlyGunTargetingAnimatorA>());
      SetupWeapon("Weapon_B", CoaxialMachineGun, "Fire_A1",
        ["Fire_B1"], null);
      SetupWeapon("Weapon_C", MachineGun,
        ["Fire_C1"],null ); //  new #TargetingAnimator2<CTankPzVITigerE1_EarlyTargetingAnimatorB>()

      SetupBehavior( new #VehicleBehavior<CTankPzVITigerE1_EarlyBehavior>());


      Component hatches = new #HatchesStateController();
      hatches.AddHatches( Hatches );
      hatches.AddStates( HatchesStates );
      SetupHatches( hatches );
      hatches.SetHatchesState( "Normal" );

    // Creates and register unit state component
    // MoveSound, TraceEffectId
      SetMovementEffects(
          new #Emitter<CTankPzVIAusfEMovementSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      SetIdleEffects(
          new #Emitter<CTankPzVIAusfE_IdleSound>()
        );

      SetAccelEffects(
          new #Emitter<CTankPzVIAusfEAccelSound>(),
          [
            ["Smoke_R", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)],
            ["Smoke_L", "TigerEngineSmokeEffect", new Vector (0.0, 0.0, 0.1)]
          ]
        );

      GetLeftTrack().EnableAutoCalcPath(true);
      GetRightTrack().EnableAutoCalcPath(true);

    }

    CPlayerUnit::Construct(_Mission, _PropMap);

    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET762792, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BULLET127, 0.0f);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_SUBCALIBREBULLET7576, 0.4);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_CALIBREBULLET7576, 0.2);
    GetDamageHandler().SetDamageTypeModifier(CBaseExplosion::CLASSIFICATOR_DAMAGE_BUILDING, 0.0);

    // create effects for tracks: [ HostId, Effectid, ZoneId ]
    SetTrackEffects(
        _Mission,
        [
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Forest04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadForest, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush02, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush03, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Bush04, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyLarge, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyRegular, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_ShrubberyCasual, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_SpecialLongAloneTree, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting01, "Right" ],
          ["Corner_RL", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Left" ],
          ["Corner_RR", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_VillagePlanting02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass01, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass02, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass03, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_Grass04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad02, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad03, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_OffRoad04, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_Road01Add, "Right" ],
          ["Vapor_L", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Left" ],
          ["Vapor_R", "RoadUnitTraceEffect", CBaseZoneMap::ZMC_RoadObject, "Right" ],
          ["Vapor_L", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Left" ],
          ["Vapor_R", "GroundUnitTraceEffect", CBaseZoneMap::ZMC_AllPassable, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_Water01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_ShallowWater01, "Right" ],
          ["Corner_FL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RL", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Left" ],
          ["Corner_RR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ],
          ["Corner_FR", "TankWaterEffect", CBaseZoneMap::ZMC_BeachWater01, "Right" ]
        ]
      );

    CreateUnitItem(
        "HullDriver",
        CJointPoints::TankPzVIAusfEUnitHULL_DRIVERPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "HullDriver"
      );
    CreateUnitItem(
        "HullGunlayer",
        CJointPoints::TankPzVIAusfEUnitHULL_GUNLAYERPoints,
        ["GenericDamageItemEffect", "HullGunLayerExplosionEffect"],
        "HullGunlayer"
      );
    CreateUnitItem(
        "HullEngine",
        CJointPoints::TankPzVIAusfEUnitHULL_ENGINEPoints,
        ["GenericDamageItemEffect", "GenericSmallFireEffect"],
        "HullEngine"
      );
    CreateUnitItem(
        "TrackLeft",
        CJointPoints::TankPzVIAusfEUnitTRACK_LEFTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackLeft"
      );
    CreateUnitItem(
        "TrackRight",
        CJointPoints::TankPzVIAusfEUnitTRACK_RIGHTPoints,
        ["GenericDamageItemEffect", "GenericDamageItemEffect"],
        "TrackRight"
      );
    CreateUnitItem(
        "Turret_A",
        CJointPoints::TankPzVIAusfEUnitTURRETPoints,
        ["GenericDamageItemEffect", "GenericLargeFirePostSmokeRefuseEffect"],
      //  ["Turret_A_Crashed", "Turret_A_Crashed"],
        "Turret_A"
      );

    GetObject("Weapon_A").SetFireAnimator(GetObject("GunRecoilAnimator"));
    //logWarning("Weapon fire deviation for " + getIdentificator(this) + "=" + new String(GetObject("Weapon_A").FireDeviation));

    LinkDeviceToUnitItem("HullDriver",   new CTankPzVITigerE1_EarlyHullDriverDevice());
    LinkDeviceToUnitItem("HullGunlayer", new CTankPzVITigerE1_EarlyHullGunlayerDevice());
    LinkDeviceToUnitItem("HullEngine",   new CTankPzVITigerE1_EarlyHullEngineDevice());
    LinkDeviceToUnitItem("TrackLeft",    new CTankPzVITigerE1_EarlyTrackLeftDevice());
    LinkDeviceToUnitItem("TrackRight",   new CTankPzVITigerE1_EarlyTrackRightDevice());
    LinkDeviceToUnitItem("Turret_A",     new CTankPzVITigerE1_EarlyTurretDevice());

    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(0.65, 0.0, 0.0));
    AttachEffect2("Vapor_L", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));
    AttachEffect2("Vapor_R", "PzVIETrackEffect", new Vector(-0.65, 0.0, 0.0));

    SetupRecoilController(new #RecoilController<CTankPzVITigerE1_EarlyRecoilController>());

    if ((new #GameController()).GetGameMode() != "Single")            // != "Single")
       GetObject("Mesh").SetAnimateAlways(true);

    if (!_PropMap.Get("IsManual", false))
      SetupPhysicaleObject("CTankPzVITigerE1_EarlySubstance", 70000.0, 0.0);


    if (_PropMap.Get("IsManual", false))
    {
      GetObject("VoiceMessenger").AddSoundTable(CCockpit::TigerVoices);
      SetAngleMessages(CCockpit::GermanAngleMessages);
      m_TargetDirection = [[L"", ""],[L"", ""]];

      Component PointDetector = new #PointCollisionDetector();
      PointDetector.EnableDetector(true);
      PointDetector.SetCollisionMask([CLASSIFICATOR_TERRAIN, CLASSIFICATOR_GROUND, CLASSIFICATOR_TERRAINFOREST],[]);
      PointDetector.SetEventHandler(this);
      setPositionable(PointDetector, GetMeshComponent());
      RegisterObject("PointDetector", PointDetector); /*   */
    }

 }
  // =======================================
  // Collision control
  // =======================================

  Component CreateCollisionControl(String _ScriptClassName)
  {
    Component CollisionControl = new #CollisionControl2();
    CollisionControl.SetCollisionMask(
        [CLASSIFICATOR_WALK_SURFACE],
        [ CLASSIFICATOR_DO_NOT_COLLISION_CHECK, CLASSIFICATOR_PHYSICS_CONTROLLABLE ]
       );

    loadFromScript(CollisionControl, _ScriptClassName);
    RegisterObject("CollisionControl", CollisionControl);

    return CollisionControl;
  }

  void Initialize(
      Component   _Mission,
      Component   _PropMap
    )
  {
    CPlayerUnit::Initialize(_Mission, _PropMap);
     // Put on ground tank object
    boolean IsManual = _PropMap.Get("IsManual", false);
    if (IsManual)
    {
      LinkModel();
      PutonGround();
      EnableSurfaceControl(false);
      UnlinkModel();

    }

 }

  void SetFlagMode(
      boolean _Enable
    )
  {
    if (_Enable)
    {
     setVisibleState(GetMeshComponent().GetJoint("Flag"), true);
     }
    else
      setVisibleState(GetMeshComponent().GetJoint("Flag"), false);
   }

  // ======================================
  // Vehicle controller
  // ======================================
  Component CreateVehicleController()
  {
   
  CTankPzVITigerE1_EarlyEngineSystem::EventHandler = this;      //
  return (new #TankVehicle<CTankPzVITigerE1_EarlyManualControl>());

  }

  // ======================================
  // AI Vehicle controller
  // ======================================
  Component CreateAIVehicleController()
  {
    return (new #AITankVehicle<CTankPzVITigerE1_EarlyManualControl>());
  }

  // ======================================
  // Manual control
  // ======================================
  Component CreateManualControl()
  {
    return new #ManualTankControl();
  }

  // ======================================
  // Armour descriptor
  // ======================================
  Array GetArmourDescriptor()
  {
    return new Array ([
                        [CMaterialStructure::MSID_ArmourTurretFWD,   CArmourPoints::TankPzVIAusfEUnitArmourTurretFWD  ],
                        [CMaterialStructure::MSID_ArmourTurretREAR,  CArmourPoints::TankPzVIAusfEUnitArmourTurretREAR ],
                        [CMaterialStructure::MSID_ArmourTurretTOP,   CArmourPoints::TankPzVIAusfEUnitArmourTurretTOP  ],
                        [CMaterialStructure::MSID_ArmourTurretLEFT,  CArmourPoints::TankPzVIAusfEUnitArmourTurretLEFT ],
                        [CMaterialStructure::MSID_ArmourTurretRIGHT, CArmourPoints::TankPzVIAusfEUnitArmourTurretRIGHT],
                        [CMaterialStructure::MSID_ArmourHullFWD,     CArmourPoints::TankPzVIAusfEUnitArmourHullFWD    ],
                        [CMaterialStructure::MSID_ArmourHullREAR,    CArmourPoints::TankPzVIAusfEUnitArmourHullREAR   ],
                        [CMaterialStructure::MSID_ArmourHullTOP,     CArmourPoints::TankPzVIAusfEUnitArmourHullTOP    ],
                        [CMaterialStructure::MSID_ArmourHullBOTTOM,  CArmourPoints::TankPzVIAusfEUnitArmourHullBOTTOM ],
                        [CMaterialStructure::MSID_ArmourHullRIGHT,   CArmourPoints::TankPzVIAusfEUnitArmourHullRIGHT  ],
                        [CMaterialStructure::MSID_ArmourHullLEFT,    CArmourPoints::TankPzVIAusfEUnitArmourHullLEFT   ]
                      ]);
  }

  event void Winter()
  {
    //Component mission = GetMission();
    return IsWinter = true;

  }/**/

  event void ReadyToRepair()
  {
    m_ReadyToRepair = true;
  }

  event void ReloadAmmo()
  {

    if (!checkMask(this, [], [CLASSIFICATOR_DEAD_OBJECT]) || !m_ReadyToRepair)
      return;

    Component AutoThingsUI = GetObject("AutoThingsUI");
    if ( AutoThingsUI == null )
      return;

    if (AutoThingsUI.IsHandbrakeActive())
    {
      m_ReadyToRepair = false;
      sendEvent(m_RepairTime, getIdentificator(this), "ReadyToRepair", []);

      Component Weapon = GetObject("Weapon_A");
      Weapon.SetAmmoQuantity(0, CTankPzVITigerE1_EarlyCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(1, CTankPzVITigerE1_EarlySubCalibreAmmoPlayer::Ammunition);
      Weapon.SetAmmoQuantity(2, CTankPzVITigerE1_EarlyHEAmmoPlayer::Ammunition);

      Component StateControl = GetStateControl();
      for (int i = 0; i < m_UnitItemsList.size(); i++)
      {
        Component Item = m_UnitItemsList[i];
        StateControl.SetUnitItemHP(Item.Index, Item.HitPoints);
        Item.CurrentHitPoints = Item.HitPoints;
      }
    }
  }

  // ======================================
  // Point collision detector
  // ======================================

  // Call when tank deep in the water (Вызывается, когда танк глубоко заехал в воду)
  event void OnPointCollisionDetect(String _ObjectID)
  {
    // Destroy HullEngine may be changed (убиваем движок, можно заменить на что-то другое)
    SetUnitItemHPPercent("HullEngine", 0.0);
    
    GetObject("PointDetector").EnableDetector(false);
  }


  event void SetModelViewState(
      boolean _State
    )
  {
    // TMP
  }

}



